src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Short_Code__c</fullName>
        <description>Created as part of new requirements from Khalid on 4/11/2016.</description>
        <label>Short Code</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>organization</fullName>
        <active>true</active>
        <label>organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Amendment_Justification__c</fullName>
        <label>Amendment Justification</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Clarification_Summary__c</fullName>
        <label>Clarification Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes__c</fullName>
        <label>Continuation Changes</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <formula>NOFA_RFP__r.Corporate_Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corporate Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cost_Effectiveness_and_Budget_Adequacy__c</fullName>
        <label>Cost Effectiveness and Budget Adequacy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <label>Executive Summary</label>
        <length>60000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Intermediary_Justification__c</fullName>
        <label>Intermediary Justification</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Leadership_and_Team__c</fullName>
        <label>Leadership and Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Need__c</fullName>
        <label>Need</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Organizational_Capability__c</fullName>
        <label>Organizational Capability</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Design__c</fullName>
        <label>Project Design</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruitment_and_Development__c</fullName>
        <label>Recruitment and Development</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <label>Standard 424</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities__c</fullName>
        <label>Strengthening Communities</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_of_Accomplishments__c</fullName>
        <label>Summary of Accomplishments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VISTA_Assignment__c</fullName>
        <label>VISTA Assignment</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CNCS_Corporate_Program__c.object
<CustomObject>
    <fields>
        <fullName>Short_Code__c</fullName>
        <label>Short Code</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CNCS Corporate Structure</label>
    <nameField>
        <label>CNCS Corporate Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNCS Corporate Structure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Allow_Concept_Paper__c</fullName>
        <label>Require Concept Paper</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Amendment_Justification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amendment Justification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CNCS_Corporate_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Corporate Program Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CNCS_Corporate_Program__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Corporate_Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CNCS_Corporate_Program__c</referenceTo>
        <relationshipLabel>NOFOs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clarification_Summary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clarification Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Continuation Changes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Program Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cost_Effectiveness_and_Budget_Adequacy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cost Effectiveness and Budget Adequacy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluation_Summary_of_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evaluation Summary or Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Executive Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Fiscal_Yr__c</fullName>
        <label>NOFO Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Foster_Grandparents_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Foster Grandparents Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intermediary_Justification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intermediary Justification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leadership_and_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Leadership and Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NOFA_Sequence__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>NOFO Sequence</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Need__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organizational_Capability__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Organizational Capability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Design__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If your project is not found then add a new project under your Account.</inlineHelpText>
        <label>Project Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Project__c.Project__r.Status__c</field>
                <operation>notEqual</operation>
                <value>Closed</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>NOFOs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruitment_and_Development__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recruitment and Development</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard 424</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strengthening Communities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary_of_Accomplishments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Summary of Accomplishments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VISTA_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VISTA Assignment</label>
        <type>Checkbox</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>CNCS_Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CNCS Corporate Program</label>
        <referenceTo>CNCS_Corporate_Program__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <formula>NOFO_RFP__r.Corporate_Program__r.Name</formula>
        <label>Corporate Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Short_Code__c</fullName>
        <label>Short Code</label>
        <length>2</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NOFAtoApplicationUIExt2.cls
public class NOFAtoApplicationUIExt2 
{
    Public Application3__c applicationInput{get;set;}
    Public id tempid;
    public String id;
    public String projectid; 
     public String corporateprogramid;
    public boolean isDraft{get;set;}
    Public NOFA__c Nofa{get;set;}
    Project__c pro{get;set;}
    public String cid{get;set;} 
    public string lic{get;set;}
     
     
    public NOFAtoApplicationUIExt2 (ApexPages.StandardController controller) 
  
    {
        User u= [select id, name, profile.userlicense.name from user where id=:userinfo.getUserId()];
        lic=u.profile.userlicense.name;
        isDraft = false;
        applicationInput= new Application3__c();
        system.debug('params = '+Apexpages.currentPage().getParameters());
        tempid=controller.getRecord().id;
        id=Apexpages.currentPage().getParameters().get('id');
        projectid=Apexpages.currentPage().getParameters().get('projectid');
        corporateprogramid=Apexpages.currentPage().getParameters().get('corporateprogramid');
        System.debug('Valueofid'+id+'*****'+projectid);
        //  applicationInput.Project__c=projectid; 
        If(id!=null && id!='')
        Nofa=[Select ID, Allow_Concept_Paper__c,Name,Fiscal_Yr__c,Corporate_Program__r.Short_Code__c,CNCS_Corporate_Program__r.Id,CNCS_Corporate_Program__r.Name,NOFA_Sequence__c,Intermediary_Justification__c,Need__c,Clarification_Summary__c,Continuation_Changes__c,VISTA_Assignment__c,Project_Name__c,Summary_of_Accomplishments__c,Leadership_and_Team__c,Cost_Effectiveness_and_Budget_Adequacy__c,Organizational_Capability__c,Executive_Summary__c,Other__c,Amendment_Justification__c,Strengthening_Communities__c,Recruitment_and_Development__c,Foster_Grandparents_Only__c,Evaluation_Summary_of_Plan__c,Standard_424__c,Program_Design__c,Program_Management__c,RSVP_Only__c from NOFA__c where id=:id];
       // System.debug('Valueofid'+id+'$$$$$'+Nofa.CNCS_Corporate_Program__r.Module__c);   
       applicationInput.NOFA_RFP__c=id; 
       //if(Nofa.CNCS_Corporate_Program__r.Module__c!=null)
      // applicationInput.Module__c=Nofa.CNCS_Corporate_Program__r.Module__c;
        //  applicationInput.Project__c=projectid; 
    }
   
   public PageReference Apply(){
     if(applicationInput.Project__c==null){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Please Select a Project to Proceed'));
        return null;
     }
     projectid=applicationInput.Project__c;
     Profile p = [Select Id,Name from Profile where Name = 'State Commission Profile'];
     Project__c project = [Select Id,name from Project__c where Id = :applicationInput.Project__c];
     
     if(Apexpages.currentPage().getParameters().get('frmPrimeApp')=='Yes'){
        Schema.DescribeSObjectResult r = Prime_Application__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        String PrimeAppName;
        if(nofa.Fiscal_Yr__c!=null && nofa.Corporate_Program__r.Short_Code__c!=null && nofa.NOFA_Sequence__c!=null){
            PrimeAppName = nofa.Fiscal_Yr__c.Right(2)+nofa.Corporate_Program__r.Short_Code__c+'00'+nofa.NOFA_Sequence__c;
        }
        if(userInfo.getProfileId()==p.Id){
            return new PageReference('/statecommission/'+keyPrefix+'/e?retURL=%2F'+nofa.Id+'&'+System.Label.NOFO_Name+'='+nofa.Name+'&'+System.Label.Corp_Structure_Prime_App+'='+nofa.CNCS_Corporate_Program__r.Name+'&'+System.Label.Project_Prime_Application+'='+project.Name+'&Name='+PrimeAppName);
        }else{
            return new PageReference('/'+keyPrefix+'/e?retURL=%2F'+nofa.Id+'&'+System.Label.NOFO_Name+'='+nofa.Name+'&'+System.Label.Corp_Structure_Prime_App+'='+nofa.CNCS_Corporate_Program__r.Name+'&'+System.Label.Project_Prime_Application+'='+project.Name+'&Name='+PrimeAppName);
        }       
     }
    // corporateprogramid=Nofa.CNCS_Corporate_Program__r.Module__c;
     if(Nofa.Allow_Concept_Paper__c == 'Yes'){
       if(Apexpages.currentPage().getParameters().get('primeApplicationId')!=null){
          string primeApplicationId = Apexpages.currentPage().getParameters().get('primeApplicationId');
          return new Pagereference('/apex/NOFAtoConceptPaperUI?id='+id+'&projectid='+projectid+'&primeApplicationId='+primeApplicationId);
       }else{   
          return new Pagereference('/apex/NOFAtoConceptPaperUI?id='+id+'&projectid='+projectid+'&corporateprogramid='+corporateprogramid);
       }
     }
     else
     {  
        
        if(Apexpages.currentPage().getParameters().get('submittedLate')!=null){
             if(Apexpages.currentPage().getParameters().get('primeApplicationId')!=null && Apexpages.currentPage().getParameters().get('opentoApps') == 'Accepting Sub-Applications'){
                string primeApplicationId = Apexpages.currentPage().getParameters().get('primeApplicationId');
                return new Pagereference('/apex/NOFAtoApplicationUI?id='+id+'&projectid='+projectid+'&submittedLate=Yes'+'&primeApplicationId='+primeApplicationId);            
             }
             else if(Apexpages.currentPage().getParameters().get('primeApplicationId')!=null && Apexpages.currentPage().getParameters().get('opentoApps') != 'Accepting Sub-Applications'){                 
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Sub Applications can be only created if Prime Application is Accpeting Sub-Applications'));
                    return null;                
             }
             else{
                return new Pagereference('/apex/NOFAtoApplicationUI?id='+id+'&projectid='+projectid+'&submittedLate=Yes');
             }
             
        }else{
            if(Apexpages.currentPage().getParameters().get('primeApplicationId')!=null && Apexpages.currentPage().getParameters().get('opentoApps') == 'Accepting Sub-Applications'){
                string primeApplicationId = Apexpages.currentPage().getParameters().get('primeApplicationId');
                return new Pagereference('/apex/NOFAtoApplicationUI?id='+id+'&projectid='+projectid+'&submittedLate=Yes'+'&primeApplicationId='+primeApplicationId);            
            }
            else if(Apexpages.currentPage().getParameters().get('primeApplicationId')!=null && Apexpages.currentPage().getParameters().get('opentoApps') != 'Accepting Sub-Applications'){              
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Sub Applications can be only created if Prime Application is Accpeting Sub-Applications'));
                    return null;                
            }else{
                return new Pagereference('/apex/NOFAtoApplicationUI?id='+id+'&projectid='+projectid);
            }
        }
     
     }
     
     
  }
   
      
  public pagereference createProject(){ 
    String userid = UserInfo.getUserID();
    string OrgIDinURL;
    system.debug('####getuserID###' + userid);
    User u = [Select ID,AccountID,ContactID  From User where ID= : userid];
    if (!Test.isRunningTest())
    {
        contact con = [select id,accountid,account.name from contact where ID=:u.contactID];
        OrgIDinURL = con.accountId;
    }    
    Field_Ids__c f = Field_Ids__c.getInstance('Project Organization');
    String fieldId = f.Id__c;
    system.debug('####OrgIDinURL ###' + OrgIDinURL);

    Schema.DescribeSObjectResult r = Project__c.sObjectType.getDescribe();
    String keyPrefix = r.getKeyPrefix();
    return new Pagereference('/apex/ProjectCreationPage?AccountId='+OrgIDinURL+'&cncsCorpProgramId='+nofa.CNCS_Corporate_Program__r.Id);   
   
  }
  
  public pagereference cancel(){    
      Schema.DescribeSObjectResult r = NOFA__c.sObjectType.getDescribe();
      String keyPrefix = r.getKeyPrefix();
      return new Pagereference('/'+keyPrefix+'/o');
  }
 }