src/objects/Action_Reports__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_ID__c</fullName>
        <label>NOFO ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Action Reports</relationshipLabel>
        <relationshipName>Action_Reports</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA_ID__r.NOFA_name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFO Name</label>
        <type>Text</type>
    </fields>
    <label>Action Reports</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Action Reports ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <description>Populates the Master Award name from the Master Award related list.</description>
        <label>Master Award</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_ID__c</fullName>
        <formula>NOFA_RFP__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFO ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA_RFP__r.NOFA_name__c</formula>
        <label>NOFO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Amendment__c</fullName>
        <description>Amendment # for Amendment awards.</description>
        <label>Amendment #</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application ID related to Award.</description>
        <label>Application ID</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Committed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this flag when the Award is Being Committed. KY</description>
        <label>Committed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <label>Grant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting GO Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PO Certification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Organization e-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO CSHR Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO De-Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO De-Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Arrival</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <description>US # 2415</description>
        <label>Federal Award Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Award Identification Number</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Child_Awards__c</fullName>
        <formula>Master_Award__r.Number_of_Child_Awards__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of Child Awards</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sponsor_e_Signature__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Applicant should check this checkbox before Signing the Agreement.
Changed Label as per # 646.</description>
        <label>I agree to the above Agreement Statement</label>
        <type>Checkbox</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Child_Awards__c</fullName>
        <description>Roll up of all Awards.</description>
        <label>Number of Child Awards</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>NOFA_name__c</fullName>
        <label>NOFO Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Award</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/awardExtensionTest.cls
@istest

public class awardExtensionTest{

    Private Static testmethod void TestAward(){  
     Application3__c App = UtilityClass.createApplication();
     insert App;
    
   
     Award__c testawd = new Award__c();
   // Award__c objAwd = new Award__c();
        Pagereference pref = Page.AwardDetailPage;
        test.setCurrentPage(pref);
      //  Award__c testawd = UtilityClass.createAward();
         testawd.Application_ID__c = App.Id;
    Insert testawd;
        
        ApexPages.currentPage().getParameters().put('id',testawd.id);
        AwardExtension ext =new AwardExtension();
        ApexPages.StandardController stdcon = new ApexPages.StandardController(testawd);
        AwardExtension obj_awardExtension  = new AwardExtension(stdcon);
       
         obj_awardExtension.initMethod();
        // obj_awardExtension.AwardApp();
         obj_awardExtension.CertifiyApplicationbyPO();
          obj_awardExtension.ApproveGrantpreviouslycertifiedbyPO();
          obj_awardExtension.ApproveGrantpreviouslycertifiedbyPO();
          //obj_awardExtension.CertifyApplicationCommitted();
          obj_awardExtension.sendtopo();
          obj_awardExtension.sendtospo();
          obj_awardExtension.sendtoGO();
          obj_awardExtension.sendtoSGO();
          obj_awardExtension.CertifytoSGO();
          obj_awardExtension.commitfromSGO();
          obj_awardExtension.Obligatepgmtypenull();
         obj_awardExtension.CertifiyApplicationbyPO1();
          obj_awardExtension.sendtoXO();
          obj_awardExtension.Withdraw();
          obj_awardExtension.CSHRtoXO();
          obj_awardExtension.reject();
          obj_awardExtension.ReturntoRework();
          obj_awardExtension.returntoXO();
          obj_awardExtension.ApproveAgreementbyXO();
          obj_awardExtension.esign();
          obj_awardExtension.esignature();
          obj_awardExtension.moveWithoutCommitting();
          obj_awardExtension.esignaturebySPO();
          obj_awardExtension.AwardnonCS();
          obj_awardExtension.MovetoAward();
          obj_awardExtension.eSignaturebySGO();
          obj_awardExtension.SignAgreementtoXO();
          obj_awardExtension.confirmsign();
          obj_awardExtension.reload();
          obj_awardExtension.Amend();
         
        /* testawd.Grant_Status__c='Awaiting SGO Approval';
         update testawd;
         obj_awardExtension.CertifyApplicationCommitted();*/
                  
          }
    
    Private Static testmethod void TestAward1(){    
     Award__c objAwd = new Award__c();
     Pagereference pref = Page.AwardDetailPage;
     test.setCurrentPage(pref);
     
     Award__c testawd = UtilityClass.createAward();
    testawd.Grant_Status__c='Awaiting SGO Approval';
    testawd.Committed__c=true;
     Insert testawd;
        
        ApexPages.currentPage().getParameters().put('id',testawd.id);
        ApexPages.StandardController stdcon = new ApexPages.StandardController(testawd);
        AwardExtension obj_awardExtension  = new AwardExtension(stdcon);     
      obj_awardExtension.CertifyApplicationCommitted();
      } 
          
       
       
      
   Private Static testmethod void TestAward3(){    
    // Award__c objAwd = new Award__c();
     Pagereference pref = Page.AwardDetailPage;
     test.setCurrentPage(pref);
      Application3__c App = UtilityClass.createApplication();
   
        insert App;
        
               
        
        Award__c Award = new Award__c();
        //Award.Application_ID__c = App.Id;
        Award.NOFA_Name__c = app.NOFA_RFP__c;       
        Award.Name = 'Test Award';
        //Award.Master_Award__c = 
        //Award.Prime_Application__c = 
        Award.Organization__c = app.Organization__c;
        Award.Grant_Status__c = 'Awaiting PO Certification';
        Award.Grant__c = 'Test127262';
        //Award.Number_of_Child_Awards__c = 1;
        Award.Amendment__c=0;
        Award.RecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('App Award').getRecordTypeId();
     
    // Award__c testawd = UtilityClass.createAward();
     //testawd.Grant_Status__c='Awaiting SGO Approval';
     //testawd.Committed__c=true;
    // testawd.Application_ID__c=null;
     Insert Award;
        
        ApexPages.currentPage().getParameters().put('id',Award.id);
        ApexPages.StandardController stdcon = new ApexPages.StandardController(Award);
        AwardExtension obj_awardExtension  = new AwardExtension(stdcon);    
        //obj_awardExtension.app_Clonedfrom_List = new List<Application3__c>{App};
      obj_awardExtension.Amend();
     
      }  
   
   Private Static testmethod void TestAward4(){    
        
        Pagereference pref = Page.AwardDetailPage;
        test.setCurrentPage(pref);
        Award__c testawd = UtilityClass.createAward();
        Insert testawd;
        Award__c objAwd = new Award__c();
        objAwd=[select id, Grant_Status__c from Award__c where id=:testAwd.id];
        system.debug('@@@prash'+objAwd);
        objAwd.Grant_Status__c='Obligated';
        objAwd.Sponsor_e_Signature__c=true;
        objAwd.Committed__c=true;
        update objAwd;
        
     /*   ApexPages.currentPage().getParameters().put('id',testawd.id);
         
        AwardExtension ext =new AwardExtension();
        ApexPages.StandardController stdcon = new ApexPages.StandardController(testawd);
        AwardExtension obj_awardExtension  = new AwardExtension(stdcon);
        obj_awardExtension.AwardApp();
        
        objAwd=[select id, Grant_Status__c from Award__c where id=:testAwd.id];
        system.debug('@@@prash'+objAwd);
        objAwd.Grant_Status__c='Awarded';
        objAwd.Sponsor_e_Signature__c=true;
        update objAwd;*/
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        ApexPages.StandardController stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension  = new AwardExtension(stdcon);
        obj_awardExtension.AwardApp();
        obj_awardExtension.CertifyApplicationCommitted();
       // obj_awardExtension.sendtoGO();
        objAwd.Grant_Status__c='Awaiting GO Certification';
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
      //  obj_awardExtension.sendtoSGO();
       
        obj_awardExtension.CertifytoSGO();
        obj_awardExtension.Withdraw();
       // obj_awardExtension.esign();
      //  objAwd=[select id, Grant_Status__c from Award__c where id=:objAwd.id];
        
        objAwd.Grant_Status__c='Awaiting GO Certification';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension1  = new AwardExtension(stdcon);
        obj_awardExtension1.sendtoSGO();
        obj_awardExtension1.Obligatepgmtypenull();
         //Awaiting GO Certification
         
        objAwd.Grant_Status__c='Awaitinifg PO Certification';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension2  = new AwardExtension(stdcon);
     //  obj_awardExtension2.esign();
       obj_awardExtension2.reject();
       //obj_awardExtension2.ReturntoRework();
        //obj_awardExtension2.esign();
        
        objAwd.Grant_Status__c='Awaiting PO Certification';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension3  = new AwardExtension(stdcon);
        obj_awardExtension3.ReturntoRework();
        obj_awardExtension3.returntoXO();
        
         }
         
        Private Static testmethod void TestAward5(){     
        Pagereference pref = Page.AwardDetailPage;
        test.setCurrentPage(pref);
        Award__c testawd = UtilityClass.createAward();
        Insert testawd;
        Award__c objAwd = new Award__c();
        objAwd=[select id, Grant_Status__c from Award__c where id=:testAwd.id];
        system.debug('@@@prash'+objAwd);
         
        objAwd.Grant_Status__c='Awaiting SGO Approval';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
       ApexPages.StandardController stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension4  = new AwardExtension(stdcon);
       obj_awardExtension4.returntoXO(); 
      // obj_awardExtension4.MovetoAward();
        obj_awardExtension4.moveWithoutCommitting();
       
                
       /*objAwd.Grant_Status__c='Awaiting XO CSHR Approval';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension3  = new AwardExtension(stdcon);*/
        
        
                         
        objAwd.Grant_Status__c='Awaiting SPO Award';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension5  = new AwardExtension(stdcon);
        obj_awardExtension5.AwardnonCS();
        //obj_awardExtension5.MovetoAward();
      
      
        objAwd.Grant_Status__c='Awaiting SGO Approval';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension6  = new AwardExtension(stdcon);
        obj_awardExtension6.MovetoAward();
        obj_awardExtension6.sendtoGO();
         
         
        objAwd.Grant_Status__c='Awaiting SGO Approval';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension7  = new AwardExtension(stdcon);
        obj_awardExtension7.sendtoGO(); 
       
        
        objAwd.Grant_Status__c='Awaiting PO Certification';
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension8  = new AwardExtension(stdcon);
        obj_awardExtension8.esign();
       // obj_awardExtension8.reject();
       
        objAwd.Grant_Status__c='Awaiting SPO Approval';
        objAwd.Sponsor_e_Signature__c=true;
        update objAwd;
        Apexpages.currentPage().getParameters().put('id',objAwd.Id);
        stdcon = new ApexPages.StandardController(objAwd);
        AwardExtension obj_awardExtension9  = new AwardExtension(stdcon);
        obj_awardExtension9.esignaturebySPO(); 
        
        }
        
        Private Static testmethod void CreateAwardfromAwardReporting(){  
        Application3__c App = UtilityClass.createApplication();
        insert App;
         
         Id Nofaid = [Select name,NOFA_RFP__r.id from Application3__c where id=: App.id].NOFA_RFP__r.id ;
         System.debug('NOFA_Id1'+Nofaid);
         Action_Reports__c actionreport =new Action_Reports__c();
         actionreport.NOFA_ID__c=Nofaid;
         insert actionreport;
         
          Id AppAwardRecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('App Award').getRecordTypeId();
        
         List<Award__c> award_List = new List<Award__c>();
        
        Award__c testawd = new Award__c();
   
         testawd.Application_ID__c = App.Id;
         award_List.add(testawd);
       //  Insert testawd;
         
         Award__c testawd1 = new Award__c();
   
         testawd1.Application_ID__c = App.Id;
         testawd1.recordtypeId = AppAwardRecordTypeId;
         award_List.add(testawd1);
       //  Insert testawd;
        
        Insert award_List;
        
        Pagereference pref = Page.AwardDetailPage;
        test.setCurrentPage(pref);
        
        ApexPages.currentPage().getParameters().put('id',testawd.id);
        AwardExtension ext =new AwardExtension();
        ApexPages.StandardController stdcon = new ApexPages.StandardController(testawd);
        AwardExtension obj_awardExtension  = new AwardExtension(stdcon);
        
    Award__c awd =  [Select Application_ID__r.NOFA_RFP__r.id from Award__c where id=:testawd.id];
      System.debug('Award_Info^^^'+awd.Application_ID__r.NOFA_RFP__r.id);
    
         
       }
       
        }