src/objects/Agency_wide_Audit__c.object
<CustomObject>
    <label>Audit</label>
    <nameField>
        <displayFormat>Audit ID-{000}</displayFormat>
        <label>Audit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Assigned_User__c.object
<CustomObject>
    <fields>
        <fullName>Agency_wide_Audit_and_Assigned_Users__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency wide Audit and Assigned Users</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>PO</value>
            </filterItems>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>GO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Assigned_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Agency_wide_audit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agency wide audit</label>
        <referenceTo>Agency_wide_Audit__c</referenceTo>
        <relationshipLabel>Assigned Users</relationshipLabel>
        <relationshipName>Assigned_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assigned User</label>
    <nameField>
        <label>Assigned User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssignedUserHelper.cls
public without sharing class AssignedUserHelper {
	
	public static void shareAuditRecords(list<Assigned_User__c> newRecs){
		Profile aduitProfile = [Select Id from Profile where Name = 'Audit'];
		map<Id,Id> userIdtoAuditId = new map<Id,Id>();
		list<Agency_wide_Audit__Share> auditShares = new list<Agency_wide_Audit__Share>();
		for(Assigned_User__c a:newRecs){
			if(a.Agency_wide_audit__c != null && a.Agency_wide_Audit_and_Assigned_Users__c != null){
				userIdtoAuditId.put(a.Agency_wide_Audit_and_Assigned_Users__c,a.Agency_wide_audit__c);
			}
		}
		list<User> users = new list<User>([Select Id,Name,Email from User where Id in :userIdtoAuditId.keyset() and isActive = true and ProfileId != :aduitProfile.Id]);
		if(users.size()>0){
			for(User u: users){
				if(userIdtoAuditId.get(u.Id)!=null && u.Id != userInfo.getUserId()){
					 Agency_wide_Audit__Share  aShare = new Agency_wide_Audit__Share();
	                 aShare.ParentId = userIdtoAuditId.get(u.Id);
	                 aShare.userorgroupId = u.Id;
	                 aShare.AccessLevel = 'Edit';
	                 auditShares.add(aShare);
				}
			}
			if(auditShares.size()>0){
				insert auditShares;
			}
		}
	}
	
}