src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Cost_Effectiveness_and_Budget_Adequacy_C__c</fullName>
        <label>Cost Effectiveness and Budget Adequacy</label>
        <length>300</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>NCCC_Dates_CP__c</fullName>
        <description>This field is for the Concept Paper type of Application.</description>
        <label>NCCC Dates</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <label>Standard 424</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Populations_CP__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <label>Target Populations</label>
        <picklist>
            <picklistValues>
                <fullName>Adult ESL participants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Caregivers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children in Foster Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disadvantaged youth (K-12)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Families experiencing homelessness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formerly Incarcerated Adults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formerly Incarcerated Youth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head Start participants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Immigrants and refugees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individuals experiencing homelessness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-income communities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-income Hispanic/Latino</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-income Nat-Amer./Nat-AK/Pac-Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-focus Intermediary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None of the above</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People in hospice for terminal illness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People receiving mental health services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People receiving substance abuse service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with HIV/AIDS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>People with physical/mental disabilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Citizens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Students, general</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teachers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unemployed individuals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Veteran family members</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Veterans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victims/Survivors of violence and abuse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Youth (16-24) not in school or working</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Amendment_Justification_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Amendment Justification </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clarification_Summary_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Clarification Summary </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Continuation Changes </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Effectiveness_and_Budget_Adequacy_C__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Cost Effectiveness and Budget Adequacy </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluation_Summary_or_Plan_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Evaluation Summary or Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Executive_Summary_CP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Executive Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Focus_Areas_and_Objectives_NCCC_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Focus Areas and Objectives - NCCC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Have_funding_history_with_a_CNCS_Prog_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Have resource history w/a CNCS Program</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intermediary_Justification_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Intermediary Justification </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NCCC_Dates_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field shows up on the Concept Paper.</description>
        <label>NCCC Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Need </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizational_Capability_CP__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Organizational Capability </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other_NCCC_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Other- NCCC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Design_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Project Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Management_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Project Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recruitment_and_Development_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Recruitment and Development</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard 424</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Strengthening Communities </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Target_Populations_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Target Populations</label>
        <type>Checkbox</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NOFAtoNotificationUIExt.cls
public with sharing class NOFAtoNotificationUIExt 

{
    Public Application3__c applicationInput{get;set;}
    Public Id tempid;
    Public String rectype{get;set;}
    Public String rectypename{get;set;}
    public boolean isDraft{get;set;}
    public String id;
    public Boolean displayMsg{get;set;}
    Public NOFA__c Nofa{get;set;}
    Public User Usr {get;set;}
    public NOFAtoNotificationUIExt (ApexPages.StandardController controller) 
    {
        isDraft = false;
    applicationInput= new Application3__c();
    Usr=new User();
    displayMsg=False;
    tempid=controller.getRecord().id;
     id=Apexpages.currentPage().getParameters().get('id');
     String projectid = Apexpages.currentPage().getParameters().get('projectid');
     If(projectid!=null) 
    applicationInput.Project__c=projectid;
   //applicationInput.Organization__c=$User.Accoutid; 
    System.debug('Valueofid'+id);
     If(id!=null && id!='')
      Nofa=[Select NCCC_Dates_CP__c,Standard_424__c,Evaluation_Summary_or_Plan_CP__c,Program_Design_CP__c, Program_Management_CP__c, Recruitment_and_Development_CP__c, Strengthening_Communities_CP__c, Amendment_Justification_CP__c, 
            Other_CP__c, Continuation_Changes_CP__c, Clarification_Summary_CP__c, Cost_Effectiveness_and_Budget_Adequacy_C__c, Organizational_Capability_CP__c, Need_CP__c,
            Intermediary_Justification_CP__c, Executive_Summary_CP__c, Focus_Areas_and_Objectives_NCCC_CP__c, Target_Populations_CP__c,
            Have_funding_history_with_a_CNCS_Prog_CP__c, Other_NCCC_CP__c from NOFA__c where id=:id];
            
            rectype=[Select id,name from Recordtype where SObjectType='Application3__c' and name='Notification of Intent to Apply'].id;    
 Usr = [SELECT Phone,Accountid, Id FROM User WHERE Id = : UserInfo.getUserId()];
 
  applicationInput.Organization__c=Usr.Accountid;
  }
   
     Public PageReference SaveAsDraft(){
         PageReference Redirect;
     
         try{
         applicationInput.recordtypeid=rectype;
         applicationInput.NOFA_RFP__c=id;
         applicationInput.Grantee_Status__c='Submitted';
             insert applicationInput;
            Redirect = new PageReference('/'+applicationInput.id);
             
            return Redirect;
            }
         Catch(DMLException e){
         ApexPages.addMessages(e);
         System.debug('@@@@@@@@!!!!!'+e.getmessage());
 }
  
return null; 
                }   
       
              
      
       /* public pagereference createProject(){
         return new Pagereference('/a0W/e?retURL=%2Fa0W%2Fo');
          }    
   
   public PageReference save(){
 applicationInput.Status__c='Submitted';
     PageReference Redirect;
         try{  
            applicationInput.recordtypeid=rectype;        
            applicationInput.NOFA_RFP__c=id;
            Insert applicationInput;
            Redirect = new PageReference('/'+applicationInput.id);
            return Redirect;
           }
         Catch(DMLException e){
         System.debug('@@@@@@@@!!!!!'+e.getmessage());
         }
             return null;
         }         */
   

 }