src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Assessment_of_Quality_Indicators__c</fullName>
        <label>Assessment of Quality Indicators</label>
        <picklist>
            <picklistValues>
                <fullName>GPR Performance Measures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance with 30 day enrollment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance with 30 day exit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site visit or other monitoring (if applicable)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Significant opportunities of the grantee to national service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Significant risks of the grantee to national service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommend to Fund</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Recommend to Fund</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <label>Executive Summary</label>
        <length>60000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Organizational_Capability__c</fullName>
        <label>Organizational Capability</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <label>Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ranking_Justification__c</fullName>
        <label>Ranking Justification</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InlineEditAppToPrimeAppCntrl.cls
public class InlineEditAppToPrimeAppCntrl{
    
    public ApexPages.StandardController stdcontroller;
    public Prime_Application__c objPrimApp{get;set;}
    public Application3__c objApp{get;set;}
    public List<Application3__c> lstApp{get;set;}
    //public Boolean errValidationErorExplode{get;set;}

    public InlineEditAppToPrimeAppCntrl(){
    }
    
    public InlineEditAppToPrimeAppCntrl(ApexPages.StandardController p_controller){
    try{  
          //errValidationErorExplode=false;
          lstApp= new List<Application3__c>();
          this.stdcontroller= p_controller;
          this.objPrimApp= (Prime_Application__c)stdController.getrecord();
          readAppData();
      }
      catch(Exception exc){
           System.debug('*** Exception***InlineEditAppToPrimeAppCntrl Constructor***'+exc.getMessage()); 
      }
    }

    public void readAppData(){
        lstApp= new List<Application3__c>();
        Prime_Application__c objPrimAppTemp=new Prime_Application__c();
        try{
            objPrimAppTemp =[SELECT id, (select id,name,Rank__c,Assessment_of_Quality_Indicators__c,Organizational_Capability__c,Executive_Summary__c,
                                                Ranking_Justification__c,Status__c  
                                         from Applications__r) 
                             FROM Prime_Application__c where id = :objPrimApp.id ];
                             
            for(Application3__c objAppTemp : objPrimAppTemp.Applications__r)         {
                if(objAppTemp.Status__c!=null && (objAppTemp.Status__c.equalsIgnoreCase('Recommended to CNCS') || objAppTemp.Status__c.equalsIgnoreCase('Submitted to CNCS') 
                                                          || objAppTemp.Status__c.equalsIgnoreCase('Submitted Late to CNCS') || objAppTemp.Status__c.equalsIgnoreCase('Review In Progress')
                                                          || objAppTemp.Status__c.equalsIgnoreCase('Returned for Rework') || objAppTemp.Status__c.equalsIgnoreCase('Accepted')
                                                          || objAppTemp.Status__c.equalsIgnoreCase('Awarded'))){ 
                    lstApp.add(objAppTemp );
                }
            }
        }
        catch(Exception exc){
           System.debug('*** Exception***InlineEditAppToPrimeAppCntrl->method -readAppData() ***'+exc.getMessage()); 
        }
        
        System.debug('***lstApp***'+lstApp);
    }
    
    public PageReference SaveInlineChanges(){
       // system.debug(attended);
        system.debug(lstApp);
        try{
   
        // update attended;
         update lstApp;
         }
         catch(DMLException dmlExc){
           //errValidationErorExplode=true;
           System.debug('***DMLException***InlineEditAppToPrimeAppCntrl->method -SaveInlineChanges() ***'+dmlExc.getMessage());
         }
         catch(Exception exc){
             System.debug('*** Exception***InlineEditAppToPrimeAppCntrl->method -SaveInlineChanges() ***'+exc.getMessage());
         }
   
    //return ApexPages.CurrentPage();
    return null;
    }
    
    
}