src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ex_Officer_Cost_Share__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ex. Officer Cost Share</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Executive_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executive Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grants_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grants Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <description>Populates the Master Award name from the Master Award related list.</description>
        <label>Master Award</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA_RFP__r.NOFA_name__c</formula>
        <label>NOFO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Grants_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Grants Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Program_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Program Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Application__c</fullName>
        <description>Field to check if the Application is a Sub-Application or regular Application.</description>
        <formula>IF( ISPICKVAL( NOFA_RFP__r.Allow_Prime_Applicants_and_Sub_Applicant__c , &apos;Yes&apos;), &apos;Yes&apos;, &apos;No&apos;)</formula>
        <label>Sub-Application?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Application__c</fullName>
        <description>Type of Application</description>
        <inlineHelpText>Please select Type of Application</inlineHelpText>
        <label>Type of Application</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Application_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application ID related to Award.</description>
        <label>Application ID</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Executive_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Executive Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grants_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Grants Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Award Identification Number</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Grants_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Grants Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Senior_Program_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Senior Program Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>XO_CSHR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CSHR Executive Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award6</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grants_Officer__c</fullName>
        <label>Grants Officer</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Officer__c</fullName>
        <label>Program Officer</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the Master Award</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the Project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApplicationHandler.cls
public class ApplicationHandler {

Map<Id,Master_Award__c> MA_Map = new Map<Id,Master_Award__c>();
List<Master_Award__c> MA_List = new List<Master_Award__c>();
List <Award__c> AwardInsert = new List <Award__c> ();
Id ApplicationID=Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
Id AMARecordTypeId = Schema.SObjectType.Master_Award__c.getRecordTypeInfosByName().get('App Master Award').getRecordTypeId();
Id SAMARecordTypeId = Schema.SObjectType.Master_Award__c.getRecordTypeInfosByName().get('Sub App Master Award').getRecordTypeId();
Id AARecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('App Award').getRecordTypeId();
Id SAARecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('Sub App Award').getRecordTypeId();


public void handleTrigger(Application3__c[] trigNew, Application3__c[] trigOld) {
      /*  if (Trigger.isBefore) {
            if (Trigger.isInsert) {
                handleBeforeInsert(trigNew);
            } else if (Trigger.isUpdate) {
                handleBeforeUpdate(trigNew, trigOld);
            }
        } else if (Trigger.isAfter) {
            if (Trigger.isUpdate) {
                handleAfterUpdate(trigNew, trigOld);
            }
        }
    
    */    
    handleAfterUpdate(trigNew, trigOld);
}


// After Update Methods
// "CreateAward" logic starts here
private void handleAfterUpdate (Application3__c[] trigNew, Application3__c[] trigOld) {

for (Application3__c App: trigNew)
{
 
if (App.Status__c == 'Accepted' && App.RecordTypeID == '012r00000004KU5' && App.Type_of_Application__c == 'New') {

Master_Award__c MA = new Master_Award__c ();
if(App.Sub_Application__c=='Yes'){
MA.recordtypeid=SAMARecordTypeId;
MA.Application__c = App.id;
}
else if (App.Sub_Application__c == 'No') {
MA.recordtypeid=AMARecordTypeId;
MA.Application__c = App.id;
}
MA_List.add(MA);
}
} 
Insert MA_List;

for(Master_Award__c ma : [Select id,name,Application__c from Master_Award__c where ID IN: MA_List])
{
    MA_Map.put(ma.Application__c,ma);
}

List<Award__c> aw_List = new List<Award__c>();
for (Application3__c App: trigNew)
{
  System.debug('App_ID'+App.id);
  if (App.Status__c == 'Accepted' && App.RecordTypeID == '012r00000004KU5') {
Award__c Aw = new Award__c ();
if(App.Sub_Application__c=='Yes'){
   if(MA_Map.containsKey(App.id))
       Aw.Master_Award__c=MA_Map.get(App.id).id;
Aw.Name = App.Name;
Aw.recordtypeid=SAARecordTypeId;
Aw.NOFA_Name__c = App.NOFA_RFP__c;
Aw.Project__c = App.Project__c;
system.debug('app Id = '+app.Id);
Aw.Application_ID__c = App.ID;
Aw.Program_Officer__c = App.Program_Officer__c;
Aw.Senior_Program_Officer__c = App.Senior_Program_Officer__c;
Aw.Executive_Officer__c = App.Executive_Officer__c;
Aw.XO_CSHR__c = App.Ex_Officer_Cost_Share__c;
Aw.Senior_Grants_Officer__c = App.Senior_Grants_Officer__c;
Aw.Grants_Officer__c = App.Grants_Officer__c; 
}
else if (App.Sub_Application__c=='No') {
if(MA_Map.containsKey(App.id))
       Aw.Master_Award__c=MA_Map.get(App.id).id;
Aw.Name = App.Name;
Aw.recordtypeid=AARecordTypeId;
Aw.NOFA_Name__c = App.NOFA_RFP__c;
Aw.Project__c = App.Project__c;
system.debug('app Id = '+app.Id);
Aw.Application_ID__c = App.ID;
Aw.Program_Officer__c = App.Program_Officer__c;
Aw.Senior_Program_Officer__c = App.Senior_Program_Officer__c;
Aw.Executive_Officer__c = App.Executive_Officer__c;
Aw.XO_CSHR__c = App.Ex_Officer_Cost_Share__c;
Aw.Senior_Grants_Officer__c = App.Senior_Grants_Officer__c;
Aw.Grants_Officer__c = App.Grants_Officer__c; 
}
aw_List.add(Aw);
      }
} 
Insert aw_List;
}
// "CreateAward" logic Ends here

}