src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <recordTypes>
        <fullName>Concept_Paper</fullName>
        <active>true</active>
        <label>Concept Paper</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Foster_Grandparents_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Foster Grandparents Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RSVP_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSVP Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>NOFO Status</label>
        <picklist>
            <picklistValues>
                <fullName>Setup in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicationEditpageExt1.cls
Public Class ApplicationEditpageExt1{

public Application3__c applicationInput {get; set;}
public Boolean displayMsg{get;set;}
public String id;
public Boolean fieldSet1Visibility {get; set;}
public Boolean fieldSet2Visibility {get; set;}
public Boolean fieldSet3Visibility {get; set;}
public string productType {get;set;}

public list<Application3__c> typeOfProduct {get; set;}

Public ApplicationEditpageExt1(ApexPages.StandardController controller){
  applicationInput=new Application3__c();
  displayMsg=False;
  id=Apexpages.currentPage().getParameters().get('id');
 applicationInput.Status__c='None';
  If(id!=null && id!='')
  //Nofa=[Select Foster_Grandparents_Only__c,RSVP_Only__c from NOFA__c where id=:id]; 
  applicationInput= [Select id,Status__c FROM Application3__c where id = :id];
  
}

public PageReference edit() {   
PageReference Redirect;
If(id!=null && id!=''){
Redirect = new PageReference('/apex/Application?id='+id);

return Redirect;
}

return null;
}



public PageReference save() {   
PageReference Redirect;
If(id!=null && id!=''){
Redirect = new PageReference('/'+id);
applicationInput.Status__c='Submitted';
update applicationInput;
//return Redirect;
}
else
{

applicationInput.Status__c='Submitted';
insert applicationInput;
system.debug('record id-->'+applicationInput.id);

Redirect = new   PageReference('/apex/ApplicationDetailPage?id='+applicationInput.id);
Redirect.setRedirect(true);
//return newpage;
}
return Redirect;
}




public PageReference setEditVisibility() {

        fieldset1Visibility = FALSE;
        fieldset2Visibility = FALSE;
        fieldset3Visibility = FALSE;

       /* if(record.Concept_Paper!= null) {
            productType = record.Concept_Paper;
        } else {
            productType = productSelection;
        }

*/
        if (applicationInput.Status__c == 'None') {

                fieldset1Visibility = false;
        } else if (applicationInput.Status__c == 'Product 2') {

                fieldset2Visibility = TRUE;
        } 
        return null;
    }
    
    Public PageReference SaveAsDraft()
    {
          PageReference Redirect;
        If(id!=null && id!=''){
        Redirect = new PageReference('/apex/ApplicationDetailPage'+id);
        applicationInput.Status__c='Pre-Submitted';      
        insert applicationInput;
        System.debug('app;lication values-->'+applicationInput);
       // return Redirect;
        }
        
        else
        {

        applicationInput.Status__c='Pre-Submitted';
        insert applicationInput;
        system.debug('record id-->'+applicationInput.id);

        Redirect = new   PageReference('/apex/ApplicationDetailPage?id='+applicationInput.id);
        Redirect.setRedirect(true);
        //return newpage;
        }

            
        return Redirect;
          
    }
        
      Public PageReference Reopen()
    {
          PageReference Redirect;
        If(id!=null && id!=''){
        Redirect = new PageReference('/'+id);
      
        update applicationInput;
        System.debug('app;lication values-->'+applicationInput);
        return Redirect;
        }
            
        return null;
          
    }  
    
     

}