src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_Feedback_Summary__c</fullName>
        <label>Application Feedback Summary</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Counties__c</fullName>
        <label>Counties</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EO_12372_Process__c</fullName>
        <inlineHelpText>Is this Application Subject to Review by State Executive Order 12372 Process?</inlineHelpText>
        <label>EO 12372 Process</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State_and_or_Territories__c</fullName>
        <label>State and/or Territories</label>
        <picklist>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Application__c</fullName>
        <description>Type of Application</description>
        <inlineHelpText>Please select Type of Application</inlineHelpText>
        <label>Type of Application</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>NOFO Status</label>
        <picklist>
            <picklistValues>
                <fullName>Setup in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>EO_12372_Process__c</fullName>
        <inlineHelpText>Is this Application Subject to Review by State Executive Order 12372 Process?</inlineHelpText>
        <label>EO 12372 Process</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Application__c</fullName>
        <label>Type of Application</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the Project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ApplicationTest.cls
@isTest
private class ApplicationTest {
    
    public static ApplicationEditpageExt ext;
    public static CustomSendEmailController customExt;
    public static CustomSendEmailController customExt2;
    public static CustomSendEmailController customExt3;
    public static CustomSendEmailController customExt4;
    public static NofaSelectionCont nofaselectExt;
    public static NOFAtoApplicationUIExt nofaToAppExt;
    
    static testMethod void ApplicationHelperTest() {
        
        Application3__c app = UtilityClass.createApplication();  
        insert app;   
        
        Application3__c app2 = new Application3__c(Name='Test App 2');
        app2.RecordTypeId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        app2.Project__c = app.Project__c;
        app2.Status__c = 'In Progress';
        app2.Grantee_Status__c = 'In Progress';
        app2.NOFA_RFP__c = app.NOFA_RFP__c;
        app2.Type_of_Application__c = 'New';
        app2.Application_Feedback_Summary__c = 'Test';
        app2.State_and_or_Territories__c = 'GA,HI,VA';
        app2.Counties__c = 'Fairfax,Leesburg';
        app2.EO_12372_Process__c = 'No';
        app2.Other__c = 'test';
        app2.Applicant_Delinquent_on_any_Federal_Debt__c = 'No';
        app2.Evaluation_Summary_or_Plan__c =  'test';
        app2.Cost_Effectiveness_and_Budget_Adequacy__c = 'Test';
        app2.Organization_Capability__c = 'test';
        app2.Executive_Summary__c = 'Test';
        app2.Education__c = 'Teacher Corps'; 
        app2.Characteristics_Priorities__c = 'test';
        insert app2;
        
    }
    
    static testMethod void ApplicationEditTest(){
        Application3__c app = UtilityClass.createApplication();  
        insert app; 
        
        Apexpages.currentPage().getParameters().put('id',app.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Application3__c());
        ext = new ApplicationEditpageExt(controller);
        
        ext.edit();
        ext.getThis();
        ext.isContinuingApp = false;
        //ext.save1();
        ext.Validate();
        ext.SaveAsDraft();
        ext.cancel();
        
    }
    
    static testMethod void customSendEmailContTest(){
        Application3__c app = UtilityClass.createApplication();
        insert app;
        
        /*EmailTemplate emT = UtilityClass.createEmailTemplate();
        emT.Body = '{!User.Name},{!Application3__c.Comments__c},{!NOFA__c.CreatedBy},{Current Date},{Authorized Representative Name},{Legal Applicant Name}'+
        '{Authorized Representative TITLE},{Legal Applicant Address},{Prefix} {LastName},{Application ID},{NOFA Name},{Date of Applicant’s correspondence}'+
        '{Fiscal year},{CNCS Program Director Name},{CNCS Program Director Title},{CNCS Program Name},{Application Due Date},{Application Submission Date}'+
        '{Intent Due Date from Notice},{Director of OGPO Name},{Director of OGPO TITLE},{Office Title of OGPO}';        
        insert emT;*/
         
        Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Accepted');
        Apexpages.currentPage().getParameters().put('tmpName','Concept_Paper_Approved');    
        //ApexPages.StandardController controller = new ApexPages.StandardController(new Application3__c());
        customExt = new CustomSendEmailController();
        customExt.sendEmails();
        customExt.cancel();        
        
        Apexpages.currentPage().getParameters().put('status',null);
        customExt2 = new CustomSendEmailController();
        customExt2.sendEmails();
        customExt2.cancel(); 
        
        Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Rejected');
        Apexpages.currentPage().getParameters().put('tmpName','Concept_Paper_Rejected_Email');      
        //customExt = new CustomSendEmailController();
        customExt.sendEmails();
        customExt.cancel(); 
        
        /*Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Return to Rework');
        Apexpages.currentPage().getParameters().put('tmpName','Application_Retrun_to_Rework');      
        //customExt = new CustomSendEmailController();
        customExt.sendEmails();
        customExt.cancel();
        
        Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Accepted');
        Apexpages.currentPage().getParameters().put('tmpName','Application_Accepted');      
        //customExt = new CustomSendEmailController();
        customExt.sendEmails();
        customExt.cancel();
        
        Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Rejected');
        Apexpages.currentPage().getParameters().put('tmpName','Application_Rejected');      
        //customExt = new CustomSendEmailController();
        customExt.sendEmails();
        customExt.cancel();*/
        
        Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Appeal Approved');
        Apexpages.currentPage().getParameters().put('tmpName','Appeal_Approved_Notification');      
        customExt3 = new CustomSendEmailController();
        customExt3.sendEmails();
        customExt3.cancel();  
        
        Apexpages.currentPage().getParameters().put('appId',app.Id);
        Apexpages.currentPage().getParameters().put('toAddresses','testEmail@test.com');
        Apexpages.currentPage().getParameters().put('status','Non Compliant');
        Apexpages.currentPage().getParameters().put('tmpName','Non_Compliant_Notification');        
        customExt4 = new CustomSendEmailController();
        customExt4.sendEmails();
        customExt4.cancel();                        
    
    }
    
    static testMethod void nofaSelectionTest(){
        Application3__c app = UtilityClass.createApplication();
        insert app;
        
        
        Application3__c app2 = new Application3__c(Name='Test App 2');
        app2.RecordTypeId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        app2.Project__c = app.Project__c;
        app2.Status__c = 'In Progress';
        app2.Grantee_Status__c = 'In Progress';
        app2.NOFA_RFP__c = app.NOFA_RFP__c;
        app2.Type_of_Application__c = 'New';
        app2.Application_Feedback_Summary__c = 'Test';
        app2.State_and_or_Territories__c = 'GA,HI,VA';
        app2.Counties__c = 'Fairfax,Leesburg';
        app2.EO_12372_Process__c = 'No';
        app2.Other__c = 'test';
        app2.Applicant_Delinquent_on_any_Federal_Debt__c = 'No';
        app2.Evaluation_Summary_or_Plan__c =  'test';
        app2.Cost_Effectiveness_and_Budget_Adequacy__c = 'Test';
        app2.Organization_Capability__c = 'test';
        app2.Executive_Summary__c = 'Test';
        app2.Education__c = 'Teacher Corps'; 
        app2.Characteristics_Priorities__c = 'test';
        insert app2;
        
        Apexpages.currentPage().getParameters().put('parentId',app.Id);
        Apexpages.currentPage().getParameters().put('id',app2.Id);
        Apexpages.currentPage().getParameters().put('isContinuingApp','fasle');
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Application3__c());
        nofaselectExt = new NofaSelectionCont(controller);
        
        nofaselectExt.continueApp();
        nofaselectExt.cancel();       
        
        Apexpages.currentPage().getParameters().put('isContinuingApp','true');
        nofaselectExt.continueApp();    
        
    }
    
    static testMethod void NofaToApplicationTest(){
        Application3__c app = UtilityClass.createApplication();
  
        NOFA__c nofa = [Select Id,Name from NOFA__c where Id = :app.NOFA_RFP__c];
        
        Apexpages.currentPage().getParameters().put('id',app.NOFA_RFP__c);
        Apexpages.currentPage().getParameters().put('projectid',app.Project__c);
        Apexpages.currentPage().getParameters().put('primeApplicationId',app.Prime_Application__c); 
        
        ApexPages.StandardController controller = new ApexPages.StandardController(nofa);
        nofaToAppExt = new NOFAtoApplicationUIExt(controller);
        
        nofaToAppExt.getThis();
        nofaToAppExt.Validate();
        nofaToAppExt.SaveAsDraft();
        nofaToAppExt.createProject();
        //nofaToAppExt.save1();
        //nofaToAppExt.Validate();         
        
    }
    
}