src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Natural_and_Other_Disasters__c</fullName>
        <label>Natural and Other Disasters</label>
        <picklist>
            <picklistValues>
                <fullName>Engaging participants</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disaster Assistance Provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individuals Assisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>At-Risk Ecosystems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity Building &amp; Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Veterans &amp; Families Served</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_On__c</fullName>
        <description>User who submits the Application - user clicks Submit button.</description>
        <label>Submitted On</label>
        <type>DateTime</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>NOFO Status</label>
        <picklist>
            <picklistValues>
                <fullName>Setup in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_On__c</fullName>
        <label>Submitted On</label>
        <type>Date</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA_Group__c.object
<CustomObject>
    <fields>
        <fullName>Review_of__c</fullName>
        <label>Review of</label>
        <picklist>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concept papers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO Group</label>
    <nameField>
        <displayFormat>NOFA Group ID-{0000}</displayFormat>
        <label>NOFO Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describes the status of that particular stage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MultipleControllerTest.cls
@isTest
private class MultipleControllerTest {

    static testMethod void rlControllerTest() {
        
        Application3__c app = UtilityClass.createApplication();
        insert app;
        
        RLController cont = new RLController();
        cont.aFields = 'Name,Organization__c,Status__c,Grantee_Status__c,Submitted_On__c';
        cont.aObjType = 'Application3__c';
        cont.arecId = app.NOFA_RFP__c;
        cont.arecordType = 'Application';
        cont.arelationfield = 'Nofa_Rfp__c';
        
        List<SelectOption> options = cont.options;
        //cont.ColumnWrapList;
        cont.getobjList();
        cont.edit();
        cont.LoadObjectList(app.NOFA_RFP__c, cont.aObjType, cont.arecordType, cont.aFields, cont.arelationfield);
        cont.run();
        String tmpStr = cont.aFields;
        String[] aFieldsList= tmpStr.split(',');
        //cont.LoadColumnList(cont.aobjType, aFieldsList);
       // cont.getrecordTypeId(cont.aobjType, cont.arecordType);
        
    }
    
    static testMethod void multiselectComponentControllerTest() {
        Application3__c app = UtilityClass.createApplication();
        app.Natural_and_Other_Disasters__c = 'test 1;test 2';
        insert app;
        
        MultiSelectComponentController cont = new MultiSelectComponentController(); 
        cont.fieldName = 'Natural_and_Other_Disasters__c';
                
        ApexPages.StandardController controller = new ApexPages.StandardController(app);
        cont.appEdit = new ApplicationEditpageExt(controller);                       
        cont.appEdit.applicationInput = app;
        
        /*ApexPages.StandardController controller2 = new ApexPages.StandardController(app);
        cont.cPaperEdit = new ConceptpapereditExt(controller2);                             
        cont.cPaperEdit.applicationInput = app;*/
        
        list<selectOption> options = cont.options;
        cont.selected = new list<string>{'Test 1'};
        cont.deselected = new list<string>{'Test 2'};
        cont.selecting();        
        list<selectOption> options2 = cont.selectedOptions;
        cont.deselecting();
        cont.assignOptions(options, cont.fieldName);    
        
        
    }
    
    static testMethod void customLookupControllerTest() {        
        NOFA_Group__c nfgrp = UtilityClass.createNofaGroup();
        insert nfgrp;
        
        Stages__c stage = UtilityClass.createStage();
        stage.NOFA_Group__c = nfgrp.Id;
        insert stage;
        
        Paneling__c panel = UtilityClass.createPanel();
        panel.Stage_Number__c = stage.Id;
        insert panel;
        
        Application3__c app = UtilityClass.createApplication();
        insert app;
        
        NOFA_Member__c nofaMember = new NOFA_Member__c();
        nofaMember.NOFA_Group__c = nfgrp.Id;
        nofaMember.NOFA__c = app.NOFA_RFP__c;
        insert nofaMember;
        
        Apexpages.currentPage().getParameters().put('lksrch','test');
        Apexpages.currentPage().getParameters().put('parentId',panel.Id);
        CustomLookupController cont = new CustomLookupController();
        cont.search();        
        
    }
    
    static testMethod void customLookupControllerTest2(){
                
        NOFA_Group__c nfgrp = UtilityClass.createNofaGroup();
        nfgrp.Review_of__c = 'Concept papers';
        insert nfgrp;
        
        Stages__c stage = UtilityClass.createStage();
        stage.NOFA_Group__c = nfgrp.Id;
        insert stage;
        
        Paneling__c panel = UtilityClass.createPanel();
        panel.Stage_Number__c = stage.Id;
        insert panel;
        
        Application3__c app = UtilityClass.createConceptPaper();
        insert app;
        
        NOFA_Member__c nofaMember = new NOFA_Member__c();
        nofaMember.NOFA_Group__c = nfgrp.Id;
        nofaMember.NOFA__c = app.NOFA_RFP__c;
        insert nofaMember;
        
        Apexpages.currentPage().getParameters().put('lksrch','test');
        Apexpages.currentPage().getParameters().put('parentId',panel.Id);
        CustomLookupController cont = new CustomLookupController();
        cont.search();
        
    }
    
    
}