src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Amendment_Justification__c</fullName>
        <label>Amendment Justification</label>
        <length>4000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes__c</fullName>
        <label>Continuation Changes</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Environment_Stewardship_CP__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <label>Environment Stewardship</label>
        <picklist>
            <picklistValues>
                <fullName>At-Risk Ecosystems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awareness &amp; Stewardship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Efficiency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green Jobs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Have_funding_history_with_any_CNCS_org__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <inlineHelpText>Has your org been funded or resourced through any of CNCS Programs?</inlineHelpText>
        <label>Have resource history with any CNCS org?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Design__c</fullName>
        <label>Project Design</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Program_Management__c</fullName>
        <label>Project Management</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Strengthen_Communities__c</fullName>
        <label>Strengthening Communities</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities__c</fullName>
        <label>Strengthening Communities</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_of_Application__c</fullName>
        <description>Type of Application</description>
        <inlineHelpText>Please select Type of Application</inlineHelpText>
        <label>Type of Application</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amendment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NOFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist for storing the type of document/attachment</description>
        <label>File Type</label>
        <picklist>
            <picklistValues>
                <fullName>1199 Direct Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Articles of Incorporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor’s Statement Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Financial Report User Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Management Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Statement Audit or SF-990</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Certification Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governing Body Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRS Certification of Non-Profit Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor Union Concurrence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List of names of any funding organizations/sources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logic Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Match Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiated indirect cost agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organizational Chart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipient contact Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor/Project Director Position Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor&apos;s Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1199 Direct Deposit Contact Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAE Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAE Waiver Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>View__c</fullName>
        <description>hyper Link to the actual attachment</description>
        <formula>IF(OR($Profile.Name == &apos;Applicant&apos;,$Profile.Name == &apos;Grantee Admin&apos;) , HYPERLINK(&quot;/granteeportal/servlet/servlet.FileDownload?file=&quot;+Attachment_Id__c, &quot;Click Here to Download File&quot;),IF($Profile.Name==&apos;Expert Reviewers&apos;, HYPERLINK(&quot;/expertreviewers/servlet/servlet.FileDownload?file=&quot;+Attachment_Id__c, &quot;Click Here to Download File&quot;),HYPERLINK(&quot;/servlet/servlet.FileDownload?file=&quot;+Attachment_Id__c, &quot;Click Here to Download File&quot;)) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>View Link</label>
        <type>Text</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Amendment_Justification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amendment Justification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Continuation Changes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Environmental_Stewardship_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Environmental Stewardship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Design_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Project Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Design__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Management_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Project Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Strengthening Communities </label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strengthening Communities</label>
        <type>Checkbox</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicationCheck.cls
public with sharing class ApplicationCheck{
     
       public static map<String,Boolean> checkNarrativeFields(Application3__c app,Id nofaId){
        //map<String,Boolean> booleanMap = new map<String,Boolean>();
        boolean check = true;
        map<String,Boolean> reqNarrativeFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofaNarratives = SObjectType.NOFA__c.FieldSets.Narratives.getFields();
        String query = 'SELECT ';
		
        for(Schema.FieldSetMember f : nofaNarratives) {
            System.debug('Field_Set Member'+f);
            query += f.getFieldPath() + ', ';

        }

        System.debug('Prashant_Nofa'+nofaNarratives);
        query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;
        
        List<Schema.FieldSetMember> appNarratives = SObjectType.Application3__c.FieldSets.Narratives.getFields();
        map<String,String> fieldLabelMapping = new map<String,String>();
        for(Schema.FieldSetMember af : appNarratives){
            fieldLabelMapping.put(af.getFieldPath(),af.getLabel());
        }
        map<String,String> fieldMapping = new map<String,String>();
    
        
        for(Schema.FieldSetMember nf : nofaNarratives) {
            if(nf.getFieldPath() == 'Strengthening_Communities__c'){
               fieldMapping.put(nf.getFieldPath(),'Strengthen_Communities__c');
            }
            else if(nf.getFieldPath() == 'Program_Design__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Design__c'); 
            }
            else if(nf.getFieldPath() == 'Program_Management__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Management__c'); 
            }
                           else{
                for(Schema.FieldSetMember af : appNarratives) {
                    String s = nf.getFieldPath();
                    Integer i = s.indexOf('_');
                    String shortForm = s.left(i);
                    System.debug('Fields_shortForm'+shortForm);
                    if(af.getFieldPath().contains(shortForm)){
                         System.debug('$$$$$$$appNarratives Fields'+af.getFieldPath());
                        fieldMapping.put(nf.getFieldPath(),af.getFieldPath());
                    }
                    
                }
            }
            
        }
        system.debug('fieldMap = '+fieldMapping);
        system.debug('app = '+app);
        NOFA__c nofa;
        try{
         	nofa = Database.query(query);              
        }
        catch(Exception e){
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Application is not linked to any Nofa'));
        }
        
        if(nofa!=null){        	
	       for(Schema.FieldSetMember f : nofaNarratives) {
	            if(nofa.get(f.getFieldPath()) == true){       
	                system.debug('app field value = '+app.get(fieldMapping.get(f.getFieldPath())));  
	                if(fieldMapping.get(f.getFieldPath())=='Amendment_Justification__c'){
	                	if(app.Type_of_Application__c == 'Amendment'){
	                		if(app.get(fieldMapping.get(f.getFieldPath())) == null){
	                    		check = false;
	                    		system.debug('f = '+f);
	                    		reqNarrativeFields.put(fieldLabelMapping.get(fieldMapping.get(f.getFieldPath())),true);
	                		}
	                	}
	                } 
	                else if(fieldMapping.get(f.getFieldPath())=='Continuation_Changes__c'){
	                	if(app.Type_of_Application__c == 'Continuation'){
	                		if(app.get(fieldMapping.get(f.getFieldPath())) == null){
	                    		check = false;
	                    		system.debug('f = '+f);
	                    		reqNarrativeFields.put(fieldLabelMapping.get(fieldMapping.get(f.getFieldPath())),true);
	                		}
	                	}
	                }                     
	                else{ 
	                	if(app.get(fieldMapping.get(f.getFieldPath())) == null){
		                    check = false;
		                    system.debug('f = '+f);
		                    reqNarrativeFields.put(fieldLabelMapping.get(fieldMapping.get(f.getFieldPath())),true);
	                    //booleanMap.put(fieldMapping.get(f.getFieldPath()),false);
	                	}     
	                }          
	                /*else
	                    check = true;*/
	               
	            }
	        }
        }
     //   reqNarrativeFields.put('Project website URL',False);
        system.debug('check = '+check);
        For(String s:reqNarrativeFields.keyset())
        {
          System.debug('Prashant_reqNarrativeFields'+s+'$$$$$'+reqNarrativeFields.get(s));
        }       // Added by me
        return reqNarrativeFields;
        
     } 
     
     public static map<String,Boolean> checkCPNarrativeFields(Application3__c app,Id nofaId){
        
        boolean check = true;
        map<String,Boolean> reqNarrativeFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofaNarratives = SObjectType.NOFA__c.FieldSets.CP_Narratives.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofaNarratives) {

            query += f.getFieldPath() + ', ';

        }

        query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;

        NOFA__c nofa = Database.query(query);    
        
        List<Schema.FieldSetMember> appNarratives = SObjectType.Application3__c.FieldSets.Narratives.getFields();
        map<String,String> fieldLabelMapping = new map<String,String>();
        for(Schema.FieldSetMember af : appNarratives){
            fieldLabelMapping.put(af.getFieldPath(),af.getLabel());
        }
        map<String,String> fieldMapping = new map<String,String>();
        
        for(Schema.FieldSetMember nf : nofaNarratives) {
             if(nf.getFieldPath() == 'Strengthening_Communities_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Strengthen_Communities__c');
            }
            else if(nf.getFieldPath() == 'Program_Design_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Design__c'); 
            }
            else if(nf.getFieldPath() == 'Program_Management_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Management__c'); 
            }
            else{
                for(Schema.FieldSetMember af : appNarratives) {
                    String s = nf.getFieldPath();
                    Integer i = s.indexOf('_');
                    String shortForm = s.left(i);
                    if(af.getFieldPath().contains(shortForm)){
                        fieldMapping.put(nf.getFieldPath(),af.getFieldPath());
                    }
                }
            }
        }    
        
        for(Schema.FieldSetMember f : nofaNarratives) {
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                if(app.get(fieldMapping.get(f.getFieldPath())) == null){
                    check = false;
                    reqNarrativeFields.put(fieldLabelMapping.get(fieldMapping.get(f.getFieldPath())),true);
                }               
                /*else
                    check = true;*/
            }
        }
        
       
        system.debug('check = '+check);
        return reqNarrativeFields;
        
     } 
     
     public static map<String,Boolean> checkCPFocusAreaFields(Application3__c app,Id nofaId){
        
        boolean check = true;
        map<String,Boolean> reqFocusFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofafocusFields = SObjectType.NOFA__c.FieldSets.CP_Focus_Areas.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofafocusFields) {

            query += f.getFieldPath() + ', ';

        }

        query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;

        NOFA__c nofa = Database.query(query);    
        
        List<Schema.FieldSetMember> appFocusFields = SObjectType.Application3__c.FieldSets.Concept_Paper_Focus_Areas_Objectives.getFields();
        map<String,String> fieldLabelMapping = new map<String,String>();
        for(Schema.FieldSetMember af : appFocusFields){
            fieldLabelMapping.put(af.getFieldPath(),af.getLabel());
        }
        map<String,String> fieldMapping = new map<String,String>();
        
        for(Schema.FieldSetMember nf : nofafocusFields) {
            if(nf.getFieldPath() == 'Environmental_Stewardship_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Environment_Stewardship_CP__c');
            }
            /*else if(nf.getFieldPath() == 'Program_Design_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Design__c'); 
            }
            else if(nf.getFieldPath() == 'Program_Management_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Management__c'); 
            }*/
            else{
                for(Schema.FieldSetMember af : appFocusFields) {
                    String s = nf.getFieldPath();
                    Integer i = s.indexOf('_');
                    String shortForm = s.left(i);
                    if(af.getFieldPath().contains(shortForm)){
                        fieldMapping.put(nf.getFieldPath(),af.getFieldPath());
                    }
                }
            }
        }    
        
        for(Schema.FieldSetMember f : nofafocusFields) {
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                if(app.get(fieldMapping.get(f.getFieldPath())) != null){
                    check = true;
                    reqFocusFields.put(fieldLabelMapping.get(fieldMapping.get(f.getFieldPath())),true);
                }               
                /*else
                    check = true;*/
            }
        }
        
       
        system.debug('check = '+check);
        return reqFocusFields;
        
     }
     
     public static map<String,Boolean> checkAppFocusAreaFields(Application3__c app,Id nofaId){
        
        boolean check = true;
        map<String,Boolean> reqFocusFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofafocusFields = SObjectType.NOFA__c.FieldSets.App_Focus_Areas.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofafocusFields) {

            query += f.getFieldPath() + ', ';

        }
		if(nofaId!=null){
        	query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;
		}

        NOFA__c nofa = Database.query(query);    
        
        List<Schema.FieldSetMember> appFocusFields = SObjectType.Application3__c.FieldSets.App_Focus_Areas.getFields();
        map<String,String> fieldLabelMapping = new map<String,String>();
        for(Schema.FieldSetMember af : appFocusFields){
            fieldLabelMapping.put(af.getFieldPath(),af.getLabel());
        }
        map<String,String> fieldMapping = new map<String,String>();
        
        for(Schema.FieldSetMember nf : nofafocusFields) {
             /*if(nf.getFieldPath() == 'Strengthening_Communities_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Strengthen_Communities__c');
            }
            else if(nf.getFieldPath() == 'Program_Design_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Design__c'); 
            }
            else if(nf.getFieldPath() == 'Program_Management_CP__c'){
               fieldMapping.put(nf.getFieldPath(),'Program_Management__c'); 
            }
            else{*/
                for(Schema.FieldSetMember af : appFocusFields) {
                    String s = nf.getFieldPath();
                    Integer i = s.indexOf('_');
                    String shortForm = s.left(i);
                    if(af.getFieldPath().contains(shortForm)){
                        fieldMapping.put(nf.getFieldPath(),af.getFieldPath());
                    }
                }
            //}
        }    
        
        for(Schema.FieldSetMember f : nofafocusFields) {
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                if(app.get(fieldMapping.get(f.getFieldPath())) != null){
                    check = true;
                    reqFocusFields.put(fieldLabelMapping.get(fieldMapping.get(f.getFieldPath())),true);
                }               
                /*else
                    check = true;*/
            }
        }
        
       
        system.debug('check = '+check);
        return reqFocusFields;
        
     }
     
     public static map<String,Boolean> appFocusAreaFieldsonNofa(Id nofaId){
        
        map<String,Boolean> reqFocusFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofafocusFields = SObjectType.NOFA__c.FieldSets.App_Focus_Areas.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofafocusFields) {

            query += f.getFieldPath() + ', ';

        }
		if(nofaId!=null){
        	query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;
		}

        NOFA__c nofa = Database.query(query);           
       
        
        for(Schema.FieldSetMember f : nofafocusFields) {
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                reqFocusFields.put(f.getFieldPath(),true);                
            }
        }       
       
       
        return reqFocusFields;
        
     }
     
     public static map<String,Boolean> cpFocusAreaFieldsonNofa(Id nofaId){
        
        map<String,Boolean> reqFocusFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofafocusFields = SObjectType.NOFA__c.FieldSets.CP_Focus_Areas.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofafocusFields) {

            query += f.getFieldPath() + ', ';

        }

        query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;

        NOFA__c nofa = Database.query(query);    
        
       
        for(Schema.FieldSetMember f : nofafocusFields) {            
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                reqFocusFields.put(f.getFieldPath(),true);                
            }
        }
        
       
        return reqFocusFields;
        
     }
     
     /* public static map<String,Boolean> appNarrativeFieldsonNofa(Id nofaId){
        
        map<String,Boolean> reqFocusFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofafocusFields = SObjectType.NOFA__c.FieldSets.Narratives.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofafocusFields) {

            query += f.getFieldPath() + ', ';

        }

        query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;

        NOFA__c nofa = Database.query(query);    
        
       
        for(Schema.FieldSetMember f : nofafocusFields) {            
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                reqFocusFields.put(f.getFieldPath(),true);                
            }
        }
        
       
        return reqFocusFields;
        
     }
     
     public static map<String,Boolean> cpNarrativeFieldsonNofa(Id nofaId){
        
        map<String,Boolean> reqFocusFields = new map<String,Boolean>();
        String t1 = '\'';
        String t2 = '\'';
        List<Schema.FieldSetMember> nofafocusFields = SObjectType.NOFA__c.FieldSets.CP_Narratives.getFields();
        String query = 'SELECT ';

        for(Schema.FieldSetMember f : nofafocusFields) {

            query += f.getFieldPath() + ', ';

        }

        query += 'Id, Name FROM NOFA__c where id = '+t1+nofaId+t2;

        NOFA__c nofa = Database.query(query);    
        
       
        for(Schema.FieldSetMember f : nofafocusFields) {            
            if(nofa.get(f.getFieldPath()) == true){
                system.debug('nofa fieldName = '+f.getFieldPath());
                reqFocusFields.put(f.getFieldPath(),true);                
            }
        }
        
       
        return reqFocusFields;
        
     } */
     
     public static void attachOrgDocs(Application3__c app,String OrgDocTypes){
        list<Attachment__c> attachments = new list<Attachment__c>([Select a.View__c, a.Type__c, a.Name, a.Id, a.Description__c, a.Application__c From Attachment__c a where Application__c = :app.Id]);
        if(attachments.size()>0){
            for(Attachment__c a: attachments){
                if(OrgDocTypes.contains(a.Type__c)){
                    system.debug('Organization == '+app.Organization__c);
                    a.Account__c = app.Organization__c;
                }
            }
            system.debug('attachments = '+attachments);
            update attachments;
        }
     } 
	 public Static Void  Validate(Application3__c apps){
 		List<Application3__c> app1=new List<Application3__c>([select id,Have_funding_history_with_any_CNCS_org__c from Application3__c where id=:apps.id]);
		for(Application3__c ap:app1){
			if(ap.Have_funding_history_with_any_CNCS_org__c  == null || ap.Have_funding_history_with_any_CNCS_org__c=='') 
			{
  				ap.Have_funding_history_with_any_CNCS_org__c.addError('');
  //return false;
			}
		}
	}
}