src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_Signed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Application Signed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assurances_Clicked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assurances Clicked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Authorized_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for Notification of Intent to Apply section of the Application.</description>
        <label>Authorized Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Certifications_Clicked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certifications Clicked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommended_Award_Amount__c</fullName>
        <label>Recommended Award Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Budget_Application_Limit__c</fullName>
        <label>Budget Application Limit</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Slot__c.object
<CustomObject>
    <fields>
        <fullName>Budget_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Application</label>
        <referenceTo>cb3__Budget__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots_BA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Slot</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Slot Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BudgetApplicationTriggerHandler.cls
public class BudgetApplicationTriggerHandler{


    public BudgetApplicationTriggerHandler(){
    
    }
    
    //invoked before insert,update of BudgetApplication(cb3__Budget__c) in restricting budgetapplications more than than limit configured 
    public void restrictBdgAppsWithInLmts(List<cb3__Budget__c> p_OldLstBdgApps,List<cb3__Budget__c> p_NewLstBdgApps,
                                Map<Id,cb3__Budget__c> p_OldMapBdgApps,Map<Id,cb3__Budget__c> p_NewMapBdgApps){

        String tempAppId;
        List<String> lstAppId=new List<String>();
        Map<String,String> mpBdgAppIdToAppId=new Map<String,String>();
        Map<String,String> mpAppIdToBdgAppId=new Map<String,String>();
        Set<String> stAppId =new Set<String>();
        String errAppId='';
    
        String errMsg='Cannot create Budget Applications more than the limit configured against respective NOFA';
        Boolean flag=false;
        try{
    
            for (cb3__Budget__c  objTemp : p_NewLstBdgApps) {
                            tempAppId =objTemp.Parent__c; 
                            System.debug('***tempAppId ***'+tempAppId );
                            System.debug('***tempAppId ***'+objTemp);
                            if(tempAppId!=null){ 
                                 lstAppId.add(tempAppId); 
                                 stAppId.add(tempAppId );
                                 mpBdgAppIdToAppId.put(objTemp.id,objTemp.parent__c);
                            }    
            }
            Integer lmt=0;
            System.debug('stAppId'+stAppId);
            List<Application3__c> lstAppForNofaLimit_BdgApp= [SELECT id,name,NOFA_RFP__r.Budget_Application_Limit__c,
                                                                     (SELECT id,name from Budget_Applications__r) 
                                                              FROM application3__c 
                                                              WHERE id in :stAppId];  
            for(Application3__c objApp:lstAppForNofaLimit_BdgApp) {
                if(objApp.NOFA_RFP__r!=null && objApp.NOFA_RFP__r.Budget_Application_Limit__c!=null){
                   lmt=Integer.valueof(objApp.NOFA_RFP__r.Budget_Application_Limit__c);
                }    
                System.debug('objApp.NOFA_RFP__r.Budget_Application_Limit__c'+objApp.NOFA_RFP__r.Budget_Application_Limit__c); 
                if(objApp.Budget_Applications__r!=null){
                    System.debug('objApp.Budget_Applications__r.size()'+objApp.Budget_Applications__r.size());  
                }
    
                if(objApp.Budget_Applications__r!=null && lmt!=null 
                        && ( objApp.Budget_Applications__r.size() >= lmt && lmt !=0)){
                    System.debug('condition error');  
                    errAppId=objApp.id;
                    flag=true;
                    break;
                    //Trigger.addError('Cannot create Budget Applications more than the limit configured against respective NOFA');        
                }
            }
            
            for (cb3__Budget__c  objTemp : p_NewLstBdgApps) {
                  if(flag==true && errAppId.equals(objTemp.Parent__c)){
                     System.debug('error'); 
                     objTemp.addError(errMsg);
                  }
                  break;
            }  
        }
        catch(Exception exc){
          System.debug('***Exception in method-restrictBdgAppsWithInLmts **'+exc.getMessage());
        }            
    }
    
    //method invoked after insert,update of BudgetApplication(cb3__Budget__c) records to update application3__c fields
    public void updateApp_Attributes(List<cb3__Budget__c> p_OldLstBdgApps,
                                    List<cb3__Budget__c> p_NewLstBdgApps,
                                    Map<Id,cb3__Budget__c> p_OldMapBdgApps,
                                    Map<Id,cb3__Budget__c> p_NewMapBdgApps ){

    try{
    
        set<Id> appIds = new set<Id>();
        for(cb3__Budget__c itrBdgApp: p_NewLstBdgApps){
            if(itrBdgApp.Parent__c != null){
                appIds.add(itrBdgApp.Parent__c);   
            }
        }
        Id appRT = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        list<Application3__c> apps = [SELECT Id,Name,RecordTypeId,Application_Signed__c,Authorized_Representative__c,
                                             Certifications_Clicked__c,Assurances_Clicked__c,Grantee_Status__c  
                                      FROM Application3__c 
                                      WHERE id in :appIds and RecordTypeId = :appRT];
        
        list<Application3__c> appsToUpdate = new list<Application3__c>();                    
            if(apps!=null && apps.size()>0){ 
                for(Application3__c itrApp: apps){
                    if(itrApp.Application_Signed__c){
                        itrApp.Application_Signed__c = false;
                        itrApp.Authorized_Representative__c = null;
                        itrApp.Grantee_Status__c = 'In Progress';
                        itrApp.Certifications_Clicked__c = false;
                        itrApp.Assurances_Clicked__c = false;
                        appsToUpdate.add(itrApp);
                    }   
                }
                if(appsToUpdate.size()>0){
                	update appsToUpdate;
                }
            }                   
        }
        catch(Exception exc){
            System.debug('***Exception in method -updateApp_certainFields-***'+exc.getMessage());
    
        }
    }
    
    //method invoked after insert,update of BudgetApplication(cb3__Budget__c) records to update application3__c 
    //field (Recommended_Award_Amount__c ) with the field(cb3__Q1__c) value of BudgetApplication
    public void assign_RecommendedAwardAmtToAppFromBdgApp(List<cb3__Budget__c> p_OldLstBdgApps,
                                                                List<cb3__Budget__c> p_NewLstBdgApps,
                                                                Map<Id,cb3__Budget__c> p_OldMapBdgApps,
                                                                Map<Id,cb3__Budget__c> p_NewMapBdgApps){
       Set<String> setAppId=new Set<String>();
       Map<String,String> mapBdgAppIdToAppId =new Map<String,String>();
       try{
           for(cb3__Budget__c itrBdgApp : p_NewLstBdgApps){
               if(itrBdgApp.cb3__BudgetForCurrentApplicationYear__c!=null && itrBdgApp.cb3__BudgetForCurrentApplicationYear__c==true){
                   setAppId.add(itrBdgApp.Parent__c);
                   mapBdgAppIdToAppId.put(itrBdgApp.id,itrBdgApp.Parent__c);
               }
           }
       
           System.debug('***setAppId***'+setAppId+ '***mapBdgAppIdToAppId***'+mapBdgAppIdToAppId);
           Id appRT = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
           Map<Id,Application3__c> mapApp=new Map<Id,Application3__c>([SELECT id,name,Recommended_Award_Amount__c 
                                                                       FROM Application3__c 
                                                                       WHERE id in :setAppId and RecordTypeId = :appRT]);
           List<Application3__c> lstUpdateApp=new List<Application3__c>();
           Application3__c tempApp=new Application3__c();
       
           for(cb3__Budget__c itrBdgApp : p_NewLstBdgApps){
               if(itrBdgApp.cb3__BudgetForCurrentApplicationYear__c!=null && itrBdgApp.cb3__BudgetForCurrentApplicationYear__c==true){
                    if(mapApp!=null && mapApp.containskey(itrBdgApp.Parent__c)){
                        tempApp=new Application3__c();
                        tempApp= mapApp.get(itrBdgApp.Parent__c);
                        tempApp.Recommended_Award_Amount__c =itrBdgApp.cb3__Q1__c;
                        mapApp.put(itrBdgApp.Parent__c,tempApp);
                    }
               }     
           }
           
           if(mapApp!=null && mapApp.size() > 0 ){
                   lstUpdateApp.addAll(mapApp.values());
                   if(lstUpdateApp!=null && lstUpdateApp.size()>0){
                       Update lstUpdateApp;
                   }
           }
       }
       catch(Exception exc){
          System.debug('***Exception in method-assign_RecommendedAwardAmtToAppFromBdgApp()-*** '+exc.getMessage());
       }
    }
    
    public void deleteSlotsForDeletedBdgApps(List<cb3__Budget__c> p_OldLstBdgApps){
        List<Slot__c> lstSlotsToBeDeleted = new List<Slot__c>();
        Set<String> setBdgAppId=new Set<String>();
        try{
             for(cb3__Budget__c itrBdgApp : p_OldLstBdgApps){
                 setBdgAppId.add(itrBdgApp.id);
             }
             
             if(setBdgAppId!=null && setBdgAppId.size()>0){
                lstSlotsToBeDeleted =[SELECT id,Budget_Application__c  
                                      From Slot__c 
                                      WHERE Budget_Application__c in :setBdgAppId];
                if(    lstSlotsToBeDeleted !=null && lstSlotsToBeDeleted.size() > 0) {
                  delete lstSlotsToBeDeleted;
                }                  
             
             }
       
        }
        
        catch(QueryException qryExc){
            System.debug('***QueryException in method-deleteSlotsForDeletedBdgApps()-*** '+qryExc.getMessage());
        }
        catch(DmlException dmlExc){
            System.debug('***DMLException in method-deleteSlotsForDeletedBdgApps()-*** '+dmlExc.getMessage());
        }
        catch(NoDataFoundException noDataFoundExc){
            System.debug('***No data found exception in method-deleteSlotsForDeletedBdgApps()-*** '+noDataFoundExc.getMessage());
        }
        catch(Exception exc){
          System.debug('***Exception in method-deleteSlotsForDeletedBdgApps()-*** '+exc.getMessage());
       }
    
    
    }

}