src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Application_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application ID related to Award.</description>
        <label>Application ID</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Source__c.object
<CustomObject>
    <description>Funding Source</description>
    <fields>
        <fullName>Fiscal_Yr_Basis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Fiscal Year and Fund Code</label>
        <referenceTo>Fiscal_Yr_Basis__c</referenceTo>
        <relationshipLabel>Funding Source</relationshipLabel>
        <relationshipName>Funding_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funds_Remaining__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Grant_location_number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Location Code</label>
        <referenceTo>Grant_location_number__c</referenceTo>
        <relationshipLabel>Funding Source</relationshipLabel>
        <relationshipName>Funding_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Funding Source (NOFO/RFP)</relationshipLabel>
        <relationshipName>Funding_Source1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object_code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Object Class Code</label>
        <referenceTo>Object_code__c</referenceTo>
        <relationshipLabel>Funding Source</relationshipLabel>
        <relationshipName>Funding_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Funding Source ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Source</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FundSourceLookUpCntrl.cls
Public class FundSourceLookUpCntrl{

    public Award__c objAward{get;set;} 
    public List<Funding_Source__c> lstFundingSource{get;set;}
    
    public PageReference retrieveFundSourceRecs(){
        String strAwardId=ApexPages.currentPage().getParameters().get('idfield');
        System.debug('***strAwardId***'+strAwardId);
        if(strAwardId!=null){
            objAward= [Select id,Application_ID__r.NOFA_RFP__c from Award__c where id=:strAwardId];
            System.debug('objAward'+objAward);
            if(objAward!=null && objAward.Application_ID__r.NOFA_RFP__c!=null){
                lstFundingSource=[Select id,name,Fiscal_Yr_Basis__r.name,Object_code__r.name,Grant_location_number__c,Funds_Remaining__c from Funding_Source__c where NOFA__c=:objAward.Application_ID__r.NOFA_RFP__c];
                System.debug('lstFundingSource'+lstFundingSource);
            }
        }
        return null;
    }
 
}