src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <description>Populates the Master Award name from the Master Award related list.</description>
        <label>Master Award</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CNCS_Corporate_Program__c.object
<CustomObject>
    <fields>
        <fullName>Short_Code__c</fullName>
        <label>Short Code</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CNCS Corporate Structure</label>
    <nameField>
        <label>CNCS Corporate Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNCS Corporate Structure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Custom_Auto_Number__c</fullName>
        <label>Custom Auto Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>CNCS_Corporate_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Corporate Program Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CNCS_Corporate_Program__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Corporate_Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CNCS_Corporate_Program__c</referenceTo>
        <relationshipLabel>NOFOs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Yr__c</fullName>
        <label>NOFO Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>CNCS_Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CNCS Corporate Program</label>
        <referenceTo>CNCS_Corporate_Program__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Award</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>contains</operation>
                <value>Continuation, New &amp; Continuation</value>
            </filterItems>
            <filterItems>
                <field>$Source.CNCS_Corporate_Program__c</field>
                <operation>equals</operation>
                <valueField>NOFA__c.CNCS_Corporate_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>equals</operation>
                <value>New, New &amp; Continuation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MasterAwardHelperForCustomAutoNumber.cls
Public class MasterAwardHelperForCustomAutoNumber{
    
    public static void manipulateAutoNumber(List<Master_Award__c> lstNewMasterAwardRecs){
        List<Master_Award__c> lstMasterAward =[SELECT id,name,Custom_Auto_Number__c,Prime_Application__r.NOFO_RFP__r.Fiscal_Yr__c,
                                                         Prime_Application__r.NOFO_RFP__r.CNCS_Corporate_Program__r.Short_Code__c,
                                                         Application__r.NOFA_RFP__r.Fiscal_Yr__c,
                                                         Application__r.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c,Application__r.Project__r.State__c 
                                                FROM   Master_Award__c];
                                                
         set<string> setCustomAutoNumber = new set<string>();
         for(Master_Award__c itrMasterAward :lstMasterAward ){
               setCustomAutoNumber.add(itrMasterAward.Custom_Auto_Number__c);
         }  
         String strConcatedValue='';                                     
         Set<Id> appIds=new Set<Id>();
         for(Master_Award__c itrMasterAward: lstNewMasterAwardRecs){
                appIds.add(itrMasterAward.Application__c);
         }
         System.debug('**appIds***'+appIds);
         List<Application3__c> lstApps=[SELECT id,name,NOFA_RFP__r.Fiscal_Yr__c,NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c,Project__r.State__c,Sub_App_Auto_Number__c 
                                        FROM Application3__c 
                                        WHERE id in :appIds];
         System.debug('**lstApps***'+lstApps);
         
         MAP<ID,Application3__c> mpApps;
         if(lstApps!=null && lstApps.size()>0){                             
            mpApps= new MAP<id,Application3__c>([SELECT id,name,NOFA_RFP__r.Fiscal_Yr__c,NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c,Project__r.State__c,Sub_App_Auto_Number__c
                                                 FROM Application3__c 
                                                 WHERE id in :appIds ]);
         }
         System.debug('**mpApps***'+mpApps ); 
         Application3__c objApplication=new Application3__c();
         String strFiscalYr='';
         String strYearInTwoDigits='';
         String strCustomAutoNumber='';  
         
         MAP<String,Integer> mapCodevalue=new Map<String,Integer>();
       //  mapCodevalue= processValueForCriteria(true);
         System.debug('***mapCodevalue***'+mapCodevalue);
         String strMapValue='';
         
         for(Master_Award__c itrMasterAward: lstNewMasterAwardRecs){
                   System.debug('**itrMasterAward.Application__c***'+itrMasterAward.Application__c);  
                   if(itrMasterAward.Application__c!=null){
                       objApplication =(Application3__c)(mpApps.get(itrMasterAward.Application__c));
                      /// System.debug('***objApplication***'+objApplication);
                      /// System.debug('***objApplication.NOFA_RFP__r.Fiscal_Yr__c***'+objApplication.NOFA_RFP__r.Fiscal_Yr__c);
                       strConcatedValue='';
                       strFiscalYr = objApplication.NOFA_RFP__r.Fiscal_Yr__c;
                       strYearInTwoDigits = (strFiscalYr !=null && strFiscalYr .length()>0)?strFiscalYr.right(2):'';
                       strConcatedValue=strYearInTwoDigits +objApplication.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c+'H'+objApplication.Project__r.State__c;
                      /// System.debug('***strConcatedValue***'+strConcatedValue);
                      
                       if(setCustomAutoNumber==null){
                           strCustomAutoNumber='001';
                       }
                       else if(setCustomAutoNumber!=null && setCustomAutoNumber.size()>0 && !setCustomAutoNumber.contains(strConcatedValue)){
                           strCustomAutoNumber='001';
                       }
                       else if (mapCodevalue!=null && mapCodevalue.size() > 0 ){
                                if(mapCodevalue.containsKey(strConcatedValue)){
                                    Integer temp_local=mapCodevalue.get(strConcatedValue); 
                                   /// System.debug('***temp_local***'+temp_local); 
                                    temp_local++;
                                    if(temp_local >=0 && temp_local<=9){
                                             strCustomAutoNumber='00'+temp_local;
                                    }else if(temp_local >=10 && temp_local<=99){
                                            strCustomAutoNumber='0'+temp_local;
                                    }else{
                                        strCustomAutoNumber=String.valueOf(temp_local);
                                    }
                                    
                                }
                       }
                       System.debug('***strCustomAutoNumber***'+strCustomAutoNumber);
                   }
         }                                        
    
    }
    
    public static MAP<String,Integer> processAggregateDataForAppMasterAwardRecType(Boolean flagGrantsOffice,String strAppMasterAwardRecTypeId){
         
         AggregateResult[] groupedResults;
    
         if(flagGrantsOffice){
                 groupedResults =[SELECT count(Custom_Auto_Number__c),Application__r.NOFA_RFP__r.Fiscal_Yr__c fy,
                                                   Application__r.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c sc,
                                                   Application__r.Project__r.State__c  st
                                  FROM   Master_Award__c 
                                  WHERE  Application__r.NOFA_RFP__r.Issuing_Officer__c='HQ(Office of Grants Management)'
                                         and recordtypeid= :strAppMasterAwardRecTypeId
                                  GROUP BY Application__r.NOFA_RFP__r.Fiscal_Yr__c,
                                           Application__r.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c,
                                           Application__r.Project__r.State__c 
                                  ];
           }else{
              /* groupedResults =[SELECT count(Custom_Auto_Number__c),Application__r.NOFA_RFP__r.Fiscal_Yr__c fy,
                                                   Application__r.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c sc,
                                                   Application__r.Project__r.State__c  st,
                                                   Dummy_State_CLR_Code__c clrCode*/
                groupedResults =[SELECT count(Custom_Auto_Number__c),Application__r.NOFA_RFP__r.Fiscal_Yr__c fy,
                                                   Application__r.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c sc,
                                                   Application__r.Project__r.State__c  st,
                                                   Application__r.Project__r.State_CLR_Code__c clrCode  
                                                  //Dummy_State_CLR_Code__c clrCode                              
                                FROM   Master_Award__c 
                                WHERE  Application__r.NOFA_RFP__r.Issuing_Officer__c!='HQ(Office of Grants Management)'
                                        and recordtypeid= :strAppMasterAwardRecTypeId
                                GROUP BY Application__r.NOFA_RFP__r.Fiscal_Yr__c,
                                         Application__r.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c,
                                        // Dummy_State_CLR_Code__c,
                                        Application__r.Project__r.State_CLR_Code__c,
                                         Application__r.Project__r.State__c
                                  ];
           
           }                       
                                            
                                            
         MAP<String,Integer> mapCodevalue=new Map<String,Integer>();
         String strFiscalYr='' ;
         String  strYearInTwoDigits='';                                   
                                            
         for (AggregateResult ar : groupedResults)  {
          ///  System.debug('count' + ar.get('expr0'));
            strFiscalYr =((String)ar.get('fy'));
            strYearInTwoDigits = (strFiscalYr !=null && strFiscalYr .length()>0)?strFiscalYr.right(2):'';
          ///  System.debug('Fiscal Yr' + ar.get('fy'));
          ///  System.debug('Short Code' + ar.get('sc'));
         ///   System.debug('State' + ar.get('st'));
            //String code=(String)ar.get('expr1');
           // mapCodevalue.put(((String)ar.get('fy'))+((String)ar.get('sc'))+'H'+((String)ar.get('st')),((Integer)ar.get('expr0')));
           if(flagGrantsOffice){
                 mapCodevalue.put(strYearInTwoDigits +((String)ar.get('sc'))+'H'+((String)ar.get('st')),((Integer)ar.get('expr0')));
           }else{
                mapCodevalue.put(strYearInTwoDigits +((String)ar.get('sc'))+((String)ar.get('clrCode'))+((String)ar.get('st')),((Integer)ar.get('expr0')));
           }      

         }
         return mapCodevalue;
    }
    
     public static MAP<String,Integer> processAggregateDataForSubAppMasterAwardRecType(Boolean flagGrantsOffice, String strSubAppMasterAwardRecTypeId){
         
         AggregateResult[] groupedResults;
    
         if(flagGrantsOffice){
                 groupedResults =[SELECT count(Custom_Auto_Number__c),Application__r.NOFA_RFP__r.Fiscal_Yr__c fy,
                                                                      Application__r.Project__r.State__c  st
                                  FROM   Master_Award__c 
                                  WHERE  Application__r.NOFA_RFP__r.Issuing_Officer__c='HQ(Office of Grants Management)' 
                                         and recordtypeid= :strSubAppMasterAwardRecTypeId
                                  GROUP BY Application__r.NOFA_RFP__r.Fiscal_Yr__c,
                                           Application__r.Project__r.State__c
                                           
                                  ];
           }else{
               groupedResults =[SELECT count(Custom_Auto_Number__c),Application__r.NOFA_RFP__r.Fiscal_Yr__c fy,
                                                   Application__r.Project__r.State__c  st,
                                                  // Dummy_State_CLR_Code__c clrCode
                                                  Application__r.Project__r.State_CLR_Code__c clrCode 
                                FROM   Master_Award__c 
                                WHERE  Application__r.NOFA_RFP__r.Issuing_Officer__c!='HQ(Office of Grants Management)'
                                       and recordtypeid= :strSubAppMasterAwardRecTypeId
                                GROUP BY Application__r.NOFA_RFP__r.Fiscal_Yr__c,
                                         Application__r.Project__r.State__c,
                                        // Dummy_State_CLR_Code__c 
                                         Application__r.Project__r.State_CLR_Code__c
                                         
                                ];
           }                       
                                            
                                            
         MAP<String,Integer> mapCodevalue=new Map<String,Integer>();
         String strFiscalYr='' ;
         String  strYearInTwoDigits='';                                   
                                            
         for (AggregateResult ar : groupedResults)  {
           /// System.debug('count' + ar.get('expr0'));
            strFiscalYr =((String)ar.get('fy'));
            strYearInTwoDigits = (strFiscalYr !=null && strFiscalYr .length()>0)?strFiscalYr.right(2):'';
          ///  System.debug('Fiscal Yr' + ar.get('fy'));
          //  System.debug('Short Code' + ar.get('sc'));
            ///System.debug('State' + ar.get('st'));
            //String code=(String)ar.get('expr1');
           // mapCodevalue.put(((String)ar.get('fy'))+((String)ar.get('sc'))+'H'+((String)ar.get('st')),((Integer)ar.get('expr0')));
           if(flagGrantsOffice){
                 mapCodevalue.put(strYearInTwoDigits +'AC'+'H'+((String)ar.get('st')),((Integer)ar.get('expr0')));
           }else{
                mapCodevalue.put(strYearInTwoDigits +'AC'+((String)ar.get('clrCode'))+((String)ar.get('st')),((Integer)ar.get('expr0')));
           }      

         }
         return mapCodevalue;
    }
    
    public static MAP<String,Integer> processAggregateDataForPrimeMasterAwardRecType(Boolean flagGrantsOffice, String strPrimeMasterAwardRecTypeId){
         
         AggregateResult[] groupedResults;
    
         if(flagGrantsOffice){
                 groupedResults =[SELECT count(Custom_Auto_Number__c),Prime_Application__r.NOFO_RFP__r.Fiscal_Yr__c  fy,
                                                                      Prime_Application__r.Project_Name__r.State__c  st
                                  FROM   Master_Award__c 
                                  WHERE  Prime_Application__r.NOFO_RFP__r.Issuing_Officer__c='HQ(Office of Grants Management)' 
                                         and recordtypeid= :strPrimeMasterAwardRecTypeId
                                  GROUP BY Prime_Application__r.NOFO_RFP__r.Fiscal_Yr__c,
                                           Prime_Application__r.Project_Name__r.State__c
                                           
                                  ];
           }else{
               groupedResults =[SELECT count(Custom_Auto_Number__c),Prime_Application__r.NOFO_RFP__r.Fiscal_Yr__c  fy,
                                                   Prime_Application__r.Project_Name__r.State__c  st,
                                                  // Dummy_State_CLR_Code__c clrCode
                                                   Application__r.Project__r.State_CLR_Code__c clrCode
                                FROM   Master_Award__c 
                                WHERE  Prime_Application__r.NOFO_RFP__r.Issuing_Officer__c!='HQ(Office of Grants Management)'
                                       and recordtypeid= :strPrimeMasterAwardRecTypeId
                                GROUP BY Prime_Application__r.NOFO_RFP__r.Fiscal_Yr__c ,
                                        // Dummy_State_CLR_Code__c,
                                         Application__r.Project__r.State_CLR_Code__c,
                                         Prime_Application__r.Project_Name__r.State__c
                               ];
           }                       
                                            
                                            
         MAP<String,Integer> mapCodevalue=new Map<String,Integer>();
         String strFiscalYr='' ;
         String  strYearInTwoDigits='';                                   
                                            
         for (AggregateResult ar : groupedResults)  {
           /// System.debug('count' + ar.get('expr0'));
            strFiscalYr =((String)ar.get('fy'));
            strYearInTwoDigits = (strFiscalYr !=null && strFiscalYr .length()>0)?strFiscalYr.right(2):'';
          ///  System.debug('Fiscal Yr' + ar.get('fy'));
            //System.debug('Short Code' + ar.get('sc'));
          ///  System.debug('State' + ar.get('st'));
            //String code=(String)ar.get('expr1');
           // mapCodevalue.put(((String)ar.get('fy'))+((String)ar.get('sc'))+'H'+((String)ar.get('st')),((Integer)ar.get('expr0')));
           if(flagGrantsOffice){
                 mapCodevalue.put(strYearInTwoDigits +'AC'+'H'+((String)ar.get('st')),((Integer)ar.get('expr0')));
           }else{
                mapCodevalue.put(strYearInTwoDigits +'AC'+((String)ar.get('clrCode'))+((String)ar.get('st')),((Integer)ar.get('expr0')));
           }      

         }
         return mapCodevalue;
    }
    
    public static String processForAppAndSubAppMasterAwardRecType(Master_Award__c  itrMasterAward,Application3__c objApplication,Prime_Application__c objPrime_Application,
                                                                            MAP<String,Integer> mapCodevalue,String strAppMasterAwardRecTypeId,
                                                                            String strSubAppMasterAwardRecTypeId,String  strPrimeMasterAwardRecTypeId,
                                                                            Boolean flagHQOfficeOfGrantsManagement){
            String strConcatedValue='';
            String strFiscalYr ='';
            String strYearInTwoDigits ='';
            String strCustomAutoNumber='';
          ///  System.debug('**itrMasterAward.Application__c***'+itrMasterAward.Application__c);  
            //if(itrMasterAward.Application__c!=null){
               //objApplication =(Application3__c)(mpApps.get(itrMasterAward.Application__c));
           ///    System.debug('***objApplication***'+objApplication);
          ///     System.debug('***objApplication.NOFA_RFP__r.Fiscal_Yr__c***'+objApplication.NOFA_RFP__r.Fiscal_Yr__c);
               strConcatedValue='';
               strFiscalYr = objApplication.NOFA_RFP__r.Fiscal_Yr__c;
               strYearInTwoDigits = (strFiscalYr !=null && strFiscalYr.length()>0)?strFiscalYr.right(2):'';
               String currRecordTypeId=itrMasterAward.recordtypeid;
          ///     System.debug('**currRecordTypeId***'+currRecordTypeId);  
               
               if(currRecordTypeId.equals(strAppMasterAwardRecTypeId)){
                   if(flagHQOfficeOfGrantsManagement){
                       strConcatedValue=strYearInTwoDigits +objApplication.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c+'H'+objApplication.Project__r.State__c;               
                   }
                   else{
                       //strConcatedValue=strYearInTwoDigits +objApplication.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c+itrMasterAward.Dummy_State_CLR_Code__c+objApplication.Project__r.State__c;
                       strConcatedValue=strYearInTwoDigits +objApplication.NOFA_RFP__r.CNCS_Corporate_Program__r.Short_Code__c+objApplication.Project__r.State_CLR_Code__c+objApplication.Project__r.State__c;
                   }
               }
               else if(currRecordTypeId.equals(strSubAppMasterAwardRecTypeId)){
                   if(flagHQOfficeOfGrantsManagement){
                       strConcatedValue=strYearInTwoDigits +'AC'+'H'+objApplication.Project__r.State__c;               
                   }
                   else{
                       //strConcatedValue=strYearInTwoDigits +'AC'+itrMasterAward.Dummy_State_CLR_Code__c+objApplication.Project__r.State__c;
                       strConcatedValue=strYearInTwoDigits +'AC'+objApplication.Project__r.State_CLR_Code__c+objApplication.Project__r.State__c;
                   }
               
               }
               else if(currRecordTypeId.equals(strPrimeMasterAwardRecTypeId)){
                   if(flagHQOfficeOfGrantsManagement){
                       strConcatedValue=strYearInTwoDigits +'AC'+'H'+objPrime_Application.Project_Name__r.State__c;               
                   }
                   else{
                       //strConcatedValue=strYearInTwoDigits +'AC'+itrMasterAward.Dummy_State_CLR_Code__c+objPrime_Application.Project_Name__r.State__c;
                       strConcatedValue=strYearInTwoDigits +'AC'+objApplication.Project__r.State_CLR_Code__c+objPrime_Application.Project_Name__r.State__c;
                   }
               
               }
               System.debug('***strConcatedValue***'+strConcatedValue);
              
               if (mapCodevalue==null){
                   /// System.debug('***mapCodevalue==null***');
                    strCustomAutoNumber='001';
               }
               else if(mapCodevalue!=null && mapCodevalue.size() >0 && !mapCodevalue.containsKey(strConcatedValue)){
                ///   System.debug('***mapCodevalue!=null && mapCodevalue.size() >0 && !mapCodevalue.containsKey(strConcatedValue)***');
                   strCustomAutoNumber='001';
               }
               else if (mapCodevalue!=null && mapCodevalue.size() > 0  && mapCodevalue.containsKey(strConcatedValue)){
                           Integer temp_local=mapCodevalue.get(strConcatedValue); 
                       ///   System.debug('***temp_local***'+temp_local); 
                      ///     System.debug('***mapCodevalue!=null && mapCodevalue.size() > 0  && mapCodevalue.containsKey(strConcatedValue)***');
                           temp_local++;
                           if(temp_local >=0 && temp_local<=9){
                                    strCustomAutoNumber='00'+temp_local;
                           }else if(temp_local >=10 && temp_local<=99){
                                   strCustomAutoNumber='0'+temp_local;
                           }else{
                               strCustomAutoNumber=String.valueOf(temp_local);
                           }
                       
               }
               System.debug('***strCustomAutoNumber***'+strCustomAutoNumber);
               itrMasterAward.Custom_Auto_Number__c=strCustomAutoNumber;
           //}
         return strCustomAutoNumber;
    
    }
    
    public class FiscalYearShortCodeState{
       String fYSCSTValue;
       String maxValue;
       
       public FiscalYearShortCodeState(){
           fYSCSTValue='';
           maxValue='';
       }
    }
    
    
    

}