src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <description>Populates the Master Award name from the Master Award related list.</description>
        <label>Master Award</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA_RFP__r.NOFA_name__c</formula>
        <label>NOFO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Proposed_Start_Date__c</fullName>
        <description>Removed the default value {TODAY()}.
Per bug # 263. 10.24.16</description>
        <label>Proposed Start Date</label>
        <type>Date</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Amendment__c</fullName>
        <description>Amendment # for Amendment awards.</description>
        <label>Amendment #</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Application_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application ID related to Award.</description>
        <label>Application ID</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <label>Grant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting GO Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PO Certification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Organization e-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO CSHR Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO De-Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO De-Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Arrival</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <description>US # 2415</description>
        <label>Federal Award Identification Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Award Identification Number</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award Id</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Reporting</relationshipLabel>
        <relationshipName>Award_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expenditure_Comments__c</fullName>
        <label>Expenditure Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Fed_Share_of_expenditures_This_Period__c</fullName>
        <label>Fed Share of expenditures-This Period</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Federal_Share_of_expenditures__c</fullName>
        <label>Federal Share of expenditures-Previous</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grant__c</fullName>
        <formula>Award__r.Grant__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAIN(FederalAward Identification Number)</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_Comments__c</fullName>
        <label>Match Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Recipient_share_of_exp_Cumulative__c</fullName>
        <label>Share of Expenditures – Cumulative</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Fed_Funds_authorized_Cumulative__c</fullName>
        <label>Total Fed Funds authorized-Cumulative</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Federal_Funds_authorized__c</fullName>
        <label>Total Federal Funds authorized-Previous</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Recipient_share_required__c</fullName>
        <label>Total Share Required – Previous</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Award Reporting</label>
    <nameField>
        <displayFormat>Award Reporting-{000}</displayFormat>
        <label>Award Reporting Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Submitted_date__c</fullName>
        <label>Submitted date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Commitment__c</fullName>
        <description>Value to be populated from Momentum.</description>
        <label>Commitment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Obligation__c</fullName>
        <description>Value to be populated from Momentum.</description>
        <label>Obligation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Award</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AwardReportingHelperTest.cls
@isTest(seealldata=true)
public class AwardReportingHelperTest
{
    public static testmethod void method1()
    {
        Application3__c app = UtilityClass.createApplication();
        app.Proposed_Start_Date__c = Date.Today();
        insert app;
        
        Master_Award__c MasterAward = new Master_Award__c();
        MasterAward.Application__c = app.Id;
        MasterAward.Name = 'test34';
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        insert MasterAward;
       
        Award__c Award = new Award__c();
        Award.Application_ID__c = app.Id;
        Award.Master_Award__c = MasterAward.Id;
        Award.NOFA_Name__c = app.NOFA_RFP__c;       
        Award.Name = 'Test Award';
        Award.Organization__c = app.Organization__c;
        Award.Grant_Status__c = 'Awaiting PO Certification';
        Award.Grant__c = 'Test127262';
        Award.Amendment__c=0;
        Award.RecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('App Award').getRecordTypeId();
        insert award;
        
    test.starttest();  
        
        Award_Reporting__c arep=new Award_Reporting__c();
        arep.Award__c=award.Id;
        arep.Expenditure_Comments__c='test';
        arep.Total_Fed_Funds_authorized_Cumulative__c=1000;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        
        arep.Federal_Share_of_expenditures__c =5;
        arep.Fed_Share_of_expenditures_This_Period__c=5;
        
        arep.Total_Recipient_share_required__c =10;
        arep.Total_Federal_Funds_authorized__c =10;
        arep.Match_Comments__c='test';
        arep.Submitted_Date__c=Date.Today()+95;
        insert arep;
        arep.Submitted_Date__c=Date.Today()+100;
        update arep;
      
        arep.Total_Fed_Funds_authorized_Cumulative__c=2;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        
        arep.Total_Fed_Funds_authorized_Cumulative__c=2;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        update arep;
        
        arep.Submitted_Date__c=Date.Today()+190;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=100;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        
        arep.Total_Fed_Funds_authorized_Cumulative__c=100;
        arep.Recipient_share_of_exp_Cumulative__c=79;
        update arep;
        
        arep.Total_Fed_Funds_authorized_Cumulative__c=100;
        arep.Recipient_share_of_exp_Cumulative__c=75;
        update arep;
        
        arep.Submitted_Date__c=Date.Today()+400;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=3;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=50;
        update arep;
       
        arep.Submitted_Date__c=Date.Today()+600;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=3;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=9;
        update arep; 
        
        arep.Submitted_Date__c=Date.Today()+750;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=3;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=100;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        update arep;         
       
        arep.Submitted_Date__c=Date.Today()+950;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=3;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=9;
        update arep;       
        test.stoptest();
        
        
    }
     public static testmethod void method2()
    {
        Application3__c app = UtilityClass.createApplication();
        app.Proposed_Start_Date__c = Date.Today();
        insert app;
        
        Master_Award__c MasterAward = new Master_Award__c();
        MasterAward.Application__c = app.Id;
        MasterAward.Name = 'test34';
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        insert MasterAward;
       
        Award__c Award = new Award__c();
        Award.Application_ID__c = app.Id;
        Award.Master_Award__c = MasterAward.Id;
        Award.NOFA_Name__c = app.NOFA_RFP__c;       
        Award.Name = 'Test Award';
        Award.Organization__c = app.Organization__c;
        Award.Grant_Status__c = 'Awaiting PO Certification';
        Award.Grant__c = 'Test127262';
        Award.Amendment__c=0;
        Award.RecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('App Award').getRecordTypeId();
        insert award;
       
     test.starttest();   
        
        Award_Reporting__c arep=new Award_Reporting__c();
        arep.Award__c=award.Id;
        arep.Expenditure_Comments__c='test';
        arep.Total_Fed_Funds_authorized_Cumulative__c=1000;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        
        arep.Federal_Share_of_expenditures__c =5;
        arep.Fed_Share_of_expenditures_This_Period__c=5;
        
        arep.Total_Recipient_share_required__c =10;
        arep.Total_Federal_Funds_authorized__c =10;
        arep.Match_Comments__c='test';
        arep.Submitted_Date__c=Date.Today()+95;
        insert arep;
    
        arep.Submitted_Date__c=Date.Today()+1100;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=3;
        arep.Recipient_share_of_exp_Cumulative__c=1;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=100;
        update arep;
        arep.Total_Fed_Funds_authorized_Cumulative__c=10;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        update arep; 
                
        arep.Submitted_Date__c=Date.Today()+500;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 7;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 1;
        MasterAward.Obligation__c= 10;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        update MasterAward;
        update arep;
            
        arep.Submitted_Date__c=Date.Today()+800;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 7.5;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 1;
        MasterAward.Obligation__c= 10;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        update MasterAward;
        update arep;
        
        arep.Submitted_Date__c=Date.Today()+1100;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 8;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 1;
        MasterAward.Obligation__c= 10;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        update MasterAward;
        update arep;
        
        arep.Submitted_Date__c=Date.Today()+1600;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 8.5;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 1;
        MasterAward.Obligation__c= 10;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        update MasterAward;
        update arep;
       

      test.stoptest();    
    }
        
         public static testmethod void method3()
    {
      Profile p = [SELECT Id FROM Profile WHERE Name='Program Officer']; 
      User u = new User(Alias = 'standt', Email='standarduser@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = p.Id, 
      TimeZoneSidKey='America/Los_Angeles', UserName='standardusertesting@test.com');
        
        system.runas(u)
        {
            
      
        Application3__c app = UtilityClass.createApplication();
        app.Proposed_Start_Date__c = Date.Today();
        insert app;
        
        Master_Award__c MasterAward = new Master_Award__c();
        MasterAward.Application__c = app.Id;
        MasterAward.Name = 'test34';
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        insert MasterAward;
 /*           
       Project__c proj = UtilityClass.createProject();
       insert proj; 
            
        Account acc= UtilityClass.createOrganization();
        insert acc;
  
        Contact c= UtilityClass.createContact();
        insert c;
      */     
        //Prime_Application__c pm=new Prime_Application__c(Name='Test Pm');
        //insert pm;
            
      test.starttest();       
        Award__c Award = new Award__c();
        Award.Application_ID__c = app.Id;
        Award.Master_Award__c = MasterAward.Id;
      //Award.Prime_Application__c = pm.Id;
        Award.NOFA_Name__c = app.NOFA_RFP__c;       
        Award.Name = 'Test Award';
        Award.Organization__c = app.Organization__c;
        Award.Grant_Status__c = 'Awaiting PO Certification';
        Award.Grant__c = 'Test127262';
        Award.Amendment__c=0;
        Award.RecordTypeId = Schema.SObjectType.Award__c.getRecordTypeInfosByName().get('App Award').getRecordTypeId();
        insert award;
        
        
        Award_Reporting__c arep=new Award_Reporting__c();
        arep.Award__c=award.Id;
        arep.Expenditure_Comments__c='test';
        arep.Total_Fed_Funds_authorized_Cumulative__c=1000;
        arep.Recipient_share_of_exp_Cumulative__c=10;
        
        arep.Federal_Share_of_expenditures__c =5;
        arep.Fed_Share_of_expenditures_This_Period__c=5;
        
        arep.Total_Recipient_share_required__c =10;
        arep.Total_Federal_Funds_authorized__c =10;
        arep.Match_Comments__c='test';
        arep.Submitted_Date__c=Date.Today()+95;
        insert arep;
            
        arep.Submitted_Date__c=Date.Today()+1900;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 9;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 1;
        MasterAward.Obligation__c= 10;
        update MasterAward;
        update arep;
        MasterAward.Commitment__c = 10;
        MasterAward.Obligation__c= 1;
        update MasterAward;
        update arep;
     
      test.stoptest();    
    }
    }
}