src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Application_Feedback__c.object
<CustomObject>
    <label>Application Feedback</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Application Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CNCS_Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CNCS Corporate Program</label>
        <referenceTo>CNCS_Corporate_Program__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CNCS_Corporate_Program__c.object
<CustomObject>
    <label>CNCS Corporate Structure</label>
    <nameField>
        <label>CNCS Corporate Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CNCS Corporate Structure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>CNCS_Corporate_Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Corporate Program Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>CNCS_Corporate_Program__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Corporate_Program</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>CNCS_Corporate_Program__c</referenceTo>
        <relationshipLabel>NOFOs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentHelper.cls
public with sharing class AttachmentHelper {
    
    public static void makeApplicationFeedbackAttachmentsPublic(list<Attachment> attachments){
        String appFeedbackPrefix = Application_Feedback__c.sobjecttype.getDescribe().getKeyPrefix();
        String appPrefix = Application3__c.sobjecttype.getDescribe().getKeyPrefix();
        String AwardPrefix = Award__c.sobjecttype.getDescribe().getKeyPrefix();
        String CorpProgPrefix = CNCS_Corporate_Program__c.sobjecttype.getDescribe().getKeyPrefix();
        String NOFOPrefix = NOFA__c.sobjecttype.getDescribe().getKeyPrefix();
        String ContactPrefix = Contact.sobjecttype.getDescribe().getKeyPrefix();
        
        for(Attachment a: attachments){
            String parentId = (String)a.ParentId;
              if(parentId.startsWith(appFeedbackPrefix) || parentId.startsWith(appPrefix) || parentId.startsWith(AwardPrefix) || parentId.startsWith(CorpProgPrefix)|| parentId.startsWith(NOFOPrefix) || parentId.startsWith(ContactPrefix)){
           // if(parentId.startsWith(appFeedbackPrefix)){
                if(a.IsPrivate){
                    a.IsPrivate = false;
                    
                } 
            }
        }
    }

}