src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monitoring_Activity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Monitoring Activity</label>
        <referenceTo>Monitoring_Activity__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stage</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monitoring_Activity__c.object
<CustomObject>
    <description>Monitoring Activities associated to Monitoring Plans.</description>
    <fields>
        <fullName>Monitoring_Activity__c</fullName>
        <label>Monitoring Activity</label>
        <picklist>
            <picklistValues>
                <fullName>Programmatic &amp; Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Visit – Programmatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desk Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drawdown Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up Compliance Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-site Compliance Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-site Training/Technical Assistance (T/TA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Standards review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted/Issue-based Site Visit</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Monitoring Activity</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Monitoring Activity Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA_Group__c.object
<CustomObject>
    <label>NOFO Group</label>
    <nameField>
        <displayFormat>NOFA Group ID-{0000}</displayFormat>
        <label>NOFO Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddAttachmentsContTest.cls
@isTest
private class AddAttachmentsContTest {
    public static AddAttachmentsController ext;
    public static AddAttachmentsController ext2;
    
    static testMethod void myUnitTest() {
       
        Utilityclass.insertFieldIds();
        Pagereference pref = Page.AddAttachments;
        test.setCurrentPage(pref);
        Monitoring_Activity__c ma = UtilityClass.createMonitoringActivity();
        insert ma;
        Apexpages.currentPage().getParameters().put('CF00Nr0000000Oh4V_lkid',ma.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Attachment__c());
        ext = new AddAttachmentsController(controller);
        //ext.Options();
        ext.fileName = 'test';
        ext.fileBody = Blob.valueOf('test');
        list<selectOption> soptions; 
        soptions = ext.Options;
        ext.processUpload();
        ext.back();      
        
        Account a = UtilityClass.createOrganization();
        insert a;
        Apexpages.currentPage().getParameters().put('CF00Nr0000000OGTx_lkid',a.Id);   
        
        ApexPages.StandardController controller2 = new ApexPages.StandardController(new Attachment__c());
        ext2 = new AddAttachmentsController(controller2);
        //ext.Options();
        ext2.fileName = 'test';
        ext2.fileBody = Blob.valueOf('test');
        list<selectOption> soptions2; 
        soptions2 = ext2.Options;
        ext2.processUpload();
        //ext2.back();       
    }
    
    static testMethod void myUnitTest2() {
        Utilityclass.insertFieldIds();
        Contact c = UtilityClass.createContact();
        insert c;
        Apexpages.currentPage().getParameters().put('CF00Nr0000000OR9y_lkid',c.Id);   
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Attachment__c());
        ext = new AddAttachmentsController(controller);
        //ext.Options();
        ext.fileName = 'test';
        ext.fileBody = Blob.valueOf('test');
        list<selectOption> soptions; 
        soptions = ext.Options;
        ext.processUpload();
        
        
        Nofa_Group__c ng = Utilityclass.createNofaGroup();
        insert ng;
        Stages__c stage = UtilityClass.createStage();
        stage.NOFA_Group__c = ng.Id;
        insert stage;
        
        Apexpages.currentPage().getParameters().put('CF00Nr0000000OD8D_lkid',stage.Id);   
        
        ApexPages.StandardController controller2 = new ApexPages.StandardController(new Attachment__c());
        ext2 = new AddAttachmentsController(controller2);
        //ext.Options();
        ext2.fileName = 'test';
        ext2.fileBody = Blob.valueOf('test');
        list<selectOption> soptions2; 
        soptions2 = ext.Options;
        ext2.processUpload();
        ext2.back();
        
        
        
    }
    
    static testMethod void myUnitTest3() {
        Utilityclass.insertFieldIds();
        NOFA__c nofa = UtilityClass.createNofa();
        insert nofa;
        
        Apexpages.currentPage().getParameters().put('CF00Nr0000000OB3z_lkid',nofa.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Attachment__c());
        ext = new AddAttachmentsController(controller);
        //ext.Options();
        ext.fileName = 'test';
        ext.fileBody = Blob.valueOf('test');
        list<selectOption> soptions; 
        soptions = ext.Options;
        ext.processUpload();
        
        
        
    }
    
    static testMethod void myUnitTest4(){
        Utilityclass.insertFieldIds();
        Application3__c app = UtilityClass.createApplication();
        insert app;
        
        Apexpages.currentPage().getParameters().put('CF00Nr0000000OB8Q_lkid',app.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Attachment__c());
        ext = new AddAttachmentsController(controller);
        //ext.Options();
        ext.fileName = 'test';
        ext.fileBody = Blob.valueOf('test');
        list<selectOption> soptions; 
        soptions = ext.Options;
        ext.processUpload();       
        
    }
    
    static testMethod void myUnitTest5(){
        Utilityclass.insertFieldIds();
        Award__c aw = UtilityClass.createAward();
        insert aw;
        
        Apexpages.currentPage().getParameters().put('CF00Nr0000000OHGB_lkid',aw.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Attachment__c());
        ext = new AddAttachmentsController(controller);
        //ext.Options();
        ext.fileName = 'test';
        ext.fileBody = Blob.valueOf('test');
        list<selectOption> soptions; 
        soptions = ext.Options;
        ext.processUpload();       
        
    }
}