src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ConceptPaperTest.cls
@isTest
private class ConceptPaperTest {
	
	public static ConceptpapereditExt ext;
	public static NOFAtoConceptPaperUIExt nofaTocpExt;
	public static NotificationEditpageExt notificationEditExt;
	public static NOFAtoNotificationUIExt nofaToNotificationExt;
	
    static testMethod void conceptPaperEditTest() {
    	Application3__c conceptPaper = UtilityClass.createConceptPaper();
    	insert conceptPaper;
    	
    	Apexpages.currentPage().getParameters().put('id',conceptPaper.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(conceptPaper);
        ext = new ConceptpapereditExt(controller);
        
        Pagereference pref = Page.ConceptPaperEdit;
	    test.setCurrentPage(pref);
        ext.getThis();
        ext.reopen1();
        ext.SaveAsDraft();
        ext.Validate();    	
    	
        
    }
    
    static testMethod void nofaToConceptPaperTest() {
        Application3__c conceptPaper = UtilityClass.createConceptPaper();
    	insert conceptPaper;
    	
    	NOFA__c nofa = [Select Id,Name from NOFA__c where id = :conceptPaper.NOFA_RFP__c];
    	
    	Apexpages.currentPage().getParameters().put('id',conceptPaper.NOFA_RFP__c);
        Apexpages.currentPage().getParameters().put('projectid',conceptPaper.Project__c);
        //Apexpages.currentPage().getParameters().put('primeApplicationId',app.Prime_Application__c);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(nofa);
        nofaTocpExt = new NOFAtoConceptPaperUIExt(controller);
        
        Pagereference pref = Page.NOFAtoConceptPaperUI;
	    test.setCurrentPage(pref);
	    
	    //nofaTocpExt.createProject();
	    nofaTocpExt.getThis();
	    nofaTocpExt.SaveAsDraft();
	    //nofaTocpExt.save1();
	    nofaTocpExt.Validate();
	    
    }
    
    static testMethod void notificationEditTest(){

    	Application3__c intentToApply = UtilityClass.createNotification();
    	insert intentToApply;
    	
    	Apexpages.currentPage().getParameters().put('id',intentToApply.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(intentToApply);
        notificationEditExt = new NotificationEditpageExt(controller);
        
        Pagereference pref = Page.NotificationEditPage;
	    test.setCurrentPage(pref);
	    
	    notificationEditExt.edit();
	    notificationEditExt.save();
	    
	    
    }
    
     static testMethod void nofaToNotificationTest() {
        Application3__c intentToApply = UtilityClass.createNotification();
    	insert intentToApply;
    	
    	NOFA__c nofa = [Select Id,Name from NOFA__c where id = :intentToApply.NOFA_RFP__c];
    	
    	Apexpages.currentPage().getParameters().put('id',intentToApply.NOFA_RFP__c);
        Apexpages.currentPage().getParameters().put('projectid',intentToApply.Project__c);
        //Apexpages.currentPage().getParameters().put('primeApplicationId',app.Prime_Application__c);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(nofa);
        nofaToNotificationExt = new NOFAtoNotificationUIExt(controller);
        
        Pagereference pref = Page.NotificationofIntenttoApply;
	    test.setCurrentPage(pref);
	    
	    //nofaToNotificationExt.save();
	    nofaToNotificationExt.SaveAsDraft();
	    
     }
}