src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_Feedback_Summary__c</fullName>
        <label>Application Feedback Summary</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Authorized_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for Notification of Intent to Apply section of the Application.</description>
        <label>Authorized Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the epert reviewer application</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - SAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/NofaSendEmailsCont.cls
public with sharing class NofaSendEmailsCont {
  private ApexPages.StandardController controller;
  
    public NofaSendEmailsCont(ApexPages.StandardController controller) {
    this.controller = controller;
    }
    
    public PageReference sendEmails(){
       Id recordId = controller.getId();
       system.debug('nofa id = '+recordId);
       set<String> templates = new set<string>{'Application_Accepted','Application_Rejected'};
       Id appRTID = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
       map<String,EmailTemplate> templateMap = new map<String,EmailTemplate>();
       list<EmailTemplate> emailTemplates = new list<EmailTemplate>([Select e.DeveloperName,e.Subject, e.Name, e.Id, e.Description, e.Body From EmailTemplate e where DeveloperName in :templates ]); 
       for(EmailTemplate e: emailTemplates){
         templateMap.put(e.DeveloperName,e);
       }
       List<Application3__c> apps = new List<Application3__c>([Select Id,RecordTypeId,Name,Status__c,Application_Feedback_Summary__c,Authorized_Representative__c,Authorized_Representative__r.Email,Authorized_Representative__r.Name,Grantee_Status__c from Application3__c where Nofa_Rfp__c = :recordId]);
       list<Id> acceptedIds = new list<Id>();
       list<Id> rejectedIds = new list<Id>();
       system.debug('apps = '+apps.size());
       if(apps.size()>0){
       	try{
         for(Application3__c a: apps){
           if(a.RecordTypeId == appRTID){
             system.debug('status = '+a.status__c);
             if(a.Status__c=='Accepted'){
               //send accepted email
               if(a.Authorized_Representative__c!=null){
                 /*acceptedIds.add(a.Authorized_Representative__c);    */           
                 //try{
                    String subject = templateMap.get('Application_Accepted').subject;    
                    String body = templateMap.get('Application_Accepted').body;
                    if(body.contains('{!Application3__c.Authorized_Representative__c}'))
                        body = (null == a.Authorized_Representative__c) ? body : body.replace('{!Application3__c.Authorized_Representative__c}',a.Authorized_Representative__r.Name); 
                    if(body.contains('{!Application3__c.Application_Feedback_Summary__c}'))
                        body = (null == a.Application_Feedback_Summary__c) ? body.replace('{!Application3__c.Application_Feedback_Summary__c}',' ') : body.replace('{!Application3__c.Application_Feedback_Summary__c}',a.Application_Feedback_Summary__c); 
                    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
                    list<String> addressesToSend = new list<String>();        
                    addressesToSend.add(a.Authorized_Representative__r.Email);                                       
                    email.setSubject( subject );
                    email.setToAddresses( addressesToSend );
                    email.setPlainTextBody( body );                                                                   
                    Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});  
                 	//ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Successfully sent Accepted Emails'));
                    //return null;
                 
                 /*}
                 catch(Exception e){
                   ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Could not send emails,please contact your administrator: '+e));
                   return null;
                 }*/
               }                                       
             }
             else if(a.Status__c=='Rejected'){
               //send rejected email
               if(a.Authorized_Representative__c!=null){
                 /*rejectedIds.add(a.Authorized_Representative__c); */
                 //try{
                   String subject = templateMap.get('Application_Rejected').subject;    
                   String body = templateMap.get('Application_Rejected').body;
                   if(body.contains('{!Application3__c.Authorized_Representative__c}'))
                      body = (null == a.Authorized_Representative__c) ? body : body.replace('{!Application3__c.Authorized_Representative__c}',a.Authorized_Representative__r.Name); 
                   if(body.contains('{!Application3__c.Application_Feedback_Summary__c}'))
                      body = (null == a.Application_Feedback_Summary__c) ? body.replace('{!Application3__c.Application_Feedback_Summary__c}',' ') : body.replace('{!Application3__c.Application_Feedback_Summary__c}',a.Application_Feedback_Summary__c); 
                   Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
                   list<String> addressesToSend = new list<String>();        
                   addressesToSend.add(a.Authorized_Representative__r.Email);                                       
                   email.setSubject( subject );
                   email.setToAddresses( addressesToSend );
                   email.setPlainTextBody( body );                                                                   
                   Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
                   //ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Successfully sent Rejection Emails'));
                   //return null;
                 /*}
                 catch(exception e){
                   ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Could not send emails,please contact your administrator '+e));
                   return null;
                 }*/
               }
             }
           }
         }
         ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Sent successfully emails'));
         return null;
       	}
       	catch(Exception e){
       		 ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Could not send emails,please contact your administrator '+e));
             return null;
       	}
         /*if(acceptedIds.size()>0){
           try{
             Messaging.MassEmailMessage emails=new Messaging.MassEmailMessage(); 
              emails.setTargetObjectIds(acceptedIds);
              emails.setTemplateId(templateMap.get('Application_Accepted').Id);
              //emails.setsubject(templateMap.get('Application_Accepted').subject);
              Messaging.SendEmail(New Messaging.MassEmailMessage[]{emails});
           }
           catch(exception e){
             
           }
         }
         system.debug('rejectedIds = '+rejectedIds.size());         
         if(rejectedIds.size()>0){
           try{
          Messaging.MassEmailMessage emails=new Messaging.MassEmailMessage(); 
              emails.setTargetObjectIds(rejectedIds);
              emails.setTemplateId(templateMap.get('Application_Rejected').Id);
              //emails.setsubject(templateMap.get('Application_Rejected').subject);
              Messaging.SendEmail(New Messaging.MassEmailMessage[]{emails});
           }
           catch(exception e){
             
           }
         }*/
         
       }
         /*PageReference pageRef = new PageReference('/'+recordId);
         pageRef.setRedirect(true);
         return pageRef;*/
         return null;
      
    }

}