src/objects/Application_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Review_Panel__c</fullName>
        <label>External Review Panel</label>
        <referenceTo>Expert_Review_Panel__c</referenceTo>
        <relationshipLabel>Application Feedback</relationshipLabel>
        <relationshipName>Application_Feedback</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Panel_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Feedback (Panel Coordinator)</relationshipLabel>
        <relationshipName>Application_Feedback1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Liasion1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Liasion</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application_Feedback1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Feedback</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Application Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>Id of the actual/standard attachment, this is referenced in the view formula field</description>
        <label>Attachment Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expert_Review_Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Review Panel</label>
        <referenceTo>Expert_Review_Panel__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stage</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist for storing the type of document/attachment</description>
        <label>File Type</label>
        <picklist>
            <picklistValues>
                <fullName>1199 Direct Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Articles of Incorporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor’s Statement Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Financial Report User Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Management Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Statement Audit or SF-990</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Certification Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governing Body Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRS Certification of Non-Profit Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor Union Concurrence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List of names of any funding organizations/sources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logic Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Match Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiated indirect cost agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organizational Chart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipient contact Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor/Project Director Position Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor&apos;s Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1199 Direct Deposit Contact Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAE Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAE Waiver Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Expert_Review_Panel__c.object
<CustomObject>
    <fields>
        <fullName>Panel_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Its a lookup to panel members object to select a panel member</description>
        <label>Panel Member</label>
        <referenceTo>Panel_Member__c</referenceTo>
        <relationshipName>Peer_Review_Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>External Review Panel</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Peer Review Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Review Panel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Panel_Application__c.object
<CustomObject>
    <fields>
        <fullName>Paneling__c</fullName>
        <label>Paneling</label>
        <referenceTo>Paneling__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Panel Application</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Panel Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Panel_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Contact object to find panel coordinator</description>
        <label>Panel Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Paneling</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Staff_Liasion1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Staff Liasion</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>PO</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Paneling</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the panel</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert or Blended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>Instructions_to_Reviewers__c</fullName>
        <description>Instructions are given to the reviewers</description>
        <label>Instructions to Reviewers</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Section_1__c</fullName>
        <description>Name of the section1 of that stage</description>
        <label>Section 1 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_2__c</fullName>
        <description>Name of the section2 of that stage</description>
        <label>Section 2 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_3__c</fullName>
        <description>Name of the section3 of that stage</description>
        <label>Section 3 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_4__c</fullName>
        <description>Name of the section4 of that stage</description>
        <label>Section 4 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_5__c</fullName>
        <description>Name of the section5 of that stage</description>
        <label>Section 5 Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Describes the type of that particular stage</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blended</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AssignPanels.cls
public with sharing class AssignPanels {
	public static void panelAssignments(set<Id> panelIds){
		
        // Apex code for handling record from a Detail page goes here
        set<Id> stageIds = new set<Id>();
      
        map<Id,Paneling__c> panelMap = new map<Id,Paneling__c>();
        list<Paneling__c> panels = [Select Id,Staff_Liasion1__c,Panel_Coordinator__c,Name,Stage_Number__c,Stage_Number__r.Instructions_to_Reviewers__c from Paneling__c where Id in :panelIds];
        for(Paneling__c p: panels){
        	stageIds.add(p.Stage_Number__c);
        	panelMap.put(p.Id,p);
        }
        
        list<Stages__c> stages = [Select Name, Id,  Section_1__c, Section_2__c, Section_3__c, Section_4__c, Section_5__c, Instructions_to_Reviewers__c,(Select Id, Attachment_Id__c, Name, Description__c, Type__c, Stages__c From Attachments__r) 
                             From Stages__c  where Id in :stageIds];
        map<Id,Stages__c> stageMap = new map<Id,Stages__c>();
        for(Stages__c s:stages){
        	stageMap.put(s.Id,s);
        }
        Set<Id> PanelMembers = new Set<Id>();
        Set<Id> PanelMembers1 = new Set<Id>();
        Set<Id> PanelApplications = new Set<Id>();      
        
       
        /*map<Id,Panel_Member__c> reviewerIdtoPMId = new map<Id,Panel_Member__c>();
        map<Id, Panel_Member__c> staffReviewerIdtoPMId = new map<Id,Panel_Member__c>();*/
        
        List<Expert_Review_Panel__c> ExpertReviewPanels = new List<Expert_Review_Panel__c>();
        List<Application_Feedback__c> AppFeedbackList = new List<Application_Feedback__c>();
        List<Feedback_questions__c> Feedques = new List<Feedback_questions__c>();
        List<Stage_Question__c > SQ1= new List<Stage_Question__c >();
        
        /* Get a list of all of the Contacts associated with the panel */
        List<Panel_Member__c> panelMemberList = new List<Panel_Member__c>();
        List<Panel_Member__c> panelMemberList1 = new List<Panel_Member__c>();
        panelMemberList1 = [SELECT Id,Staff_Member__c,Role__c,Panel__c FROM Panel_Member__c where Panel__c in :panelIds and Staff_Member__c!=null];
        panelMemberList = [SELECT Id,Expert_Reviewer__c,Role__c,Panel__c FROM Panel_Member__c where Panel__c in :panelIds and Expert_Reviewer__c!=null];       
        for(Panel_Member__c pm: panelMemberList){
          PanelMembers.add(pm.Expert_Reviewer__c);          
          //reviewerIdtoPMId.put(pm.Expert_Reviewer__c,pm); 
        }
        for(Panel_Member__c pm1: panelMemberList1){
          PanelMembers1.add(pm1.Staff_Member__c);
          //staffReviewerIdtoPMId.put(pm1.Staff_Member__c,pm1);
          
        }
        
        
        

        /* Get a list of all of the Applications associated with the panel */
        List<Panel_Application__c> panelApplicationList = new List<Panel_Application__c>();
        panelApplicationList = [SELECT Id,Application__c,Paneling__c FROM Panel_Application__c where Paneling__c in :panelIds];
        map<Id,Panel_Application__c> panelAppMap = new map<Id,Panel_Application__c>();
        for(Panel_Application__c pm: panelApplicationList){
          PanelApplications.add(pm.Application__c);
          panelAppMap.put(pm.Application__c,pm);
        }
        
        //List<Stage_Question__c > SQ1 = new List<Stage_Question__c >();
        SQ1 = [SELECT ID, Name,Active__c, If_Yes_Comments_Required__c,Question__c,Scoring_Method__c,Section__c,Weight__c,Roles__c,Stages_ID__c FROM Stage_Question__c where Stages_ID__c in :stageIds order by Section__c];
        
        /* Create an Expert Reviewer Panel Object for each Reviewer */
        for(Paneling__c p:panels){
	        for (Panel_Member__c pm: panelMemberList){
	        	if(pm.Panel__c == p.Id){
		            Expert_Review_Panel__c exp = new Expert_Review_Panel__c();
		            if(pm != null)
			        {	
			        	system.debug('got here in exp loop = ');
			            exp.Reviewer__c = pm.Expert_Reviewer__c;
			            exp.Panel__c = p.Id;
			            exp.Panel_Member__c = pm.Id;
			            exp.Role__c = pm.Role__c;
			            //Set the Status 
			            ExpertReviewPanels.add(exp);
		            }
	        	}
	        }
        }
        for(Paneling__c p:panels){
	       	 for(Panel_Member__c pm: panelMemberList1){
	       	 	if(pm.Panel__c == p.Id){
		            Expert_Review_Panel__c exp1 = new Expert_Review_Panel__c();
		            if(pm != null)
		            {
			            exp1.Staff_Reviewer__c= pm.Staff_Member__c;
			            exp1.Panel__c = p.Id;
			            exp1.Panel_Member__c = pm.Id;
			            exp1.Role__c = pm.Role__c;
			            //Set the Status 
			            ExpertReviewPanels.add(exp1);
		            }
	       	 	}
	         }
        }
        system.debug('ExpertReviewPanels = '+ExpertReviewPanels);
        insert ExpertReviewPanels;
        
        
        
      
        
        
        /* Create an Expert Reviewer Panel Object for each Reviewer */
        system.debug('ExpertReviewPanels = '+ExpertReviewPanels);
        system.debug('panelApplications = '+panelApplications);
        for (Expert_Review_Panel__c ExpertPanel: ExpertReviewPanels){              
            for (Panel_Application__c pa: panelApplicationList){
            	if(ExpertPanel.Panel__c == pa.Paneling__c){
            		system.debug('got here in app feedback loop ');
	                Application_Feedback__c appFeedback = new Application_Feedback__c();
	                appFeedback.Expert_Review_Panel__c = ExpertPanel.Id;
	                
	                appFeedback.Application__c = pa.Application__c;
	                appFeedback.Instructions__c = panelMap.get(ExpertPanel.Panel__c).Stage_Number__r.Instructions_to_Reviewers__c ;
	                appFeedback.Staff_Liasion1__c= panelMap.get(ExpertPanel.Panel__c).Staff_Liasion1__c;
	                appFeedback.Panel_Coordinator__c = panelMap.get(ExpertPanel.Panel__c).Panel_Coordinator__c; 
	                //Need to add the Feedback Form
	                AppFeedbackList.add(appFeedback);
            	}
                    
            }  
        
        }
        
        if(AppFeedbackList.size()>0){           
            insert AppFeedbackList;
        }
        
        
       // Stage_Question__c stageque = [ Select Id, Name, Active__c, Allow_Comments__c, If_Yes_Comments_Required__c, Question__c, Roles__c, Scoring_Method__c, Section__c, Weight__c from Stage_Question__c where Id = :stage];
       list<Application_Feedback__c> appFeedBacks = new list<Application_Feedback__c>([Select Id,Expert_Review_Panel__r.Panel__r.Stage_Number__c from
       													Application_Feedback__c where Id in :AppFeedbackList]); 
       if(AppFeedbackList.size()>0 && SQ1.size()>0){ 
           for(Application_Feedback__c AppFeedback:appFeedBacks)
           {
                for( Stage_Question__c sq: SQ1 ) 
                { 
                  system.debug('sq.Stages_ID__c '+sq.Stages_ID__c);
            	  system.debug('AppFeedback.Expert_Review_Panel__r.Panel__r.Stage_Number__c '+AppFeedback.Expert_Review_Panel__r.Panel__r.Stage_Number__c); 	
                  if(sq.Stages_ID__c == AppFeedback.Expert_Review_Panel__r.Panel__r.Stage_Number__c){ 
                  		
                   Feedback_questions__c fq = new Feedback_questions__c();
                   fq.Application_Feedback__c = AppFeedback.Id;
                   fq.Stage_Question2__c = sq.Id;
                   fq.Stages_ID__c = sq.Stages_ID__c;
                   fq.Question__c = sq.Question__c;
                   fq.Scoring_Method__c = sq.Scoring_Method__c;
                   fq.weight__c = sq.Weight__c;
                   fq.Active__c = sq.Active__c;
                   fq.Comments_Required__c = sq.If_Yes_Comments_Required__c;
                   fq.Roles__c = sq.Roles__c; 	
                 
                   if(sq.Section__c == 'Section 1')
                   {
                   fq.Name__c = stageMap.get(sq.Stages_ID__c).Section_1__c;
                   }
                   else if(sq.Section__c== 'Section 2')
                   {
                   fq.Name__c = stageMap.get(sq.Stages_ID__c).Section_2__c;
                   }
                   else if(sq.Section__c== 'Section 3')
                   {
                   fq.Name__c = stageMap.get(sq.Stages_ID__c).Section_3__c;
                   }
                   else if(sq.Section__c== 'Section 4')
                   {
                   fq.Name__c = stageMap.get(sq.Stages_ID__c).Section_4__c;
                   }
                   else
                   {
                   fq.Name__c = stageMap.get(sq.Stages_ID__c).Section_5__c;
                   }
                   
                   
                   //fq.ID= panelQuestion2;
                   Feedques.add(fq);
                
                }
                }
           }
       }
       if(Feedques.size()>0){
          insert Feedques;
       }
        
        
        
        
    
    }
	
}