src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Application_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Application ID related to Award.</description>
        <label>Application ID</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Source__c.object
<CustomObject>
    <description>Funding Source</description>
    <fields>
        <fullName>Fiscal_Yr_Basis__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Fiscal Year and Fund Code</label>
        <referenceTo>Fiscal_Yr_Basis__c</referenceTo>
        <relationshipLabel>Funding Source</relationshipLabel>
        <relationshipName>Funding_Source</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Funding Source (NOFO/RFP)</relationshipLabel>
        <relationshipName>Funding_Source1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Source</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Funding Source ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Source</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Fund_Commitment.cls
Public Class Fund_Commitment{


Public Fund_Commitment__c fc;
Public List<Funding_Source__c> fs_List{get;set;}
Public Funding_Source__c Selected_fs_radio{get;set;}
public boolean displayPopup {get; set;} 
Public String selected_fs{get;set;}
Public List<SelectOption> options{get;set;}
Public List<Award__c> award_List;
 Public Fund_Commitment(ApexPages.StandardController con){
 
 fc=(Fund_Commitment__c)con.getRecord();
 fs_List=new List<Funding_Source__c>();
 Map<String,String> parammap=apexPages.currentPage().getParameters();
 String awardId = apexPages.currentPage().getParameters().get('rid');

 System.debug('MAP%%%'+parammap.keyset()+'^^^'+fc);
 System.debug('Award_ID'+awardId);
 
  award_List = [Select Application_ID__r.NOFA_RFP__c from Award__c where id=:awardId];
  System.debug('Award_ID'+award_List[0]);
   if(award_List.size()>0){
    fs_List=[Select name from Funding_Source__c where NOFA__c=:award_List[0].Application_ID__r.NOFA_RFP__c];
  System.debug('test'+fs_List);
   } 
 
}

 Public void Select_Action(){
 options = new List<SelectOption>();
 displayPopup = true;
 for(Funding_Source__c fs:fs_List){
 options.add(new SelectOption(fs.id,fs.name));
 }
 }

 Public Pagereference Submit(){
 PageReference PR;
  System.debug('Selected_Record'+selected_fs);
  String fiscal_year_basis;
  List<String> split_List;
  displayPopup = false; 
  if(selected_fs!=null){
    Selected_fs_radio = [Select name,Fiscal_Yr_Basis__r.name from Funding_Source__c where id=:selected_fs];
  System.debug('Selected_Record_ID'+Selected_fs_radio.Fiscal_Yr_Basis__r.name);
  fiscal_year_basis=Selected_fs_radio.Fiscal_Yr_Basis__r.name;
  split_List=fiscal_year_basis.split('-');
  
  if(split_List.size()==2){
     Fund_Commitment__c fc = new Fund_Commitment__c();
     fc.name=Selected_fs_radio.name;
     fc.Start_FY__c=split_List[0];
     fc.Fund__c=split_List[1];
     fc.Award__c=award_List[0].id;
     Insert fc;
     PR = new PageReference('/'+award_List[0].id);
     return PR;
  }
  
  else if(split_List.size()==3){
     Fund_Commitment__c fc = new Fund_Commitment__c();
     fc.name=Selected_fs_radio.name;
     fc.Start_FY__c=split_List[0];
     fc.Ending_FY__c=split_List[1];
     fc.Fund__c=split_List[2];
     fc.Award__c=award_List[0].id;
     Insert fc;
     PR = new PageReference('/'+award_List[0].id);
     return PR;
  }
  
  }
     return null;
 }

 public void closePopup() {        
        displayPopup = false;    
    }     
    
 public void showPopup() {        
        displayPopup = true;    
    }



}