src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>contains</operation>
                <value>Continuation, New &amp; Continuation</value>
            </filterItems>
            <filterItems>
                <field>$Source.CNCS_Corporate_Program__c</field>
                <operation>equals</operation>
                <valueField>NOFA__c.CNCS_Corporate_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>equals</operation>
                <value>New, New &amp; Continuation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PrimeNofaSelectionForCloneCont.cls
public class PrimeNofaSelectionForCloneCont {
    
    public Prime_Application__c PrimeApp{get;set;}
    public string ParentPrimeId{get;set;}
    public PrimeNofaSelectionForCloneCont(ApexPages.StandardController controller) {
        PrimeApp = new Prime_Application__c();
        ParentPrimeId=ApexPages.currentPage().getParameters().get('parentId');
    }
    
    public PageReference continueApp(){
        PageReference pg = new PageReference('/apex/ClonePlus?id='+ParentPrimeId+'&childobjecttypes=Application3__c&NofaId='+PrimeApp.NOFO_RFP__c);
        return pg;
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference('/apex/PrimeApplicationDetail?Id='+ParentPrimeId);
        return pg;
    }
    
    

}