src/objects/Application_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Accepted_by_Panel_Coordinator__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted by Panel Coordinator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Accepted_by_Staff_Liaison__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted by Staff Liaison</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Expert_Review_Panel__c</fullName>
        <label>External Review Panel</label>
        <referenceTo>Expert_Review_Panel__c</referenceTo>
        <relationshipLabel>Application Feedback</relationshipLabel>
        <relationshipName>Application_Feedback</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Review Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In - Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted by CNCS</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application Feedback</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Application Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expert_Review_Panel__c.object
<CustomObject>
    <fields>
        <fullName>Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Panel</label>
        <referenceTo>Paneling__c</referenceTo>
        <relationshipName>Expert_Review_Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact object to find a reviewer</description>
        <label>External Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Expert_Review_Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Expertise Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Control Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Rater Reliability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Review Quality Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Liaison</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>States the status of the External review panel from a set of values</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Test__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Test</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Expert_Review_Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>External Review Panel</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Peer Review Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Review Panel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback_questions__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Application_Feedback__c</fullName>
        <label>Application Feedback ID</label>
        <referenceTo>Application_Feedback__c</referenceTo>
        <relationshipLabel>Feedback Questions</relationshipLabel>
        <relationshipName>Feedback_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments_Required__c</fullName>
        <label>Comments Required</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Rater Reliability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Review Quality Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Control Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Liaison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Expertise Reviewer</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Score_Value__c</fullName>
        <formula>IF(( ISPICKVAL( Score_yes_no__c,&quot;Yes&quot; ))
   , 100,IF(( ISPICKVAL( Score_yes_no__c,&quot;NO&quot;))
      ,0,IF(( ISPICKVAL( Score_yes_no__c,&quot;N/A&quot;))
       ,0,IF(( ISPICKVAL( Score_two_factor__c,&quot;Satisfactory&quot;))
         ,100,IF(( ISPICKVAL( Score_two_factor__c,&quot;Unsatisfactory&quot;))
          ,0,IF(( ISPICKVAL( Score_two_factor__c,&quot;N/A&quot;))
           ,0,IF(( ISPICKVAL( Score_four_factor__c,&quot;Exceeds&quot;)) 

,100,IF(( ISPICKVAL( Score_four_factor__c,&quot;Meets&quot;))
,66.66,IF(( ISPICKVAL( Score_four_factor__c,&quot;Partially Meets&quot;))
,33.33,IF(( ISPICKVAL( Score_four_factor__c,&quot;Does Not Meet&quot;))
,0,If((ISPICKVAL(Scoring_Method__c,&quot;None&quot;)),1,Score_number__c )


))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rating</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_four_factor__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Exceeds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Meets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_number__c</fullName>
        <label>Rating</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_two_factor__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Satisfactory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_yes_no__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scoring_Method__c</fullName>
        <label>Scoring Method</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number (1-100)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Factor Option</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Four Factor Option</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weighted_Score__c</fullName>
        <formula>( Score_Value__c * Weight__c)/100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Weighted Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Feedback Question</label>
    <nameField>
        <displayFormat>FQ-{0000}</displayFormat>
        <label>Feedback questions id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Paneling__c.object
<CustomObject>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeedqueCV.cls
public class FeedqueCV {
    //Get the Standard Controller
    private ApexPages.StandardController std;
     
    // the associated FeedqueList
    public List<Feedback_questions__c> FeedqueList;
    public string profileName{get;set;}
    public string contactID{get;set;}
    public string userID{get;set;}
    public list<Feedback_questions__c> fqsToReturn = new list<Feedback_questions__c>();    
    
      
    //Init the Class
    public FeedqueCV(ApexPages.StandardController stdCtrl)
    {
        if (!Test.isRunningTest())
        {
            stdCtrl.addFields(new List<String>{'Expert_Review_Panel__r.Reviewer__c','Expert_Review_Panel__r.Panel__r.Panel_Status__c','Expert_Review_Panel__r.Role__c'});
        }
        std=stdCtrl;
        Profile P = [Select ID, name From Profile where Id =: UserInfo.getProfileId()];
        User U = [Select ID, ContactID FROM User where ID = :UserInfo.getuserID()];
        userID = U.ID;
        profileName = P.Name;
  //    if(u.contactID != NULL)
        contactID = U.contactID;
    }
     
    //Get the application feedback record 
    public Application_Feedback__c getApplicationFeedback()
    {
     return (Application_Feedback__c) std.getRecord();
    }
 
    //Code to update the feedback questions
    private boolean updateFeedqueList()
    {
        boolean result=true;
        //Can't update if there is nothing in the list
        if (null!=fqsToReturn)
        {

            //try catch block to update the feedback questions
              try
              {
                update fqsToReturn;
              }
              catch (Exception e)
              {
                  //if it fails, let's nicely display the message
                 String msg=e.getMessage();
                 integer pos;
                  
                 // if its field validation, this will be added to the messages by default
                 if (-1==(pos=msg.indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION, ')))
                 {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg));
                 }
                  
                 result=false;
              }
         }
            
         return result;
    }
     
     
    public PageReference save()
    {
        system.debug('FeedqueList = '+fqsToReturn);
        for(Feedback_questions__c fq : fqsToReturn){
            system.debug('Score Number..............@@@@@@@@' +fq.Score_number__c);
            if(fq.Score_number__c > 100 || fq.Score_number__c <1){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Score cannot be less than 1 and  greater than 100'));
                return null;
            }
        }
      getApplicationFeedback().Status__c = 'In - Progress';
      //Assume it works
      Boolean result=true;
      //Send it back to detail page
      PageReference pr=Page.FeedBackQuestionDetail;
      //get the application feedback ID
      if (null!=getApplicationFeedback().id)
      {
        //first, update the feedback questions
        result=updateFeedqueList();
      }
      else
      {
         
        pr.setRedirect(true);
      }
      
      if (result)
      {
        // call standard save, but don't capture the return value which will redirect to view page
        //std.save();
        update getApplicationFeedback();
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Changes saved'));
      }
      pr.getParameters().put('id', getApplicationFeedback().id);
      pr.setRedirect(true);
      return pr;
      
        
    }
  

    
    public PageReference ReturnToRework()
    {
        getApplicationFeedback().Status__c = 'Returned for Rework';
        if(profileName =='Expert Reviewers'){
            getApplicationFeedback().Accepted_by_Panel_Coordinator__c = False;
        }
        else{
            getApplicationFeedback().Accepted_by_Staff_Liaison__c= False;
        }
        //Assume it works
        Boolean result=true;
        //Send it back to detail page
        PageReference pr=Page.FeedBackQuestionDetail;
        //get the application feedback ID
        if (null!=getApplicationFeedback().id)
        {
           //first, update the feedback questions
           result=updateFeedqueList();
        }
        else
        {          
           pr.setRedirect(true);
        }
      
        if(result)
        {
            // call standard save, but don't capture the return value which will redirect to view page
            //std.save();
            update getApplicationFeedback();
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Changes saved'));
        }
        pr.getParameters().put('id', getApplicationFeedback().id);
      
        return pr;
    }
 
    public PageReference submit()
    {
        getApplicationFeedback().Status__c = 'Submitted';
        getApplicationFeedback().Accepted_by_Panel_Coordinator__c=False;
        
        //Assume it works
        Boolean result=true;
        //Send it back to detail page
        PageReference pr=Page.FeedBackQuestionDetail;
        //get the application feedback ID
        if (null!=getApplicationFeedback().id)
        {
            //first, update the feedback questions
            result=updateFeedqueList();
        }
        else
        {
             pr.setRedirect(true);
        }
          
        if(result)
        {
             // call standard save, but don't capture the return value which will redirect to view page
             System.debug('Standard Controller' +std);
             update getApplicationFeedback();
             //std.save();
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Changes saved'));
        }
        pr.getParameters().put('id', getApplicationFeedback().id);
      
        return pr;
    }
     
   public List<Feedback_questions__c> getFeedqueList()
   {   
       
       if ( (null!=getApplicationFeedback().id) && (FeedqueList == null) )
       {
           id someVar = getApplicationFeedback().ID;           
            //get the list of feedback questions
            // FeedqueList = [SELECT Question__c,Name__c,Comments_Required__c,Active__c,Answer__c,Scoring_Method__c,Score_number__c,Score_yes_no__c,Score_two_factor__c,Score_four_factor__c,Score_Value__c,Weighted_Score__c, id from Feedback_questions__c where (Application_Feedback__c = :getApplicationFeedback().ID) ORDER BY Name__c];
         FeedqueList = [SELECT Question__c,Name__c,Comments_Required__c,Active__c,Answer__c,Scoring_Method__c,Score_number__c,Score_yes_no__c,Score_two_factor__c,Score_four_factor__c,Score_Value__c,
                                Weighted_Score__c, id, Roles__c,  CreatedDate
                        from Feedback_questions__c
                        where Application_Feedback__c = :someVar order by Name__c];
         if (Test.isRunningTest())
         {
             return FeedqueList;
         }
         for(Feedback_questions__c fq: FeedqueList){
            if(fq.Roles__c!=null && fq.Roles__c!='' && getApplicationFeedback().Expert_Review_Panel__r.Role__c!=null){
                if(fq.Roles__c.contains(getApplicationFeedback().Expert_Review_Panel__r.Role__c)){
                    system.debug('fq.Score_Number__c = '+fq.Score_Number__c);
                    fqsToReturn.add(fq);
                }
            }
         }              
       
       }
                           
       return fqsToReturn;
    }
}