src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Applicant_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant/User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Due_Date__c</fullName>
        <description>This field replaces the Editable &quot;Application Due Date&quot; field. 
This date is same as the NOFA Application Due Date. Use this field for List views and Reports.</description>
        <formula>NOFA_RFP__r.Applications_due_date__c</formula>
        <label>Application Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Feedback_Summary__c</fullName>
        <label>Application Feedback Summary</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Authorized_Representative__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Used for Notification of Intent to Apply section of the Application.</description>
        <label>Authorized Representative</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments</description>
        <inlineHelpText>Comments</inlineHelpText>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <formula>NOFA_RFP__r.Corporate_Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corporate Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Received__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_Fiscal_Yr__c</fullName>
        <formula>TEXT( NOFA_RFP__r.Fiscal_Yr__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFO Fiscal Yr</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA_RFP__r.NOFA_name__c</formula>
        <label>NOFO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP ID</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 2) OR (3 AND (4 OR 5))</booleanFilter>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>notEqual</operation>
                <value>State Commission Profile</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value>Yes, No</value>
            </filterItems>
            <filterItems>
                <field>NOFA__c.Allow_Prime_Applicants_and_Sub_Applicant__c</field>
                <operation>equals</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Office_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Office Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <label>Submitted By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the epert reviewer application</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - SAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Application_Due_Date__c</fullName>
        <formula>Parent_NOFA__r.Applications_due_date__c</formula>
        <label>Application Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Program Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intent_to_Apply_Due_Date__c</fullName>
        <label>Intent to Apply Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NOFA_name__c</fullName>
        <label>NOFO Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>NOFO Status</label>
        <picklist>
            <picklistValues>
                <fullName>Setup in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Director_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director ID</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Program</fullName>
        <active>true</active>
        <label>Program</label>
    </recordTypes>
</CustomObject>

src/classes/CustomSendEmailController.cls
public with sharing class CustomSendEmailController {
        public String subject { get; set; }    
        public String body { get; set; }  
        public string toAddresses {get;set;}
        public string toCCAddresses {get;set;}
        public User auser {get;set;}
        public Id appId {get;set;}
        public Application3__c app{get;set;}
        public String status{get;set;}
        
        public CustomSendEmailController (){
            String tmpName = ApexPages.CurrentPage().getParameters().get('tmpName');
            toAddresses = ApexPages.CurrentPage().getParameters().get('toAddresses');
            status = ApexPages.CurrentPage().getParameters().get('status');
            appId = ApexPages.CurrentPage().getParameters().get('appId');
            //Application3__c app;
            system.debug('appId = '+appId);
            if(appId!=null){
             app = [Select Id,Name,Submitted_By__c,CreatedById,CreatedBy.Name,Grantee_Status__c,Status__c,
                    Authorized_Representative__c,Authorized_Representative__r.Name,Authorized_Representative__r.Title,Comments__c,
                    Applicant_User__c,Applicant_User__r.Name,Applicant_User__r.Street,Applicant_User__r.City,Applicant_User__r.LastName,
                    Application_ID__c,Nofa_Rfp__r.NOFA_name__c,Nofa_Rfp__c,NOFA_Fiscal_Yr__c,Nofa_Rfp__r.Corporate_Program__r.Director_ID__r.Name,
                    Nofa_Rfp__r.Corporate_Program__r.Director_ID__r.Title,Nofa_Rfp__r.Corporate_Program__r.Name,Application_Due_Date__c,Date_Received__c,
                    Nofa_Rfp__r.Intent_to_Apply_Due_Date__c,Program_Office_Director__r.Name,Program_Office_Director__r.Title,Application_Feedback_Summary__c,
                    Program_Office_Director__c from Application3__c where Id = :appId];
            }
            system.debug('tmpName = '+tmpName);
            EmailTemplate template = [Select Id,Name,Body,Subject from EmailTemplate where DeveloperName = :tmpName];
            subject = template.Subject;            
            body = template.Body; 
            system.debug('createdById = '+app.CreatedById);
            User createdBy = [Select Id,Name from User where Id = :app.CreatedById];  
            system.debug('after user query = '+createdBy);
            if(body.contains('{!User.Name}'))
                body = (null == app.CreatedById) ? body : body.replace('{!User.Name}',CreatedBy.Name); 
            if(body.contains('{!Application3__c.Comments__c}'))
                body = (null == app.Comments__c) ? body.replace('{!Application3__c.Comments__c}','') : body.replace('{!Application3__c.Comments__c}',app.Comments__c);  
            
            if(body.contains('{!Application3__c.Submitted_By__c}'))
                body = (null == app.Submitted_By__c) ? body.replace('{!Application3__c.Submitted_By__c}','') : body.replace('{!Application3__c.Submitted_By__c}',app.Submitted_By__c);  
                
            if(body.contains('{!NOFA__c.CreatedBy}')){                          
                body = (null == app.CreatedById) ? body : body.replace('{!NOFA__c.CreatedBy}',CreatedBy.Name);   
            }
            
            
            if(body.contains('{Current Date}')){
                system.debug('got here');
                body = (null == Date.today()) ? body : body.replace('{Current Date}',String.valueOf(Date.today()));
            }              
            if(body.contains('{!Application3__c.Authorized_Representative__c}')) 
                body = (null == app.Authorized_Representative__c) ? body.replace('{!Application3__c.Authorized_Representative__c}',' ') : body.replace('{!Application3__c.Authorized_Representative__c}',app.Authorized_Representative__r.Name);
            if(body.contains('{!Application3__c.Application_Feedback_Summary__c}'))
            	body = (null == app.Application_Feedback_Summary__c) ? body.replace('{!Application3__c.Application_Feedback_Summary__c}',' ') : body.replace('{!Application3__c.Application_Feedback_Summary__c}',app.Application_Feedback_Summary__c);
            	
            
            	             
            if(body.contains('{Authorized Representative Name}'))
                body = (null == app.Authorized_Representative__c) ? body.replace('{Authorized Representative Name}',' ') : body.replace('{Authorized Representative Name}',app.Authorized_Representative__r.Name);
            system.debug(' title = '+app.Authorized_Representative__r.Title);   
            if(body.contains('{Authorized Representative TITLE}'))
                body = (null == app.Authorized_Representative__r.Title) ? body.replace('{Authorized Representative TITLE}','') : body.replace('{Authorized Representative TITLE}',app.Authorized_Representative__r.Title);
            if(body.contains('{Legal Applicant Name}'))
                body = (null == app.Applicant_User__c) ? body.replace('{Legal Applicant Name}','') : body.replace('{Legal Applicant Name}',app.Applicant_User__r.Name);
            if(body.contains('{Legal Applicant Address}'))
                body = (null == app.Applicant_User__r.Street) ? body.replace('{Legal Applicant Address}','') : body.replace('{Legal Applicant Address}',app.Applicant_User__r.Street+' '+app.Applicant_User__r.City);
            if(body.contains('{Prefix} {LastName}'))
                body = (null == app.Applicant_User__c) ? body.replace('{Prefix} {LastName}','') : body.replace('{Prefix} {LastName}',app.Applicant_User__r.LastName);
            if(body.contains('{Application ID}'))
                body = (null == app.Application_ID__c) ? body.replace(' {Application ID}','') : body.replace(' {Application ID}',app.Application_ID__c);
            if(body.contains('{NOFA Name}'))
                body = (null == app.Nofa_Rfp__c) ? body.replace('{NOFA Name}','') : body.replace('{NOFA Name}',app.Nofa_Rfp__r.NOFA_name__c);
            if(body.contains('{Date of Applicant’s correspondence}'))
                body = (null == app.Date_Received__c) ? body.replace('{Date of Applicant’s correspondence}','') : body.replace('{Date of Applicant’s correspondence}',String.valueof(app.Date_Received__c));
            //if(body.contains('*Date of original Compliance letter*'))
            //  body = (null == app.Nofa_Rfp__c) ? body : body.replace('*Date of original Compliance letter*',app.Nofa_Rfp__r.NOFA_name__c);
            if(body.contains('{Fiscal year}'))
                body = (null == app.NOFA_Fiscal_Yr__c) ? body.replace('{Fiscal year}','') : body.replace('{Fiscal year}',app.NOFA_Fiscal_Yr__c);
            if(body.contains('{CNCS Program Director Name}'))
                body = (null == app.Nofa_Rfp__r.Corporate_Program__r.Director_ID__r.Name) ? body.replace('{CNCS Program Director Name}','') : body.replace('{CNCS Program Director Name}',app.Nofa_Rfp__r.Corporate_Program__r.Director_ID__r.Name);
            if(body.contains('{CNCS Program Director Title}'))
                body = (null == app.Nofa_Rfp__r.Corporate_Program__r.Director_ID__r.Title) ? body.replace('{CNCS Program Director Title}','') : body.replace('{CNCS Program Director Title}',app.Nofa_Rfp__r.Corporate_Program__r.Director_ID__r.Title);
            if(body.contains('{CNCS Program Name}'))
                body = (null == app.Nofa_Rfp__r.Corporate_Program__r.Name) ? body.replace('{CNCS Program Name}','') : body.replace('{CNCS Program Name}',app.Nofa_Rfp__r.Corporate_Program__r.Name); 
                
            if(body.contains('{Application Due Date}'))
                body = (null == app.Application_Due_Date__c) ? body.replace('{Application Due Date}','') : body.replace('{Application Due Date}',String.valueOf(app.Application_Due_Date__c));
            if(body.contains('{Application Submission Date}'))
                body = (null == app.Date_Received__c) ? body.replace('{Application Submission Date}','') : body.replace('{Application Submission Date}',String.valueOf(app.Date_Received__c));
            if(body.contains('{Intent Due Date from Notice}'))
                body = (null == app.Nofa_Rfp__r.Intent_to_Apply_Due_Date__c) ? body.replace('{Intent Due Date from Notice}','') : body.replace('{Intent Due Date from Notice}',string.valueOf(app.Nofa_Rfp__r.Intent_to_Apply_Due_Date__c));
            if(body.contains('{Director of OGPO Name}'))
                body = (null == app.Program_Office_Director__r.Name) ? body.replace('{Director of OGPO Name}','') : body.replace('{Director of OGPO Name}',app.Program_Office_Director__r.Name);
            if(body.contains('{Director of OGPO TITLE}'))
                body = (null == app.Program_Office_Director__r.Title) ? body.replace('{Director of OGPO TITLE}','') : body.replace('{Director of OGPO TITLE}',app.Program_Office_Director__r.Title);
            if(body.contains('{Office Title of OGPO}'))
                body = (null == app.Program_Office_Director__c) ? body.replace('{Office Title of OGPO}','') : body.replace('{Office Title of OGPO}',app.Program_Office_Director__c);
             
                
            
        }
        
        public PageReference sendEmails(){
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
            list<String> addressesToSend = new list<String>();
            list<String> addressesToCC = new list<String>();
            if(toAddresses!=null){
                addressesToSend.add(toAddresses);
            }
            if(toCCAddresses != null && toCCAddresses !=''){                
                addressesToCC = toCCAddresses.split(';');
            }            
            email.setSubject( subject );
            email.setToAddresses( addressesToSend );
            email.setPlainTextBody( body );      
            if(addressesToCC.size()>0){             
                email.setCcAddresses(addressesToCC);
            }                            
           if(status!=null&&status!=''){      
                /*app.Grantee_Status__c = status;
                app.Status__c = status;      
                Database.Saveresult appUpdate = Database.update(app);*/
                //update app;     
                
                    try{
                        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});    
                        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Successfully sent email(s) to contacts'));
                        if(r[0].isSuccess()){
                        	app.Grantee_Status__c = status;
                			app.Status__c = status;      
                			Database.Saveresult appUpdate = Database.update(app);
                			if(!appUpdate.isSuccess()){                        
                   			 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Unable to update Concept Paper/Application, please contact your admin'));
                    	     return null;
                			}
                        }                                              
                    } catch(Exception e){               
                         ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Unable to send email, please contact your admin'));
                         return null;
                    }                        
            }else{
                try{
                    Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email}); 
                    Task newTask = new Task();
                    newTask.OwnerId = userInfo.getUserId();
                    newTask.Subject = subject;
                    newTask.Description = body;
                    newTask.ActivityDate = date.today();
                    newTask.Status = 'Completed';
                    newTask.Priority = 'Normal';
                    newTask.whatId = app.Id;
                    insert newTask;
                }catch(Exception e){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Unable to send email, please contact your admin'));
                    return null;
                }
                
            }   
            PageReference pg = new PageReference('/'+appId);
            pg.setRedirect(true);
            return pg;
        }
        
        public PageReference cancel(){
             PageReference pg = new PageReference('/'+appId);
             system.debug('appId = '+appId);
             pg.setRedirect(true);
             return pg;
        }
}