src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_w_Allowance__c</fullName>
        <description>Field to aggregate the total &quot;Requested with Allowance&quot; from all Slots for an Application. Field populated from a Trigger.</description>
        <label>Requested w/ Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Slot__c.object
<CustomObject>
    <fields>
        <fullName>Aggregate_Recommendation_w_Allowance__c</fullName>
        <label>Aggregate Recommendation w/Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Aggregate_Recommendation_w_o_Allowance__c</fullName>
        <label>Aggregate Recommendation w/o Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApplicationId__c</fullName>
        <formula>casesafeid(Budget_Application__r.Parent__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ApplicationId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approved_WithOut_Allowance__c</fullName>
        <label>Approved WithOut Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved_With_Allowance__c</fullName>
        <label>Approved With Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BudgetLine</label>
        <referenceTo>cb3__BudgetLine__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots_BdgLn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Application</label>
        <referenceTo>cb3__Budget__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots_BA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_End_Date__c</fullName>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommended_w_Allowance__c</fullName>
        <label>Recommended w/ Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recommended_w_o_Allowance__c</fullName>
        <label>Recommended w/o Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_w_Allowance__c</fullName>
        <label>Requested w/ Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_w_o_Allowance__c</fullName>
        <label>Requested w/o Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Slot_Type__c</fullName>
        <label>Slot Type</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Slot</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Slot Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlotInformationWithAppCntrl.cls
public class SlotInformationWithAppCntrl{

    public ApexPages.StandardController stdcontroller;
    public Application3__c app{get;set;}
    public List<Slot__c> lstSlot{get;set;}
    
    public SlotInformationWithAppCntrl(){
          System.debug('***SlotInformationWithApp constructor***');
    
    }
    
    public SlotInformationWithAppCntrl(ApexPages.StandardController p_controller){
    try{
      this.stdcontroller= p_controller;
      this.app= (Application3__c )stdController.getrecord();
      System.debug('***appid***'+app.id);
      String strAppId='';
      strAppId=(app!=null )? app.id:'';
      readSlotInformation(strAppId);
      }
      catch(Exception exc){
            System.debug('***error in SlotInformationWithAppCntrl constructor***'+exc.getMessage());
      }   
      
    }
    
    
    
    public void readSlotInformation(String p_strAppId){
         System.debug('***p_strAppId***'+p_strAppId);
         if(p_strAppId!=null && p_strAppId!=''){
            lstSlot =[SELECT ID,NAME,Slot_Type__c,Award__c,Prime_Application__c,ApplicationId__c,Application__c,BudgetLine__c,
                             Budget_Application__c,Requested_w_Allowance__c,Requested_w_o_Allowance__c,
                             Recommended_w_Allowance__c,Recommended_w_o_Allowance__c,
                             Aggregate_Recommendation_w_Allowance__c,Aggregate_Recommendation_w_o_Allowance__c,
                             /* Enrollment_Start_Date__c,Enrollment_End_Date__c  */ //commented as per Khalid bugs list doc- dated 09272016
                             Approved_With_Allowance__c,Approved_WithOut_Allowance__c 
                      FROM SLOT__c  Where   BudgetLine__c!=null and Application__c= :p_strAppId];  //Where ApplicationId__c= :p_strAppId
         }         
         System.debug('*** lstSlot ***'+lstSlot );    
   
    }
    
    public PageReference updateSlotRecs(){
        try{
           System.debug('*** lstSlot ***'+lstSlot );
           if(lstSlot !=null && lstSlot.size()>0){
             Update lstSlot ;
           }
        }
        catch(Exception exc){
            System.debug('***lstSlot ***'+exc );
             //System.debug('***excMsg***' +exc.getMesssage());
        
        }
        return null;
    
    }
    
    public void processBdgLnRecsForUpdate(){
    List<cb3__BudgetLine__c> lstBdgLin = new List<cb3__BudgetLine__c>();
        
      /* for(SLOT__c   itrSlot :lstSlot ){
         itrSlot.  
       
       }*/
    
    }
  

}