src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application_ID__c</fullName>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Application ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Competitive_or_Formula__c</fullName>
        <description>This field is for Sub-Applications - Competitive or Formula.</description>
        <label>Competitive or Formula</label>
        <picklist>
            <picklistValues>
                <fullName>Competitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formula</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Application Status - CNCS Only</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waitlisted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Prime Award Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>CNCS_Status__c</fullName>
        <label>Application Status</label>
        <picklist>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Held for Formula</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepting Sub-Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed to Sub-Applicants</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competitive_or_Formula__c</fullName>
        <label>Competitive or Formula</label>
        <picklist>
            <picklistValues>
                <fullName>Competitive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formula</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFO_Name__c</fullName>
        <formula>NOFO_RFP__r.NOFA_name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFO Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>contains</operation>
                <value>Continuation, New &amp; Continuation</value>
            </filterItems>
            <filterItems>
                <field>$Source.CNCS_Corporate_Program__c</field>
                <operation>equals</operation>
                <valueField>NOFA__c.CNCS_Corporate_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>equals</operation>
                <value>New, New &amp; Continuation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application_Id_w_link__c</fullName>
        <formula>IF( $Profile.Name  = &apos;State Commission Profile&apos;, HYPERLINK(&quot;/statecommission/&quot;&amp;Id,  Prime_Application_ID_Number__c , &quot; &quot;), IF( $Profile.Name  = &apos;Applicant&apos;  || $Profile.Name  = &apos;Grantee Admin&apos;, HYPERLINK(&quot;/granteeportal/&quot;&amp;Id,Prime_Application_ID_Number__c , &quot; &quot;), HYPERLINK(&quot;/&quot;&amp;Id,  Prime_Application_ID_Number__c , &quot; &quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Prime Application Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CopyHeldFormulaApps.cls
public with sharing class CopyHeldFormulaApps {
    
    public String competetiveid;
    public string nofaId;
    //public string selectedPrimeAppId{get;set;}
    public List<cPrimeApplication> primeAppList {get; set;}
    
    public CopyHeldFormulaApps(ApexPages.StandardController controller){
        competetiveid=ApexPages.currentPage().getParameters().get('id');
        nofaId = ApexPages.currentPage().getParameters().get('nofaId');
    }
    
    public list<cPrimeApplication> getprimeAppsFormula(){
        if(primeAppList==null){
            primeAppList = new list<cPrimeApplication>();
            for(Prime_Application__c p: [Select Id,Name,Prime_Application_Id_w_link__c,NOFO_RFP__c,Project_Name__c,CNCS_Status__c,Competitive_or_Formula__c,NOFO_Name__c from Prime_Application__c 
                                                                                    where Competitive_or_Formula__c = 'Formula' and NOFO_RFP__c = :nofaId]){
                primeAppList.add(new cPrimeApplication(p));
            }                       
        }
        return primeAppList;        
    } 
    
    public PageReference copy(){ 
        List<Prime_Application__c> selectedPrimeApp = new List<Prime_Application__c>();
        for(cPrimeApplication cPc: getprimeAppsFormula()) {
            if(cPc.selected == true) {
                selectedPrimeApp.add(cPc.pc);
            }
        }
        if(selectedPrimeApp.size()>1){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Please Select only one Prime Application'));
            return null;
        }else if(selectedPrimeApp.size()==1){
            list<Application3__c> subApps = new list<Application3__c>([Select Id, Name, Application_ID__c From Application3__c where Prime_Application__c = :competetiveid and (Grantee_Status__c = 'Held for Formula' or Status__c = 'Held for Formula')]);
            if(subApps.size()>0){
                for(Application3__c a: subApps){
                    a.Prime_Application__c = selectedPrimeApp[0].Id;
                    //a.Status__c = 'In Progress';
                    //a.Grantee_Status__c  = 'In Progress';
                }
                update subApps;
            }
            PageReference pg = new PageReference('/apex/PrimeApplicationDetail?id='+selectedPrimeApp[0].Id);
            pg.setRedirect(true);
            return pg;
        }else if(selectedPrimeApp.size()==0){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Please Select one Prime Application'));
            return null;
        }
        
        return null;
        
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference('/apex/PrimeApplicationDetail?id='+competetiveid);
        pg.setRedirect(true);
        return pg;
    }
    
    public class cPrimeApplication {
        public Prime_Application__c pc {get; set;}
        public Boolean selected {get; set;}

        public cPrimeApplication(Prime_Application__c p) {
            pc = p;
            selected = false;
        }

    }
    

}