src/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <description>Populates the Master Award name from the Master Award related list.</description>
        <label>Master Award</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Sub-Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>Application__r.Organization__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Award</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Org_Id__c</fullName>
        <formula>Project_Name__r.Organization__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Org Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project ID</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MasterAwardHelper.cls
public without sharing class MasterAwardHelper {
    
    /*public static void shareMasterAwardWithStateCommission(list<Master_Award__c> newRecs){
            Profile p = [Select Id,Name from Profile where Name = 'System Administrator'];
            if(userInfo.getProfileId()!=p.Id){
        
                set<Id> primeAppIds = new set<Id>();
                set<Id> appIds = new set<Id>();
                for(Master_Award__c a:newRecs){
                    if(a.Prime_Application__c!=null){
                        primeAppIds.add(a.Prime_Application__c);                    
                    }
                    if(a.Application__c!=null){
                        appIds.add(a.Application__c);
                    }
                }
                
                if(primeAppIds.size()>0){
                    Map<Id,Application3__c> apps = new Map<Id,Application3__c>([Select Id,Name,Organization__c from Application3__c where id in :appIds]);
                    Map<Id,Prime_Application__c> primeApps = new Map<Id,Prime_Application__c>([Select Id,createdById,Project_Name__r.Organization__c from Prime_Application__c where id in :primeAppids]);
                    list<Master_Award__Share> awShares = new list<Master_Award__Share>();
                    
                    if(primeApps.size()>0){
                        for(Master_Award__c a:newRecs){
                            if(apps.get(a.Application__c).Organization__c != null && apps.get(a.Application__c).Organization__c == primeApps.get(a.Prime_Application__c).Project_Name__r.Organization__c){
                                Master_Award__Share aShare = new Master_Award__Share();
                                aShare.ParentId = a.Id;
                                aShare.userorgroupId = primeApps.get(a.Prime_Application__c).createdById;
                                aShare.AccessLevel = 'Edit';
                                awShares.add(aShare);
                            
                            }
                        }
                    }
                    if(awShares.size()>0){
                        insert awShares;
                    }
                }
            }
        
    }*/
    
    public static void shareMasterAwards(list<Master_Award__c> newMasterAwards){
        
        
        //Profile p = [Select Id,Name from Profile where Name = 'System Administrator'];
        //if(userInfo.getProfileId()!=p.Id){
            set<Id> orgIds = new set<Id>();
            set<Id> conIds = new set<Id>();
            map<Id,Id> accIdtoAppId = new map<Id,Id>();
            map<Id,Id> conNametoAccId = new map<Id,Id>();
            list<Master_Award__Share> maShares = new list<Master_Award__Share>();
            for(Master_Award__c a: newMasterAwards){
                if(a.Org_Id__c != null){
                    orgIds.add(a.Org_Id__c);
                    accIdtoAppId.put(a.Org_Id__c,a.Id); 
                }   
            }
            if(orgIds.size()>0){
                list<Account> accs = new list<Account>([Select (Select Id, contact.accountid,LastName, FirstName, Name From Contacts) From Account a where Id in :orgIds]);
                if(accs.size()>0){
                    for(Account a: accs){
                        if(a.Contacts.size()>0){
                            for(Contact c: a.Contacts){
                                conIds.add(c.Id);
                                conNametoAccId.put(c.Id,c.AccountId);
                            }
                        }
                    }
                }
                if(conIds.size()>0){
                    set<Id> roleIds = new set<Id>();
                    list<User> users = new list<User>([Select Id,FirstName,LastName,Name,userRoleId,contactId,isactive from User where contactId in :conIds]);
                    if(users.size()>0){
                        for(User u: users){                     
                          if(u.isActive && u.Id!=userInfo.getUserId() && accIdtoAppId.get(conNametoAccId.get(u.contactid))!=null){        
                            Master_Award__Share aShare = new Master_Award__Share();
                            aShare.ParentId = accIdtoAppId.get(conNametoAccId.get(u.contactId));
                            aShare.userorgroupId = u.Id;
                            aShare.AccessLevel = 'Edit';
                            maShares.add(aShare); 
                          }                         
                        }
                    }                   
                }
                if(maShares.size()>0){
                    insert maShares;
                }
                
                
            }
        //}
    
    
    }

}