src/objects/Application_Feedback__c.object
<CustomObject>
    <label>Application Feedback</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Application Feedback ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Expert_Reviewer_Form__c.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>External Reviewer Form</label>
    <nameField>
        <displayFormat>Form - {0000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Reviewer Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Reviewer Form</label>
        <referenceTo>Expert_Reviewer_Form__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <formula>Setup_Questionnaire__r.Question_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback_questions__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Answer__c</fullName>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Application_Feedback__c</fullName>
        <label>Application Feedback ID</label>
        <referenceTo>Application_Feedback__c</referenceTo>
        <relationshipLabel>Feedback Questions</relationshipLabel>
        <relationshipName>Feedback_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments_Required__c</fullName>
        <label>Comments Required</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Score_Value__c</fullName>
        <formula>IF(( ISPICKVAL( Score_yes_no__c,&quot;Yes&quot; ))
   , 100,IF(( ISPICKVAL( Score_yes_no__c,&quot;NO&quot;))
      ,0,IF(( ISPICKVAL( Score_yes_no__c,&quot;N/A&quot;))
       ,0,IF(( ISPICKVAL( Score_two_factor__c,&quot;Satisfactory&quot;))
         ,100,IF(( ISPICKVAL( Score_two_factor__c,&quot;Unsatisfactory&quot;))
          ,0,IF(( ISPICKVAL( Score_two_factor__c,&quot;N/A&quot;))
           ,0,IF(( ISPICKVAL( Score_four_factor__c,&quot;Exceeds&quot;)) 

,100,IF(( ISPICKVAL( Score_four_factor__c,&quot;Meets&quot;))
,66.66,IF(( ISPICKVAL( Score_four_factor__c,&quot;Partially Meets&quot;))
,33.33,IF(( ISPICKVAL( Score_four_factor__c,&quot;Does Not Meet&quot;))
,0,If((ISPICKVAL(Scoring_Method__c,&quot;None&quot;)),1,Score_number__c )


))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rating</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_four_factor__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Exceeds</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partially Meets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Meet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_number__c</fullName>
        <label>Rating</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score_two_factor__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Satisfactory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unsatisfactory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_yes_no__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scoring_Method__c</fullName>
        <label>Scoring Method</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number (1-100)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Factor Option</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Four Factor Option</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weighted_Score__c</fullName>
        <formula>( Score_Value__c * Weight__c)/100</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Weighted Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Feedback Question</label>
    <nameField>
        <displayFormat>FQ-{0000}</displayFormat>
        <label>Feedback questions id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReviewerTraining.cls
public class ReviewerTraining{

     private ApexPages.StandardController std;
     
    // public List<Feedback__c> questions;
      public list<Feedback__c> questions = new list<Feedback__c>(); 
     
     public ReviewerTraining(ApexPages.StandardController stdCtrl){
         std=stdCtrl;
     }
     
     public Expert_Reviewer_Form__c getExpertReviewerFeedback(){
         return (Expert_Reviewer_Form__c) std.getRecord();
    }
    
    private boolean updateFeedbackList()
    {
        boolean result=true;
        //Can't update if there is nothing in the list
        if (null!=questions)
        {

            //try catch block to update the feedback questions
              try
              {
                update questions;
              }
              catch (Exception e)
              {
                  //if it fails, let's nicely display the message
                 String msg=e.getMessage();
                 integer pos;
                  
                 // if its field validation, this will be added to the messages by default
                 if (-1==(pos=msg.indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION, ')))
                 {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg));
                 }
                  
                 result=false;
              }
         }
            
         return result;
    }
    
    public PageReference save()
    {
     
      //Assume it works
      Boolean result=true;
      //Send it back to detail page
      PageReference pr=Page.FeedBackQuestionDetail;
      //get the application feedback ID
      if (null!=getExpertReviewerFeedback().id)
      {
        //first, update the feedback questions
        result=updateFeedbackList();
      }
      else
      {
         
        pr.setRedirect(true);
      }
      
      if (result)
      {
        // call standard save, but don't capture the return value which will redirect to view page
        //std.save();
        update getExpertReviewerFeedback();
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Changes saved'));
      }
      pr.getParameters().put('id', getExpertReviewerFeedback().id);
      pr.setRedirect(true);
      return pr;
      
        
    }
    
     public List<Feedback__c> getFeedbacklist(){   
       
       if ( (null!=getExpertReviewerFeedback().id) && (questions == null) ){
           id someVar = getExpertReviewerFeedback().ID;           
            //get the list of feedback questions
            // FeedqueList = [SELECT Question__c,Name__c,Comments_Required__c,Active__c,Answer__c,Scoring_Method__c,Score_number__c,Score_yes_no__c,Score_two_factor__c,Score_four_factor__c,Score_Value__c,Weighted_Score__c, id from Feedback_questions__c where (Application_Feedback__c = :getExpertReviewerFeedback().ID) ORDER BY Name__c];
         questions = [SELECT Answer_1__c,Question_1__c  from Feedback__c where Expert_Reviewer_Form__c = :someVar];
           
           
           }
           return questions;
        }
           
}