src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Arrival_Date__c</fullName>
        <description>Project Arrival Date for any Team Assignment</description>
        <label>Project Arrival Date</label>
        <summarizedField>Team_Assignment__c.Project_Arrival_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Team_Assignment__c.Project_Arrival_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Team_Assignment__c.Award__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reason_No_Longer_in_Use__c</fullName>
        <label>Reason No Longer in Use</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TeamName__c</fullName>
        <label>Team Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <formula>Unit__r.Unit_Name__c &amp; &quot; &quot; &amp;   TEXT(Team_Number__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Team Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Team_Number__c</fullName>
        <label>Team Number</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>58</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>59</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Type__c</fullName>
        <label>Team Type</label>
        <picklist>
            <picklistValues>
                <fullName>Firefighting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Composite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Cross</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Team</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>Team Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team_Assignment__c.object
<CustomObject>
    <description>Junction Object Between Award and Teams.</description>
    <fields>
        <fullName>Award__c</fullName>
        <description>MD relation with Award.</description>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Team Assignments</relationshipLabel>
        <relationshipName>Team_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Campus_Arrival_Date__c</fullName>
        <description>The date selected must be greater than or equal to the &quot;Project Departure Date&quot; but less than or equal to “Agreement End Date” on the award record.</description>
        <label>Campus Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campus_Departure_Date__c</fullName>
        <label>Campus Departure Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>No_Transition__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checking this checkbox nullifies the &quot;Campus Arrival Date&quot; field.</description>
        <label>No Transition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Number_of_Members__c</fullName>
        <label>Number of Members</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Arrival_Date__c</fullName>
        <description>Date selected must be greater than or equal to the “Campus Departure Date ” for the team.</description>
        <label>Project Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Departure_Date__c</fullName>
        <description>The date selected must be greater than or equal to the &quot;Start Date&quot; but less than or equal to “Agreement End Date” on the award record.</description>
        <label>Project Departure Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relation to Team object. .</description>
        <label>Team Record ID</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This Team cannot be associated to this award for the specified dates because the team is associated with a different award during that period.</errorMessage>
            <filterItems>
                <field>Team__c.Active1__c</field>
                <operation>equals</operation>
                <value>Yes</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>Team Assignments</relationshipLabel>
        <relationshipName>Team_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Team_Type__c</fullName>
        <label>Team Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire Fighting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Composite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red Cross</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Team Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>Team Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TeamAssignerrortriggertest.cls
@istest
public class  TeamAssignerrortriggertest
{

 static testMethod void testmethod1()
{
 Award__c testawd = UtilityClass.createAward();

 Insert testawd;
 
Team__c team = new Team__c();
team.Team_Number__c = '58'; 
team.Effective_Date__c = system.today()-50;
team.End_Date__c = system.today()+25;
team.Reason_No_Longer_in_Use__c = 'abcd';

//team.TeamName__c = 'xyz';
insert team;

Team_Assignment__c teamassign = new Team_Assignment__c();
teamassign.Award__c = testawd.id;
teamassign.Campus_Arrival_Date__c =  system.today();
teamassign.Campus_Departure_Date__c =  system.today();
teamassign.Project_Arrival_Date__c = system.today();
teamassign.Project_Departure_Date__c =  system.today();
teamassign.Number_of_Members__c = 4;
teamassign.Team_Type__c = 'Standard';
teamassign.Team_Name__c = team.id;
teamassign.No_Transition__c = true;


Team_Assignment__c teamassign1 = new Team_Assignment__c();
teamassign1.Award__c = testawd.id;
teamassign1.Campus_Arrival_Date__c =  system.today()+25;
teamassign1.Campus_Departure_Date__c =  system.today()+10;
teamassign1.Project_Arrival_Date__c = system.today()+14;
teamassign1.Project_Departure_Date__c =  system.today()+20;
teamassign1.Number_of_Members__c = 4;
teamassign1.Team_Type__c = 'Standard';
teamassign1.Team_Name__c = team.id;
teamassign1.No_Transition__c = true;

Team_Assignment__c teamassign2 = new Team_Assignment__c();
teamassign2.Award__c = testawd.id;
teamassign2.Campus_Arrival_Date__c =  system.today()-5;
teamassign2.Campus_Departure_Date__c =  system.today()-10;
teamassign2.Project_Arrival_Date__c = system.today()-9;
teamassign2.Project_Departure_Date__c =  system.today()-7;
teamassign2.Number_of_Members__c = 4;
teamassign2.Team_Type__c = 'Standard';
teamassign2.Team_Name__c = team.id;
teamassign2.No_Transition__c = true;

try
{
insert teamassign;
insert teamassign1;
insert teamassign2;
}
catch(exception e)
{
}
}
static testMethod void testmethod2()
{
 Award__c testawd = UtilityClass.createAward();

 Insert testawd;
 
Team__c team = new Team__c();
team.Team_Number__c = '59'; 
team.Effective_Date__c = system.today()-200;
team.End_Date__c = system.today()+100;
team.Reason_No_Longer_in_Use__c = 'abcd';

//team.TeamName__c = 'xyz';
insert team;

Team_Assignment__c teamassign = new Team_Assignment__c();
teamassign.Award__c = testawd.id;
teamassign.Campus_Arrival_Date__c =  system.today();
teamassign.Campus_Departure_Date__c =  system.today();
teamassign.Project_Arrival_Date__c = system.today();
teamassign.Project_Departure_Date__c =  system.today();
teamassign.Number_of_Members__c = 4;
teamassign.Team_Type__c = 'Standard';
teamassign.Team_Name__c = team.id;
teamassign.No_Transition__c = false;


Team_Assignment__c teamassign1 = new Team_Assignment__c();
teamassign1.Award__c = testawd.id;
teamassign1.Campus_Arrival_Date__c =  system.today()+3;
teamassign1.Campus_Departure_Date__c =  system.today()+10;
teamassign1.Project_Arrival_Date__c = system.today()+4;
teamassign1.Project_Departure_Date__c =  system.today()+7;
teamassign1.Number_of_Members__c = 4;
teamassign1.Team_Type__c = 'Standard';
teamassign1.Team_Name__c = team.id;
teamassign1.No_Transition__c = false;

Team_Assignment__c teamassign2 = new Team_Assignment__c();
teamassign2.Award__c = testawd.id;
teamassign2.Campus_Arrival_Date__c =  system.today()-5;
teamassign2.Campus_Departure_Date__c =  system.today()-10;
teamassign2.Project_Arrival_Date__c = system.today()-9;
teamassign2.Project_Departure_Date__c =  system.today()-7;
teamassign2.Number_of_Members__c = 4;
teamassign2.Team_Type__c = 'Standard';
teamassign2.Team_Name__c = team.id;
teamassign2.No_Transition__c = false;



try
{
insert teamassign;
insert teamassign1;
insert teamassign2;

}
catch(exception e)
{
}
}
 }