src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Agreement_Period_End_Date__c</fullName>
        <description>NOFO - Cash Grant= “No&quot; / &quot;Optional&quot;; 
Application - Program Type = &quot;Standard&quot;
New Date field created as the new requirements. 
US # 4783.</description>
        <label>Agreement Period End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Agreement_Period_Start_Date__c</fullName>
        <description>NOFO - Cash Grant= “No&quot; / &quot;Optional&quot;; 
Application - Program Type = &quot;Standard&quot;
New Date field created as the new requirements. 
US # 4783.</description>
        <label>Agreement Period Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Application_Type__c</fullName>
        <description>Type of Application coming from Application object.</description>
        <formula>if(ispickval(Application_ID__r.Type_of_Application__c, &quot;New&quot;), &quot;New&quot;, 
if(ispickval(Application_ID__r.Type_of_Application__c, &quot;Continuation&quot;), &quot;Continuation&quot;,
if(ispickval(Application_ID__r.Type_of_Application__c, &quot;Amendment&quot;), &quot;Amendment&quot;,&quot;None&quot;
) 
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <label>Grant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting GO Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PO Certification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Organization e-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO CSHR Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO De-Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO De-Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Arrival</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Award Identification Number</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <description>Field name was changed from &quot;Project End Date&quot; to &quot;Agreement Period End&quot; on 9.15.15_Krishna Yama.
Cash Grant Award = No; Program Type = Standard</description>
        <formula>Application_ID__r.Proposed_End_Date__c</formula>
        <label>Agreement Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <description>Field name was changed from &quot;Project Start Date&quot; to &quot;Agreement Period Start&quot; on 9.15.15_Krishna Yama.
Cash Grant Award = No; Program Type = Standard</description>
        <formula>Application_ID__r.Proposed_Start_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Agreement Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Amended_Awards__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Amended Awards</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Awarded_Awards__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Awarded Awards #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Continuation_Awards__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Continuation Awards #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Continuation_and_Awarded__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Continuation and Awarded #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_End_Date__c</fullName>
        <label>Project End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateAwardCountOnMasterAward.cls
public with sharing class UpdateAwardCountOnMasterAward{
	
    //Constructor
    public UpdateAwardCountOnMasterAward(){
    	
    }
    
    //Method to update Award Count on Master Award.
    public void updateAwardCount(list<Award__c> awardList, map<Id,Award__c> oldMap){
    	//set for MasterAward Ids.
    	set<Id> masterAwardIds = new set<Id>();
    	set<Id> ConAwardprojectIDs = new set<Id>();
    	set<Id> AwardedAwardProjectIDs = new set<Id>();
    	set<Id> ConAwardedAwardProjectIDs = new set<Id>();
    	
    	//map for Master Award and related Award records.
    	map<Id,Master_Award__c> masterAwardMap = new map<Id,Master_Award__c>();
    	map<Id,Project__c> ConAwardProjectMap = new map<Id,Project__c>();
    	map<Id,Project__c> AwardedAwardProjectMap = new map<Id,Project__c>();
    	map<Id,Project__c> ConAwardedProjectMap = new map<Id,Project__c>();
    	
    	//Check for award List Empty and Null.
    	if(awardList != null && !awardList.isEmpty()){
    		for(Award__c aw: awardList){
    			if((aw.Application_Type__c != null && aw.Application_Type__c.equalsIgnoreCase('Amendment')) || (oldMap != null && oldMap.get(aw.Id) != null && oldMap.get(aw.Id).Application_Type__c.equalsIgnoreCase('Amendment'))){
    				if(aw.Master_Award__c != null){
    					masterAwardIds.add(aw.Master_Award__c);
    				}
    			}//end of If for application type Amendment null check and value check.
    			if((aw.Application_Type__c != null && aw.Application_Type__c.equalsIgnoreCase('Continuation')) || (oldMap != null && oldMap.get(aw.Id) != null && oldMap.get(aw.Id).Application_Type__c.equalsIgnoreCase('Continuation'))){
    			   if(aw.Project__c !=null){
    			       ConAwardprojectIDs.add(aw.Project__c);
    				}
    			}//end of If for application type Continuation null check and value check.
    			if((aw.Grant_Status__c != null && aw.Grant_Status__c.equalsIgnoreCase('Awarded')) || (oldMap != null && oldMap.get(aw.Id) != null && oldMap.get(aw.Id).Grant_Status__c.equalsIgnoreCase('Awarded'))){
    			   if(aw.Project__c !=null){
    			       AwardedAwardProjectIDs.add(aw.Project__c);
    				}
    			}//end of If for Grant Status Awarded null check and value check.
    			if((aw.Grant_Status__c != null && aw.Application_Type__c != null && aw.Grant_Status__c.equalsIgnoreCase('Awarded') && aw.Application_Type__c.equalsIgnoreCase('Continuation')) || (oldMap != null && oldMap.get(aw.Id) != null && oldMap.get(aw.Id).Grant_Status__c.equalsIgnoreCase('Awarded') && oldMap.get(aw.Id).Application_Type__c.equalsIgnoreCase('Continuation'))){
    			   if(aw.Project__c !=null){
    			       ConAwardedAwardProjectIDs.add(aw.Project__c);
    				}
    			}//end of If for Grant Status Awarded and continuation null check and value check.
    		}//end of for Loop.
    		
    		//retrieve Master Award Records with related Award Records.
    		if(masterAwardIds != null && !masterAwardIds.isEmpty()){
    			masterAwardMap = new map<Id,Master_Award__c>([Select Id,Number_of_Amended_Awards__c,(Select Id,Application_Type__c from Award__r where Application_Type__c = 'Amendment') from Master_Award__c where ID IN:masterAwardIds]);
    		}
    		//retrieve Project Records with related Award Records for Continuation.
    		if(ConAwardprojectIDs != null && !ConAwardprojectIDs.isEmpty()){
    			ConAwardProjectMap = new map<Id,Project__c>([Select Id,Continuation_Awards__c,(Select Id,Application_Type__c from Award__r where Application_Type__c = 'Continuation') from Project__c where Id =: ConAwardprojectIDs]);
    		}
    		//retrieve Project Records with related Awarded Records.
    		if(AwardedAwardProjectIDs != null && !AwardedAwardProjectIDs.isEmpty()){
    			AwardedAwardProjectMap = new map<Id,Project__c>([Select Id,Awarded_Awards__c,Project_Start_Date__c,Project_End_Date__c,(Select Id,Grant_Status__c,Agreement_Period_End_Date__c,Agreement_Period_Start_Date__c from Award__r where Grant_Status__c = 'Awarded') from Project__c where Id =: AwardedAwardProjectIDs]);
    		}
    		//retrieve Project Records with related Awarded Records with Continuation.
    		if(ConAwardedAwardProjectIDs != null && !ConAwardedAwardProjectIDs.isEmpty()){
    			ConAwardedProjectMap = new map<Id,Project__c>([Select Id,Continuation_and_Awarded__c,(Select Id,Grant_Status__c,Application_Type__c from Award__r where (Grant_Status__c = 'Awarded' AND Application_Type__c = 'Continuation')) from Project__c where Id IN:ConAwardedAwardProjectIDs]);
    		}
    		//update count on Master Award 
    		if(masterAwardMap != null && !masterAwardMap.isEmpty()){
    			for(Master_Award__c maw : masterAwardMap.values()){
    				if(maw.Award__r != null && !maw.Award__r.isEmpty()){
    					maw.Number_of_Amended_Awards__c = maw.Award__r.size();
    				}else{
    					maw.Number_of_Amended_Awards__c = 0;
    				}
    			}
    			
    			update masterAwardMap.values();
    		}  
    		if(ConAwardProjectMap != null && !ConAwardProjectMap.isEmpty()){
    			for(Project__c prCon : ConAwardProjectMap.values()){
    				if(prCon.Award__r != null && !prCon.Award__r.isEmpty()){
    					prCon.Continuation_Awards__c = prCon.Award__r.size();
    				}else{
    					prCon.Continuation_Awards__c = 0;
    				}
    			}
    			update ConAwardProjectMap.values();
    		} 
    		if(ConAwardedProjectMap != null && !ConAwardedProjectMap.isEmpty()){
    			for(Project__c prConAwarded : ConAwardedProjectMap.values()){
    				if(prConAwarded.Award__r != null && !prConAwarded.Award__r.isEmpty()){
    					prConAwarded.Continuation_and_Awarded__c = prConAwarded.Award__r.size();
    				}else{
    					prConAwarded.Continuation_and_Awarded__c = 0;
    				}
    			}
    			update ConAwardedProjectMap.values();
    		}
    		if(AwardedAwardProjectMap != null && !AwardedAwardProjectMap.isEmpty()){
    			for(Project__c prAwarded : AwardedAwardProjectMap.values()){
    				if(prAwarded.Award__r != null && !prAwarded.Award__r.isEmpty()){
    					prAwarded.Awarded_Awards__c = prAwarded.Award__r.size();
    					Integer i = prAwarded.Award__r.size();
    					prAwarded.Project_End_Date__c = prAwarded.Award__r[i-1].Agreement_Period_End_Date__c;
    					prAwarded.Project_Start_Date__c = prAwarded.Award__r[0].Agreement_Period_Start_Date__c;
    				}else{
    					prAwarded.Awarded_Awards__c = 0;
    					//prAwarded.Project_Start_Date__c=null;
    					//prAwarded.Project_End_Date__c=null;
    				}
    			}
    	
    			update AwardedAwardProjectMap.values();
    		} 		
    	}//end of IF for Award List Empty check
    }
    
}