src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Slot__c.object
<CustomObject>
    <fields>
        <fullName>Aggregate_Recommendation_w_Allowance__c</fullName>
        <label>Aggregate Recommendation w/Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Aggregate_Recommendation_w_o_Allowance__c</fullName>
        <label>Aggregate Recommendation w/o Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ApplicationId__c</fullName>
        <formula>casesafeid(Budget_Application__r.Parent__r.Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ApplicationId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BudgetLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>BudgetLine</label>
        <referenceTo>cb3__BudgetLine__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots_BdgLn</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budget_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Application</label>
        <referenceTo>cb3__Budget__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots_BA</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_End_Date__c</fullName>
        <label>Enrollment End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Start_Date__c</fullName>
        <label>Enrollment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Slots</relationshipLabel>
        <relationshipName>Slots</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recommended_w_Allowance__c</fullName>
        <label>Recommended w/ Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Recommended_w_o_Allowance__c</fullName>
        <label>Recommended w/o Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_w_Allowance__c</fullName>
        <label>Requested w/ Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Requested_w_o_Allowance__c</fullName>
        <label>Requested w/o Allowance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Slot_Type__c</fullName>
        <label>Slot Type</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Slot</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Slot Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SlotInformationWithPrmAppCntrl.cls
public class  SlotInformationWithPrmAppCntrl{

    public ApexPages.StandardController stdcontroller;
    public Prime_Application__c prmApp{get;set;}
    public List<Slot__c> lstSlot{get;set;}
    public List<SlotGroupedData> lstSlotGroupedData{get;set;}
    
    public SlotInformationWithPrmAppCntrl(){
          System.debug('***SlotInformationWithApp constructor***');
    
    }
    
    public SlotInformationWithPrmAppCntrl(ApexPages.StandardController p_controller){
     try{
          this.stdcontroller= p_controller;
          this.prmApp= (Prime_Application__c )stdController.getrecord();
          System.debug('***prmApp***'+prmApp);
          String strPrmAppId='';
          strPrmAppId=(prmApp!=null )? prmApp.id:'';
          //readSlotInformation(strPrmAppId);
          deriveAggregateData( strPrmAppId);
     }     
     catch(Exception exc){
            System.debug('***error in SlotInformationWithPrmAppCntrl constructor***'+exc.getMessage());
        }   
      }
      
   
    
    public void deriveAggregateData(String p_strPrmAppId){  
            
        AggregateResult[] groupedResults;
        //List<SLOt__c> lstSlot=[select name from slot__c where name = :strPrmAppId];
        //System.debug('***lstSlot' + lstSlot);
        try{
            groupedResults=[select Slot_Type__c st,sum(Recommended_w_Allowance__c) awa,sum(Recommended_w_o_Allowance__c) awoa 
                                  from slot__c where Prime_Application__c= :p_strPrmAppId  and BudgetLine__c !=null
                                  group by  Slot_Type__c];
            System.debug('***groupedResults' + groupedResults);
            
            SlotGroupedData objTempSlotGroupedData=new SlotGroupedData();
            lstSlotGroupedData=new List<SlotGroupedData>();
            for (AggregateResult ar : groupedResults)  {
                System.debug('st' + ar.get('st'));
                System.debug('Aggr Recommended_w_Allowance' + ar.get('awa'));
                System.debug('Aggr Recommended_w_o_Allowance' + ar.get('awoa'));
                objTempSlotGroupedData=new SlotGroupedData();
                objTempSlotGroupedData.strSlotType=(ar.get('st')!=null )?String.valueOf(ar.get('st')):'';
                /*
                objTempSlotGroupedData.AggregateRecommendationWAllowance= (ar.get('awa')!=null )?String.valueOf(ar.get('awa')):'';    
                objTempSlotGroupedData.AggregateRecommendationWOAllowance=(ar.get('awoa')!=null) ?String.valueOf(ar.get('awoa')):''; 
                */
                if(ar.get('awa')!=null && ar.get('awa')!=0){
                    objTempSlotGroupedData.AggregateRecommendationWAllowance=String.valueOf(ar.get('awa'));   
                }else if(ar.get('awa')!=null && ar.get('awa')==0){
                    objTempSlotGroupedData.AggregateRecommendationWOAllowance=String.valueOf(ar.get('awa'));
                }

                if(ar.get('awoa')!=null ){
                    objTempSlotGroupedData.AggregateRecommendationWOAllowance=String.valueOf(ar.get('awoa'));   
                }
                
                
                lstSlotGroupedData.add(objTempSlotGroupedData);
            }
       }catch(DMLException sqlExc){
          System.debug('SQLException in method deriveAggregateData'+sqlExc);
       }
       catch(Exception exc){
           System.debug('SQLException in method deriveAggregateData'+exc);
       }     
    }   
    
    
    public class SlotGroupedData{
                public String strSlotType{get;set;}
                Public String AggregateRecommendationWAllowance{get;set;}
                Public String AggregateRecommendationWOAllowance{get;set;}
    } 
     
    /* this method is no longer used*/  
   public void readSlotInformation(String p_strPrmAppId){
         System.debug('***p_strPrmAppId***'+p_strPrmAppId);
         if(p_strPrmAppId!=null && p_strPrmAppId!=''){
                System.debug('readslotinformation if prmappid !=null');
                lstSlot =[SELECT ID,NAME,Slot_Type__c,Award__c,Prime_Application__c,ApplicationId__c,Budget_Application__c,Requested_w_Allowance__c,Requested_w_o_Allowance__c,
                                 Recommended_w_Allowance__c, Recommended_w_o_Allowance__c, Aggregate_Recommendation_w_Allowance__c,Aggregate_Recommendation_w_o_Allowance__c,
                                 Enrollment_Start_Date__c,Enrollment_End_Date__c 
                          FROM SLOT__c  Where Prime_Application__c= :p_strPrmAppId];  //Where Prime_Application__c= :p_prmAppId
         }         
         System.debug('*** lstSlot ***'+lstSlot );
         deriveAggregateData( p_strPrmAppId);    
   
    }
    /* this method is no longer used*/ 
    public void readSlotInformation1(String p_strPrmAppId){
         System.debug('***p_strPrmAppId***'+p_strPrmAppId);
         if(p_strPrmAppId!=null && p_strPrmAppId!=''){
                System.debug('readslotinformation if prmappid !=null');
                lstSlot =[SELECT ID,NAME,Slot_Type__c,Award__c,Prime_Application__c,ApplicationId__c,Budget_Application__c,Requested_w_Allowance__c,Requested_w_o_Allowance__c,
                                 Recommended_w_Allowance__c, Recommended_w_o_Allowance__c, Aggregate_Recommendation_w_Allowance__c,Aggregate_Recommendation_w_o_Allowance__c,
                                 Enrollment_Start_Date__c,Enrollment_End_Date__c 
                          FROM SLOT__c  Where Prime_Application__c= :p_strPrmAppId];  //Where Prime_Application__c= :p_prmAppId
         }         
         System.debug('*** lstSlot ***'+lstSlot );    
    }
    
    
    /* this method is no longer used*/ 
     public PageReference updateSlotRecs(){
        try{
           System.debug('*** lstSlot ***'+lstSlot );
           if(lstSlot !=null && lstSlot.size()>0){
             Update lstSlot ;
           }
        }
        catch(DMLException dmlExc){
            System.debug('***PrimeApp lstSlot -dmlExc ***'+dmlExc);
        }
        catch(Exception exc){
            System.debug('***lstSlot ***'+exc );
        }
        return null;
    
    }  



}