src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <label>Grant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting GO Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PO Certification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Organization e-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO CSHR Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO De-Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO De-Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Arrival</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Arrival_Date__c</fullName>
        <description>Project Arrival Date for any Team Assignment</description>
        <label>Project Arrival Date</label>
        <summarizedField>Team_Assignment__c.Project_Arrival_Date__c</summarizedField>
        <summaryFilterItems>
            <field>Team_Assignment__c.Project_Arrival_Date__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Team_Assignment__c.Award__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team_Assignment__c.object
<CustomObject>
    <description>Junction Object Between Award and Teams.</description>
    <fields>
        <fullName>Award__c</fullName>
        <description>MD relation with Award.</description>
        <label>Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Team Assignments</relationshipLabel>
        <relationshipName>Team_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_Arrival_Date__c</fullName>
        <description>Date selected must be greater than or equal to the “Campus Departure Date ” for the team.</description>
        <label>Project Arrival Date</label>
        <type>Date</type>
    </fields>
    <label>Team Assignment</label>
    <nameField>
        <displayFormat>TA-{00000000}</displayFormat>
        <label>Team Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateAwardStatus.cls
global class UpdateAwardStatus implements Schedulable {
   global void execute(SchedulableContext ctx) {
      set<Id> awardIds = new set<Id>();
      list<Team_Assignment__c> tas = new list<Team_Assignment__c>([Select Id,Award__c,Project_Arrival_Date__c from Team_Assignment__c where Project_Arrival_Date__c = Today]);
      for(Team_Assignment__c ta: tas){
          awardIds.add(ta.Award__c);
      }
      if(awardIds.size()>0){
          list<Award__c> awards = new list<Award__c>([Select Id,Grant_Status__c from Award__c where Id in :awardIds]);
          if(awards.size()>0){
              for(Award__c a: awards){
                  a.Grant_Status__c = 'Awarded';
              }
              update awards;
          }
      }      
   }   
}