src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Authorized_Amount__c</fullName>
        <inlineHelpText>Total federal funds authorized for this funding period.</inlineHelpText>
        <label>Authorized Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award Id</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Reporting</relationshipLabel>
        <relationshipName>Award_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Balance_Undrawn__c</fullName>
        <inlineHelpText>Total amount undrawn to date.</inlineHelpText>
        <label>Balance Undrawn</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Balance_of_Expenditures__c</fullName>
        <inlineHelpText>Total amount expended to date.</inlineHelpText>
        <label>Balance of Expenditures</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Disbursed_Amount__c</fullName>
        <inlineHelpText>Total amount disbursed to date.</inlineHelpText>
        <label>Disbursed Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Drawdowns__c</fullName>
        <inlineHelpText>Cumulative recipient share of outlays</inlineHelpText>
        <label>Drawdowns</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>FAIN__c</fullName>
        <formula>Award__r.Master_Award__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FAIN</label>
        <type>Text</type>
    </fields>
    <label>Award Reporting</label>
    <nameField>
        <displayFormat>Award Reporting-{000}</displayFormat>
        <label>Award Reporting Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FFRForAwardReportingCntrl.cls
public class FFRForAwardReportingCntrl{

    public ApexPages.StandardController stdcontroller;
    public Award_Reporting__c objAward_Reporting{get;set;}
    public String strAwardName{get;set;}
    public String recRecordTypeId;
    
    public FFRForAwardReportingCntrl(ApexPages.StandardController p_controller){
        this.stdcontroller= p_controller;
        stdcontroller.addFields(new List<String>{'name','FAIN__c','RecordTypeId'});
        this.objAward_Reporting= (Award_Reporting__c )stdController.getrecord();
        strAwardName=objAward_Reporting.FAIN__c;
        recRecordTypeId=objAward_Reporting.RecordTypeId;
        System.debug('***objAward_Reporting***'+objAward_Reporting);
   }
   
   public PageReference invokeFFRData(){
       
       HttpResponse hResp;
       String json='';
       String strWSname='ffrData';
       String  endPointuri='';
       String  uName='';
       String  upassword='';
       String  httpMethodName='';
       String  contenttype='';
          
       CNCS_AuthorizeHttp objCNCS_AuthorizeHttp=new CNCS_AuthorizeHttp();
       try{
            String ffrRecordTypeId=CNCS_ObjectUtility.getObjectRecordTypeId( Award_Reporting__c.SObjectType,'Federal Financial Reports');
            System.debug('***ffrRecordTypeId***'+ffrRecordTypeId);
            //CNCS_ObjectUtility.getObjectRecordTypeId(Award__c.SObjectType,'App Award');
            
            if(recRecordTypeId!=null && ffrRecordTypeId!=null && recRecordTypeId.equals(ffrRecordTypeId)){
                System.debug('*** recordTypeIds matching***');
            
                Intgr_MuleSoft__c objIntgr_MuleSoft=CNCS_ObjectUtility.retrieveWSDetails(strWSname);
                System.debug(objIntgr_MuleSoft);
                if(objIntgr_MuleSoft==null){
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Configuration for Web Service Grant Closeout is not setUp'));
                        throw new RecordTypeException();
                }
                endPointuri=objIntgr_MuleSoft.endPointuri__c;
                uName=objIntgr_MuleSoft.uName__c;
                upassword=objIntgr_MuleSoft.upassword__c;
                httpMethodName=objIntgr_MuleSoft.httpMethodName__c;
                contenttype=objIntgr_MuleSoft.contenttype__c;
                String strBody=composeBodyForFFRData();
                System.debug('endPointuri'+endPointuri+''+'httpMethodName'+httpMethodName+'uName'+uName+'upassword'+upassword+'contenttype'+contenttype);
                
                hResp=objCNCS_AuthorizeHttp.wsConnectAndSend(endPointuri,uName,upassword,httpMethodName,contenttype,strBody,false);
                System.debug('***hResp***'+hResp);
                if(hResp!=null && hResp.getStatusCode()!=200){
                         throw new CNCS_ObjectUtility.CustomException('Status-->'+hResp.getStatus()+' StatusCode-->'+hResp.getStatusCode()+'  Message-->'+hResp.getBody().replace('\n', ''));
                }
                // the service is returning a line feed so parse it out
                json = hResp.getBody().replace('\n', '');
                System.debug('***json***'+json );
                
                ParseJSONUtil objParseJSONUtil= new ParseJSONUtil();
                ParseJSONUtil.FFRDataForGrantIdJSON    objFFRDataForGrantIdJSON= new ParseJSONUtil.FFRDataForGrantIdJSON();
                objFFRDataForGrantIdJSON= objParseJSONUtil.parseFFRDataForGrantIdJSON(json);
                System.debug('***objFFRDataForGrantIdJSON'+objFFRDataForGrantIdJSON);
                List<ParseJSONUtil.FFRDataForGrantId> lstFFRDataForGrantId=objFFRDataForGrantIdJSON.lstData;
                System.debug('***lstFFRDataForGrantId'+lstFFRDataForGrantId);
                updateMomentumDataForFFRAwardReporting(lstFFRDataForGrantId);
            }    
           }catch(System.CalloutException ce) {
              System.debug('Callout error: '+ ce);
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,ce.getMessage()));
              //System.debug(resp.toString());
         }catch(CNCS_ObjectUtility.CustomException custExc) {
                  System.debug('Custom Exception '+ custExc);
                  ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,custExc.getMessage()));
         }
         catch(System.DmlException de) {
              System.debug('Callout error: '+ de);
              ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,de.getMessage()));
         }
         catch(Exception exc){
            System.debug('***exc***'+exc.getMessage());
         }
         return null;
   }
   
   public String composeBodyForFFRData(){
       //strAwardName='15CAHOR001';
       String strBody ='{ "grant_id":'+'"'+ strAwardName+'" }';
       return strBody;
   
   }
   
   public void updateMomentumDataForFFRAwardReporting(List<ParseJSONUtil.FFRDataForGrantId> lstFFRDataForGrantId){
       List<Award_Reporting__c> lstAward_Reporting =new List<Award_Reporting__c>();
       Award_Reporting__c objTempAward_Reporting;
       for( ParseJSONUtil.FFRDataForGrantId objFFRDataForGrantId :lstFFRDataForGrantId){
          objTempAward_Reporting=new Award_Reporting__c();
          /*
          objTempAward_Reporting.id=objAward_Reporting.id;
          objTempAward_Reporting.Balance_Undrawn__c =(objFFRDataForGrantId.BALANCE_UNDRAWN_AMT!=null && objFFRDataForGrantId.BALANCE_UNDRAWN_AMT!='')? Double.valueOf(objFFRDataForGrantId.BALANCE_UNDRAWN_AMT):0;
          objTempAward_Reporting.Balance_of_Expenditures__c =(objFFRDataForGrantId.BALANCE_UNEXPENDED_AMT!=null & objFFRDataForGrantId.BALANCE_UNEXPENDED_AMT!='')?Double.valueOf(objFFRDataForGrantId.BALANCE_UNEXPENDED_AMT):0; 
          objTempAward_Reporting.Disbursed_Amount__c =(objFFRDataForGrantId.DISBURSED_AMT!=null && objFFRDataForGrantId.DISBURSED_AMT!='')?Double.valueOf(objFFRDataForGrantId.DISBURSED_AMT):0 ;
          objTempAward_Reporting.Authorized_Amount__c =(objFFRDataForGrantId.FED_EXPENDITURES_AMT!=null && objFFRDataForGrantId.FED_EXPENDITURES_AMT!='')?Double.valueOf(objFFRDataForGrantId.FED_EXPENDITURES_AMT):0 ;
          objTempAward_Reporting.Drawdowns__c =(objFFRDataForGrantId.OBLIGATION_AMT!=null && objFFRDataForGrantId.OBLIGATION_AMT!='')?Double.valueOf(objFFRDataForGrantId.OBLIGATION_AMT):0; 
          */
          objTempAward_Reporting.id=objAward_Reporting.id;
          objTempAward_Reporting.Authorized_Amount__c =(objFFRDataForGrantId.OBLIGATION_AMT!=null && objFFRDataForGrantId.OBLIGATION_AMT!='')? Double.valueOf(objFFRDataForGrantId.OBLIGATION_AMT):0;
          objTempAward_Reporting.Disbursed_Amount__c =(objFFRDataForGrantId.FED_EXPENDITURES_AMT!=null & objFFRDataForGrantId.FED_EXPENDITURES_AMT!='')?Double.valueOf(objFFRDataForGrantId.FED_EXPENDITURES_AMT):0; 
          objTempAward_Reporting.Drawdowns__c =(objFFRDataForGrantId.DISBURSED_AMT!=null && objFFRDataForGrantId.DISBURSED_AMT!='')?Double.valueOf(objFFRDataForGrantId.DISBURSED_AMT):0 ;
          objTempAward_Reporting.Balance_of_Expenditures__c =(objFFRDataForGrantId.BALANCE_UNEXPENDED_AMT!=null && objFFRDataForGrantId.BALANCE_UNEXPENDED_AMT!='')?Double.valueOf(objFFRDataForGrantId.BALANCE_UNEXPENDED_AMT):0 ;
          objTempAward_Reporting.Balance_Undrawn__c =(objFFRDataForGrantId.BALANCE_UNDRAWN_AMT!=null && objFFRDataForGrantId.BALANCE_UNDRAWN_AMT!='')?Double.valueOf(objFFRDataForGrantId.BALANCE_UNDRAWN_AMT):0; 
         
          
          lstAward_Reporting.add(objTempAward_Reporting);
       }
       try{
           if(lstAward_Reporting!=null && lstAward_Reporting.size()>0){
               update lstAward_Reporting;
           }   
       }catch(DMLException dmlExc){
           System.debug('***dmlExc***'+dmlExc);
           System.debug('***dmlExc.getMessage()***'+dmlExc.getMessage());
       
       }catch(Exception exc){
           System.debug('***exc***'+exc);
           System.debug('***exc.getMessage()***'+exc.getMessage());
       }
   }
   
    public class RecordTypeException extends Exception{}

}