src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <label>Grant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting GO Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PO Certification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Organization e-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO CSHR Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO De-Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO De-Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Arrival</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PO_Certification_Date__c</fullName>
        <description>Field to populate the date when the PO takes action on Award record.</description>
        <label>PO Certification Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO__c</fullName>
        <description>Field to populate the PO Name who took action on Award record.</description>
        <label>PO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Officer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AwardHandler.cls
// Handler class for Award Trigger. KY_8.6.15
public class AwardHandler {
public static final String Awaiting_PO_Approval = 'Awaiting PO Approval';


public void handleTrigger(Award__c[] trigNew, Award__c[] trigOld) {
        if (Trigger.isBefore) {
            if (Trigger.isInsert || Trigger.isUpdate) {
                handleBeforeUpdate(trigNew);
            } 
        }
    }

private void handleBeforeUpdate(Award__c[] trigNew) {
List <Award__c> AwardUpdate = new List <Award__c> ();
AwardUpdate = Trigger.new;
for (Award__c Award : AwardUpdate)
{
if (Award.Grant_Status__c == 'Awaiting SPO Approval') {
// Award.PO__c = Award.Program_Officer__c;  
Award.OwnerId = Award.Program_Officer__c;
// Award.PO_Certification_Date__c = Award.LastModifiedDate;
}
}}



}