src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Grant_Status__c</fullName>
        <label>Grant Status</label>
        <picklist>
            <picklistValues>
                <fullName>Awaiting GO Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting PO Certification</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Organization e-Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO CSHR Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awarded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Being Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO Award</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SGO De-Obligation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting XO De-Commitment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Committed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>De-Obligated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPO Approval/Denial Waitlist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting SPO Signature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Team Arrival</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Master_Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Federal Award Identification Number</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Application_ID__r.Project__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Grant_Close_Out__c.object
<CustomObject>
    <fields>
        <fullName>Master_Award__c</fullName>
        <label>Federal Award Identification Number</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipName>Grants_Close_Out</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <formula>Master_Award__r.Project__c</formula>
        <label>Project Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Closeout Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Momentum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Certified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>GCO-{00000}</displayFormat>
        <label>Closeout Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Master Awards</relationshipLabel>
        <relationshipName>Master_Awards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the Master Award</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the Project</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReopenProjectOnGrantCloseOutCtrl.cls
public class ReopenProjectOnGrantCloseOutCtrl
{
    public String grantClosedOutId;
    public ReopenProjectOnGrantCloseOutCtrl()
    {
        grantClosedOutId = ApexPages.CurrentPage().getParameters().get('Id');
    }
    
    public void  reOpenProject()
    {
        grantClosedOutId = ApexPages.CurrentPage().getParameters().get('Id');
        system.debug('###grantClosedOutId : '+grantClosedOutId);
        
        if(grantClosedOutId != null && grantClosedOutId.trim().length() > 0)
        {
            Grant_Close_Out__c gco = [Select Id, Name, Master_Award__c From Grant_Close_Out__c Where Id = : grantClosedOutId Limit 1];
            if(gco != null)
            {
                Master_Award__c masterAward = [Select Id, Name, Status__c, Project_Name__c, 
                                                    (Select Id, Name, Grant_Status__c 
                                                        From Award__r) 
                                               From Master_Award__c 
                                               Where Id = : gco.Master_Award__c Limit 1];
                if(masterAward != null)
                {
                    // status of the Project should change to Open
                    if(masterAward.Project_Name__c != null)
                    {
                        Project__c pro = new Project__c(Id = masterAward.Project_Name__c, Status__c  = 'Open');
                        update pro;
                    }
                    
                    // status of the children awards should change to Awarded 
                    if(masterAward.Award__r != null && masterAward.Award__r.size() > 0)
                    {
                        for(Award__c award: masterAward.Award__r)
                        {
                            award.Grant_Status__c = 'Awarded';
                        }
                        update masterAward.Award__r;
                    }
                    
                    //Award__c newAward = new Award__c(Name = '', Master_Award__c = masterAward.Id, Grant_Status__c = 'Awarded');
                    // status of the Master Award should change from Complete to Active
                    masterAward.Status__c = 'Active';
                    update masterAward;
                }
            }
        }
    }
}