src/objects/Award__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Award</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award</relationshipLabel>
        <relationshipName>Award</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award</label>
    <nameField>
        <label>Award ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Award</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Award_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Award__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Award Id</label>
        <referenceTo>Award__c</referenceTo>
        <relationshipLabel>Award Reporting</relationshipLabel>
        <relationshipName>Award_Reporting</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Award Reporting</label>
    <nameField>
        <displayFormat>Award Reporting-{000}</displayFormat>
        <label>Award Reporting Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FFRUpdateTriggertest.cls
@istest
public class  FFRUpdateTriggertest
{

 static testMethod void testmethod1()
{
 Award__c testawd = UtilityClass.createAward();

 Insert testawd;
 
 Award_Reporting__c ar = new Award_Reporting__c();
 
 id FFRRecordTypeId = Schema.SObjectType.Award_Reporting__c.getRecordTypeInfosByName().get('Federal Financial Reports').getRecordTypeId();                                     
 ar.RecordTypeid = FFRRecordTypeId;
 insert ar;
 
 Award_Reporting__c awardrep = new Award_Reporting__c();
 
 id FFRRecordTypeId1 = Schema.SObjectType.Award_Reporting__c.getRecordTypeInfosByName().get('Federal Financial Reports').getRecordTypeId();                                     
 awardrep.RecordTypeid = FFRRecordTypeId1;
 insert awardrep;
 
 }
 }