src/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <label>Campus Record ID</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Class Year</relationshipLabel>
        <relationshipName>Class</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class Year</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Class Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Year</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>As per #4603</description>
        <label>Campus</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>NCCC Campus</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Campuses</relationshipLabel>
        <relationshipName>Regions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campus</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Campus Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/RFP_Class_year__c.object
<CustomObject>
    <fields>
        <fullName>Class_Year__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class Year</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>RPF Class years</relationshipLabel>
        <relationshipName>RPF_Class_years</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>RFP Class Years</relationshipLabel>
        <relationshipName>RPF_Class_years</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RFP Class year</label>
    <nameField>
        <displayFormat>RFP Class year - {0000}</displayFormat>
        <label>RFP Class year Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RPF Class years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RFPClassYearHelper.cls
public with sharing class RFPClassYearHelper {
    public static void preventClassYearforCampus(list<RFP_Class_year__c> rfpCls){
        set<Id> rfpIds = new set<Id>();
        set<Id> clsIds = new set<Id>();
        for(RFP_Class_year__c r:rfpCls){
            if(r.NOFO_RFP__c != null){
                rfpIds.add(r.NOFO_RFP__c);              
            }
            if(r.Class_Year__c!=null){
                clsIds.add(r.Class_Year__c);
            }
        }
        list<RFP_Class_year__c> existingRfpCls = new list<RFP_Class_year__c>([Select Id,Name,NOFO_RFP__c,Class_Year__c,Class_Year__r.Region__c from RFP_Class_year__c where NOFO_RFP__c in :rfpIds]);
        Map<Id,Class__c> clsYrMap = new Map<Id,Class__c>([Select Id,Name,Region__c from Class__c where Id in :clsIds]);
        for(RFP_Class_year__c r:rfpCls){
            for(RFP_Class_year__c er:existingRfpCls){
                if(r.NOFO_RFP__c == er.NOFO_RFP__c){
                    if(er.Class_Year__r.Region__c == clsYrMap.get(r.Class_Year__c).Region__c){
                        r.adderror('The campus for the selected class year must be unique');
                    }
                }
            }
        }
         
    }
}