src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Highest__c</fullName>
        <description>This field pulls the highest level of education value from history object.</description>
        <label>Highest Level of Education</label>
        <picklist>
            <picklistValues>
                <fullName>Less Than High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School Diploma/GED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical School/Apprenticeship/Vocational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associates Degree (AA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Degree (e.g. MA, PhD, MD, JD)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_CNCS_Reviews__c</fullName>
        <inlineHelpText>This information is collected for reporting purposes only and is not used to determine your eligibility to become an External Reviewer.</inlineHelpText>
        <label>How did you hear about CNCS Reviews?</label>
        <picklist>
            <picklistValues>
                <fullName>Email/recruitment flyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listserv or Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended by friend or colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNCS Website (NationalService.gov)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Mobile_Number__c</fullName>
        <description>The user must be able to identify if the phone number is a mobile phone number</description>
        <label>Is this a Mobile Number</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <description>This field stores mailing city of the user.</description>
        <label>Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <description>This field stores mailing state of the user</description>
        <label>Mailing State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address_1__c</fullName>
        <description>This field stores the mailing address of the user.</description>
        <label>Mailing Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Re_Enter_Email__c</fullName>
        <label>Re-Enter Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <label>State of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/History__c.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>CNCS</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Account__c</fullName>
        <label>User Account</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>History</relationshipLabel>
        <relationshipName>History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>History</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ExpertReviewerTest.cls
@isTest
private class ExpertReviewerTest {
    public static ContactCreateController8 ext;
    public static ExpertReviewEdit editext;
    public static accountRecordTypeSelection_Controller rtSelectExt; 
    public static ExpertReviewRedirect redirectExt;
    static testMethod void expertReviewDetailTest() {
        
        Pagereference pref = Page.ExpertReviewerDetail;
        test.setCurrentPage(pref);
        
        Account a = UtilityClass.createOrganization();
        insert a;
        
        Contact c = utilityClass.createContact();
        c.AccountId = a.Id;
        insert c;
        
        list<History__c> eduH = utilityClass.createEducationHistory();
        for(History__c h:eduH){
            h.User_Account__c = c.Id;
        }
        insert eduH;
        
        list<History__c> empH = UtilityClass.createEmploymenthistory();
        for(History__c eh:empH){
            eH.User_Account__c = c.Id;
        }
        insert empH;
        
        Apexpages.currentPage().getParameters().put('id',c.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Contact());
        ext = new ContactCreateController8(controller);
        ext.Acceptbtn();
        ext.editbtn();
        ext.rejectbtn();
        ext.SubmitBtn();
        ext.Applybtn();
        ext.pendingbtn();        
        
    }
    
    static testMethod void expertReviewEditTest() {
        Pagereference pref = Page.ExpertReviewEdit;
        test.setCurrentPage(pref);
        
        Account a = UtilityClass.createOrganization();
        insert a;
        
        Contact c = utilityClass.createContact();
        c.AccountId = a.Id;
        system.debug('conatct = '+c);
        insert c;        
        
        list<History__c> eduH = utilityClass.createEducationHistory();
        for(History__c h:eduH){
            h.User_Account__c = c.Id;
        }
        insert eduH;
        
        list<History__c> empH = UtilityClass.createEmploymenthistory();
        for(History__c eh:empH){
            eH.User_Account__c = c.Id;
        }
        insert empH;
        
        
        Apexpages.currentPage().getParameters().put('id',c.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Contact());
        editext = new ExpertReviewEdit(controller);        
        //editext.delEmpRow2();
        //editext.delRow2();
        editext.edubool = true;
        editext.empbool = true;
        editext.fileName = 'test attachment';
        editext.fileBody = Blob.valueOf('testing attachment');
        editext.save_upsert();
        editext.SaveAsDraft();
        editext.AddEmpRow2();
        editext.AddRow2();
        
        editext.edubool = false;
        editext.empbool = false;
        editext.fileName = 'test attachment';
        editext.fileBody = Blob.valueOf('testing attachment');
        editext.save_upsert();
        editext.SaveAsDraft();
        
        editext.con = new Contact();       
        editext.con.Salutation='Mr.';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';             
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';        
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.save_upsert();        
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.save_upsert();         
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.save_upsert();      
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.save_upsert();
            
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.save_upsert();      
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.history2.Experience_Type__c = 'Professional';
        editext.save_upsert();   
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.history2.Experience_Type__c = 'Professional';
        editext.history2.Expertise__c = 'Test expertise';
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.history2.Experience_Type__c = 'Professional';
        editext.history2.Expertise__c = 'Test expertise';
        editext.history2.Job_Description__c = 'test description';
        editext.save_upsert();
        
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.history2.Experience_Type__c = 'Professional';
        editext.history2.Expertise__c = 'Test expertise';
        editext.history2.Job_Description__c = 'test description';
        editext.history2.empFrom__c = Date.newInstance(1965,2,18);
        editext.save_upsert();
        
        editext.con = new Contact();
        editext.con.Salutation='Mr.';
        editext.con.Primary_Phone__c = '3837373772';
        editext.con.Is_this_a_Mobile_Number__c = 'No';
        editext.con.Email = 'test@gmail.com';
        editext.con.Re_Enter_Email__c = 'test@gmail.com';
        editext.con.Mailing_Street_Address_1__c = 'test street';
        editext.con.Mailing_State__c = 'test state';
        editext.con.Mailing_City__c = 'test city';
        editext.con.State_of_Residence__c = 'DC';
        editext.con.How_did_you_hear_about_CNCS_Reviews__c = 'google';
        editext.con.Highest__c = 'Test';        
        editext.con.FirstName = 'Test';
        editext.con.LastName = 'Contact';
        editext.con.Area_of_Expertise__c = 'CNCS';
        editext.con.State_of_Residence__c = 'VA';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history = new History__c();
        editext.history.Organization_Type1__c = 'test';
        editext.history.Areas_of_Study_Degree_Details__c = 'test';
        editext.history2 = new History__c();
        editext.history2.Employer__c = 'test employer';
        editext.history2.Organization_Type__c = 'Test organization';
        editext.history2.Area_of_Expertise__c = 'Test expertise';
        editext.history2.Experience_Type__c = 'Professional';
        editext.history2.Expertise__c = 'Test expertise';
        editext.history2.Job_Description__c = 'test description';
        editext.history2.empFrom__c = Date.newInstance(1965,2,18);
        editext.history2.empTo__c = date.newInstance(1970,2,18);
        editext.history2.Years_of_Experience__c = 5;
        editext.save_upsert();         
        apexpages.currentpage().getparameters().put('index','0');        
        editext.delEmpRow2();
        editext.delRow2();
      
    }
    
    static testMethod void expertReviewRedirectTest() {
        Pagereference pref = Page.ExpertReviewerDetail;
        test.setCurrentPage(pref);
        
        Account a = UtilityClass.createOrganization();
        insert a;
        
        Contact c = utilityClass.createContact();
        c.AccountId = a.Id;
        insert c;
        
        User u = utilityclass.createUser('Expert Reviewers');
        u.ContactId = c.Id;
        //insert u;
        
        System.runAs(u){
             //ApexPages.StandardController controller = new ApexPages.StandardController(new Contact());
             redirectExt = new ExpertReviewRedirect();
             redirectExt.PageRedirect();
        }
        
        
    }
    
    static testMethod void contactRecordTypeSelectTest(){
        
        Pagereference pref = Page.SelectRecordType;
        test.setCurrentPage(pref);
        
        Account a = UtilityClass.createOrganization();
        insert a;
        
        Contact c = utilityClass.createContact();
        c.AccountId = a.Id;
        insert c;
        
        Apexpages.currentPage().getParameters().put('id',c.Id);
        
        ApexPages.StandardController controller = new ApexPages.StandardController(new Contact());
        rtSelectExt = new accountRecordTypeSelection_Controller(controller);
        rtSelectExt.selectedRtType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Expert Reviewer').getRecordTypeId();
        rtSelectExt.continueWtSelection();
        
        rtSelectExt.selectedRtType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Grantee').getRecordTypeId();
        rtSelectExt.continueWtSelection();
    }
}