src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer_Performance_Rating__c</fullName>
        <label>External Reviewer Performance Rating</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Highest__c</fullName>
        <description>This field pulls the highest level of education value from history object.</description>
        <label>Highest Level of Education</label>
        <picklist>
            <picklistValues>
                <fullName>Less Than High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High School Diploma/GED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical School/Apprenticeship/Vocational</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associates Degree (AA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Degree (e.g. MA, PhD, MD, JD)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Performance_Rating__c</fullName>
        <label>Performance Rating</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <label>State of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the epert reviewer application</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - SAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Do Not Use</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <description>This field value sums up the total experience of the applicant and is pulled from the History object .</description>
        <label>Years of Experience</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NOFA_Group__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO Group</label>
    <nameField>
        <displayFormat>NOFA Group ID-{0000}</displayFormat>
        <label>NOFO Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Panel_Member__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>It describes the status of the panel member from a set of values.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Panel Member</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Panel Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup for NOFA Group object</description>
        <label>NOFO Group Name</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Paneling</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Panel_Coordinator__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to Contact object to find panel coordinator</description>
        <label>Panel Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Paneling</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reviewer_Pool__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Reviewer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expert Reviewer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviewer Pools</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Reviewer Pool</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available with Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible – COI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reviewer Pool</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Reviewer Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewer Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describes the status of that particular stage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddPanelMembersCont.cls
public class AddPanelMembersCont {
    
    public string qryStr{get;set;}
    public List<contactWrapper> wrappedContacts {get; set;}
    public Contact con{get;set;}
    public decimal rating{get;set;}
    public decimal Experience{get;set;}
    public set<Id> contactIdsfromPool = new set<Id>();
    public list<Contact> lContacts{get;set;} 
    public string debugsoql{get;set;}
    public Paneling__c panel;
    
    public AddPanelMembersCont() {
        
        list<Reviewer_Pool__c> poolMembers = new list<Reviewer_Pool__c>();
        //String panelId = ApexPages.currentPage.getParameters.get('id');
        
        if(ApexPages.currentPage().getParameters().get('id')!=null)
            panel = [Select Id,Name,Stage_Number__c,Stage_Number__r.NOFA_Group__c,NOFA_Group_Name__c,Panel_Coordinator__c from Paneling__c where Id = :ApexPages.currentPage().getParameters().get('id')];
        
        if(panel!=null && panel.Stage_Number__r.NOFA_Group__c != null){    
        	system.debug('nofa grp 1 = '+panel.Stage_Number__r.NOFA_Group__c);
        	system.debug('nofa grp 2 = '+panel.NOFA_Group_Name__c);     
            poolMembers = new list<Reviewer_Pool__c>([Select Id,Expert_Reviewer_Name__c from Reviewer_Pool__c where Status__c = 'Available' and NOFA_Group__c = :panel.Stage_Number__r.NOFA_Group__c]);
        	
        }
        if(poolMembers.size()>0){   
            for(Reviewer_Pool__c r: poolMembers){
                contactIdsfromPool.add(r.Expert_Reviewer_Name__c);
            }
        }
        con = new Contact();
        
    }
    
    public List<contactWrapper> getContacts() {
    	system.debug('contactIdsfromPool = '+contactIdsfromPool);
        lContacts = new list<Contact>([Select Id,Name,Email,Area_of_Expertise__c,Highest__c,Expert_Reviewer_Performance_Rating__c,Performance_Rating__c,State_of_Residence__c,Status__c,Years_of_Experience__c from Contact where Id in :contactIdsfromPool]);
        
        if(wrappedContacts == null) {
            wrappedContacts = new List<contactWrapper>();  
            for(Contact c: lContacts){
                wrappedContacts.add(new contactWrapper(c));
            }                     
        }
        return wrappedContacts;

    }

    public void runSearch(){
        system.debug('in search');
        string soql;
        /*string area = Apexpages.currentPage().getParameters().get('area');
        string education = Apexpages.currentPage().getParameters().get('education');
        string status = Apexpages.currentPage().getParameters().get('status');
        string residence = Apexpages.currentPage().getParameters().get('residence');
        String  rating1= Apexpages.currentPage().getParameters().get('rating');
        String  Experience1= Apexpages.currentPage().getParameters().get('Experience');
        
        system.debug('rating parameter = '+Apexpages.currentPage().getParameters().get('rating'));
        system.debug('area = '+area);
        system.debug('education = '+education);
        system.debug('status = '+status);
        system.debug('residence = '+residence);   
        system.debug('Experience parameter = '+Apexpages.currentPage().getParameters().get('Experience'));*/
        
        
                    
        string rating1 = '';
        if(con.Expert_Reviewer_Performance_Rating__c != null)
            rating1 = string.valueOf(con.Expert_Reviewer_Performance_Rating__c);
            
                         
        string Experience1 = '';
        if(con.Years_of_Experience__c!= null)
            Experience1 = string.valueOf(con.Years_of_Experience__c);   
                
        string education = '';
        if(con.Highest__c != null)
            education = con.Highest__c;
            
        string residence = '';        
        if(con.State_of_Residence__c != null)
            residence = con.State_of_Residence__c;
            
        string area = '';
        if(con.Area_of_Expertise__c != null)
            area = con.Area_of_Expertise__c;
            
        system.debug('Experience 1  = '+Experience1);
        system.debug('rating 1 = '+rating1);
        if(rating1 !='' && rating1 != null) {
            rating  = decimal.Valueof(rating1);
        }
        else{
            rating = 0;
        }
        System.debug('test::'+rating);
        
      
      if(Experience1 != '' && Experience1!= null) {
            Experience = decimal.Valueof(Experience1);
        }
        else{
            Experience = 0;
        }
          System.debug('test::'+Experience);    
      
        string t1='\'';
        string t2= '\'';
        
       
        
       
         if((area =='' || area == null) && (education =='' || education == null) && (residence =='' || residence == null) /*&& (status =='' || status == null)*/ && rating < 1 && Experience <1)
        {
             soql = 'select Id,Name,firstname,lastname,Email,Area_of_Expertise__c,Highest__c,Expert_Reviewer_Performance_Rating__c,State_of_Residence__c,Status__c,Years_of_Experience__c from contact where Id in :contactIdsfromPool ';     
        }
        else
        {
            soql = 'select Id,name,firstname,lastname,Email,Area_of_Expertise__c,Highest__c,Expert_Reviewer_Performance_Rating__c,State_of_Residence__c,Status__c,Years_of_Experience__c from contact where Id in :contactIdsfromPool and lastname!=null '  ;
            if (!area.equals(''))
                soql += ' AND Area_of_Expertise__c = '+t1+area+t2;
        
            if (!education.equals(''))
                soql += 'AND  Highest__c = '+t1+education+t2;
      
     
            if (!residence.equals(''))
                soql += ' AND State_of_Residence__c = '+t1+residence+t2;
                
      
            /*if (!status.equals(''))
                soql += ' AND Status__c = '+t1+status+t2;*/
            if(rating <1) {
                soql+='';
            }
            else {
                soql += ' AND Expert_Reviewer_Performance_Rating__c= '+rating;
            }
            
            if(Experience <1) {
                soql+='';
            }
            else {
                soql += ' AND Years_of_Experience__c= '+Experience;
            }
       
           system.debug('**************************************query'+soql);
            debugsoql = soql;
           
           
            //return wrappedContacts;
            
        
        }    
        
        if(lContacts.size()>0)
                lContacts.clear();
        lContacts = new list<Contact>();
        lContacts = database.query(soql);
            
        if(wrappedContacts.size()==0) {
            wrappedContacts = new List<contactWrapper>();  
            for(Contact c: lContacts){
                wrappedContacts.add(new contactWrapper(c));
            }                     
        }
        else if(wrappedContacts.size()>0){
            wrappedContacts.clear();
            wrappedContacts = new List<contactWrapper>();  
            for(Contact c: lContacts){
                wrappedContacts.add(new contactWrapper(c));
            }               
        }   
                
    }
    
    public class contactWrapper{
        public Contact con{get;set;}        
        public Boolean isSelected{get;set;}     
        
        public contactWrapper(Contact c) {
            con = c;
            isSelected = false;

        }
    }           
    
    public PageReference savePanelMembers(){
        list<Panel_Member__c> newpanelMembers = new list<Panel_Member__c>();
        set<Id> selectedContactIds = new set<Id>();
        for(ContactWrapper c: wrappedContacts){
            if(c.isSelected){
                selectedContactIds.add(c.con.Id);
            }
        }
        map<String,Panel_Member__c> existingMembersMap = new map<String,Panel_Member__c>();
        list<Panel_Member__c> existingPanelMembers = new list<Panel_Member__c>([Select Id,Expert_Reviewer__c,Panel__c from Panel_Member__c where Expert_Reviewer__c in :selectedContactIds]);
        for(Panel_Member__c pm: existingPanelMembers){
            existingMembersMap.put(String.valueOf(pm.Expert_Reviewer__c)+String.valueOf(pm.Panel__c),pm);
        }
        
        if(selectedContactIds.size()>0){
            for(Id i: selectedContactIds){
                String key = String.valueOf(i)+String.valueOf(panel.Id);
                system.debug('key = '+key);
                system.debug('map = '+existingMembersMap);
                if(existingMembersMap.get(key) == null){
                    Panel_Member__c pm = new Panel_Member__c();
                    pm.Expert_Reviewer__c = i;
                    pm.Panel__c = ApexPages.currentPage().getParameters().get('id');
                    pm.Status__c = 'Active';
                    if(panel.Panel_Coordinator__c == i){
                        pm.Role__c = 'Panel Coordinator';
                    }                   
                    // pm.Reviewer__c = 
                    newpanelMembers.add(pm);
                }
            }
        }
        
        if(newpanelMembers.size()>0){
            insert newpanelMembers;
        }
        PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
        return pg;
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
        return pg;
    }

}