src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CommunityAuto__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>CommunityAuto</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Dataloader_input__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dataloader input</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <description>This field stores mailing city of the user.</description>
        <label>Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <description>This field stores mailing state of the user</description>
        <label>Mailing State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address_1__c</fullName>
        <description>This field stores the mailing address of the user.</description>
        <label>Mailing Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Code__c</fullName>
        <description>This field stores the zip code of the user</description>
        <label>Mailing Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Grantee</fullName>
        <active>true</active>
        <label>Grantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateLegacyUserTest.cls
@isTest
Public Class CreateLegacyUserTest
{
    static testmethod void CreateLegacyUserTest(){
        Profile p = [SELECT Id FROM Profile WHERE Name='Grantee Admin'];
        Profile p1 = [SELECT Id FROM Profile WHERE Name='Applicant'];
        Profile p2 = [SELECT Id FROM Profile WHERE Name='Expert Reviewers'];
        
        Account a = new Account();
        a = UtilityClass.createOrganization();
        insert a ;
        Contact c = new Contact();
        //if(c.Dataloader_input__c==true){
        c.FirstName = 'Test FirstName';
        c.Dataloader_input__c = true;
        c.LastName = 'Test LastName';
        c.Primary_Phone__c = '230-908-1098';
        //c.CommunityAuto__c = 'Test';
        c.Email = 'test@email.com';
        c.Mailing_Street_Address_1__c = '2400 S Glebe Rd';
        c.Mailing_State__c ='VA';
        c.Mailing_City__c = 'Arlington';
        c.Mailing_Zip_Code__c = '22206';
        c.Accountid = a.id;
        //}
        insert c;
        
        User u = new User();
                if(c.Dataloader_input__c == true){
                     if(c.RecordTypeId == '012r00000004KUn'){
                            u.ProfileId = p.Id;
                            u.UserName = c.Email+'.grantee';
                        }
                    if(c.RecordTypeId == '012r00000004KUm'){
                            u.ProfileId = p1.Id;
                            u.UserName = c.Email+'.grantee';
                        }
                    if(c.RecordTypeId == '012r00000004KUl'){
                            u.ProfileId = p2.Id;
                            u.UserName = c.Email+'.externalreviewer';
                        }
                            u.FirstName=c.FirstName;
                            u.LastName=c.LastName;
                            u.UserName=c.Email;
                            u.ProfileId = p.Id;
                            //u.UserRole= c.LastName+ 'Customer user';
                            u.Alias = (c.FirstName+''+c.LastName).substring(0,1);
                            u.Email=c.Email;
                            u.ContactId=c.Id;
                            u.CommunityNickname = c.FirstName+''+c.LastName+''+c.CommunityAuto__c;
                            u.EmailEncodingKey = 'ISO-8859-1';
                            u.LanguageLocaleKey = 'en_US';
                            u.LocaleSidKey = 'en_US';
                            u.TimeZoneSidKey = 'America/New_York';
                }
                //insert u;
                
                /*System.runAs(u){
       
        }*/
    }
}