src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <description>This field stores mailing city of the user.</description>
        <label>Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <description>This field stores mailing state of the user</description>
        <label>Mailing State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address_2__c</fullName>
        <description>This field stores the mailing address of the user</description>
        <label>Mailing Street Address 2</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Code__c</fullName>
        <description>This field stores the zip code of the user</description>
        <label>Mailing Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Password__c</fullName>
        <inlineHelpText>Please enter a valid password. The should contain atleaset 1 Special Character.</inlineHelpText>
        <label>New Password</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Re_Enter_Email__c</fullName>
        <label>Re-Enter Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Re_Enter_Password__c</fullName>
        <label>Re-Enter Password</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CommunitiesSelfRegControllerTest.cls
/**
 * An apex page controller that supports self registration of users in communities that allow self registration
 */
@isTest(seealldata=true)
 private class CommunitiesSelfRegControllerTest {
    
    static testMethod void CommunitiesSelfRegControllerTest() {
        
        Pagereference pref = Page.CommunitiesCustomSelfRegPage;
        test.setCurrentPage(pref);
        
        CommunitiesSelfRegController controller = new CommunitiesSelfRegController();
        //ApexPages.currentPage().getParameters().put('')
        controller.firstName = 'FirstName';
        controller.lastName = 'LastName';
        controller.email = 'test@force.com';
        controller.communityNickname = 'test';        
        // registerUser will always return null when the page isn't accessed as a guest user    
        controller.registerUser();
              
        controller.password = 'abcd1234';
        controller.confirmPassword = 'abcd123';
        
        controller.registerUser(); 
        controller.Cancel();
         
    }    
    
    static testMethod void CommunitiesSelfRegController1Test() {
        Pagereference pref = Page.CommunitiesCustomSelfRegPage1;
        test.setCurrentPage(pref);
        
        CommunitiesSelfRegController1 controller = new CommunitiesSelfRegController1();
        //ApexPages.currentPage().getParameters().put('')
        controller.contact.firstName = 'FirstName';
        controller.contact.lastName = 'LastName';
        controller.contact.email = 'test@force.com';
        controller.contact.Re_Enter_Email__c = 'test@force.com';   
        controller.contact.Mailing_Street_Address_2__c = '1212 New York Ave. ';
        controller.contact.Mailing_City__c = 'DC';
        controller.contact.Mailing_State__c = 'DC';
        controller.contact.Mailing_Zip_Code__c = '20170';                  
        controller.contact.Re_Enter_Password__c = 'abcd1234';
        controller.contact.New_Password__c = 'abcd1234';
        controller.Address = 'landover st, alexandria,va,22305';    
        controller.contact.Primary_Phone__c= '6346466664'; 
        //controller.Submit();
        controller.registerUser();
        //controller.PageRedirect();
        
           
        
       // Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.setMock(WebServiceMock.class, new AddressDoctorWebServiceMock());
        controller.GetAddresses();
       
       
        controller.Submit();
        controller.Cancel();   
        
       // controller.closePopup();
    }
        static testMethod void CommunitiesSelfRegController1Test1() {
        Pagereference pref = Page.CommunitiesCustomSelfRegPage1;
        test.setCurrentPage(pref);
        
        CommunitiesSelfRegController1 controller = new CommunitiesSelfRegController1();
        //ApexPages.currentPage().getParameters().put('')
        controller.contact.firstName = 'FirstName';
        controller.contact.lastName = 'LastName';
        controller.contact.email = 'test@force.com';
        controller.contact.Re_Enter_Email__c = 'test@force.com';   
        controller.contact.Mailing_Street_Address_2__c = '1212 New York Ave. ';
        controller.contact.Mailing_City__c = 'DC';
        controller.contact.Mailing_State__c = 'DC';
        controller.contact.Mailing_Zip_Code__c = '20170';                  
        controller.contact.Re_Enter_Password__c = 'abcd1234';
        controller.contact.New_Password__c = 'abcd1234';
        controller.Address = 'landover st, alexandria,va,22305';    
        controller.contact.Primary_Phone__c= '6346466664'; 

        
       // controller.closePopup();
    }
}