src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Performance_Rating__c</fullName>
        <label>Performance Rating</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/History__c.object
<CustomObject>
    <fields>
        <fullName>Job_Description__c</fullName>
        <label>Job Description</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Account__c</fullName>
        <label>User Account</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>History</relationshipLabel>
        <relationshipName>History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>History</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Reviewer_Rating__c.object
<CustomObject>
    <fields>
        <fullName>Performance_Rating__c</fullName>
        <inlineHelpText>0-2.6 = F
2.7-3.4 = C
3.5-4.2 = B
4.3-5.0 = A</inlineHelpText>
        <label>Performance Rating</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reviewer_Name__c</fullName>
        <label>Reviewer Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviewer Ratings</relationshipLabel>
        <relationshipName>Reviewer_Ratings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Co-Ordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert Reviewer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reviewer Rating</label>
    <nameField>
        <label>Reviewer Rating</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reviewer Ratings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ReviewerRatingTriggerTest.cls
@isTest
public class ReviewerRatingTriggerTest
{
    static testmethod void method1()
    {
        Contact c=new Contact(lastname='Test');            //Insert Contact here
        insert c;
        History__c h=new History__c(Job_Description__c='Test',User_Account__c=c.id);    //Insert History Records
        History__c h1=new History__c(Job_Description__c='Test',User_Account__c=c.id);
        
        List<Reviewer_Rating__c> revList=new List<Reviewer_Rating__c>();
        Reviewer_Rating__c r=new Reviewer_Rating__c(Role__c = 'Panel Co-Ordinator',Performance_Rating__c=20,Reviewer_Name__c=c.id);
        revList.add(r);
        Reviewer_Rating__c r1=new Reviewer_Rating__c(Role__c = 'Panel Co-Ordinator',Performance_Rating__c=20,Reviewer_Name__c=c.id);
        revList.add(r1);
        Reviewer_Rating__c r2=new Reviewer_Rating__c(Role__c = 'Expert Reviewer',Performance_Rating__c=20,Reviewer_Name__c=c.id);
        revList.add(r2);
        Reviewer_Rating__c r3=new Reviewer_Rating__c(Role__c = 'Expert Reviewer',Performance_Rating__c=20,Reviewer_Name__c=c.id);
        revList.add(r3);
        
        insert revList;
        
        Reviewer_Rating__c r5=new Reviewer_Rating__c(Role__c = 'Panel Co-Ordinator',Performance_Rating__c=20,Reviewer_Name__c=c.id);
        insert r5;
        Reviewer_Rating__c r6=new Reviewer_Rating__c(Role__c = 'Expert Reviewer',Performance_Rating__c=20,Reviewer_Name__c=c.id);
        insert r6;
    }
}