src/objects/Expert_Reviewer_Form__c.object
<CustomObject>
    <fields>
        <fullName>Feeback__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Feedback</label>
        <referenceTo>Feedback__c</referenceTo>
        <relationshipName>Expert_Reviewer_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_the_date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Save the date</label>
        <referenceTo>Save_the_Date__c</referenceTo>
        <relationshipName>Expert_Reviewer_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Vetting Questions Not Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetting Questions Submitted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <label>Total Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>External Reviewer Form</label>
    <nameField>
        <displayFormat>Form - {0000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Reviewer Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Reviewer Form</label>
        <referenceTo>Expert_Reviewer_Form__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <formula>Setup_Questionnaire__r.Question_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Save the Date</label>
        <referenceTo>Save_the_Date__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup Questionnaire</label>
        <referenceTo>Setup_Questionnaire__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NOFA_Group__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO Group</label>
    <nameField>
        <displayFormat>NOFA Group ID-{0000}</displayFormat>
        <label>NOFO Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Save_the_Date__c.object
<CustomObject>
    <description># 471</description>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to NOFO Group for implementing save the date functionality</description>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ineligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible - COI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Save the Date</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Save the Date ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Save the Date</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Setup_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Setup Questionnaires</relationshipLabel>
        <relationshipName>Setup_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup Questionnaire</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>Setup Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeedbackScoreCtrl.cls
public class FeedbackScoreCtrl
{
    public Id Erfmid;
    public Id SaveDateid;
    public Expert_Reviewer_Form__c sd;
    public string fId{get;set;}
    public List<Setup_Questionnaire__c> setupQue{get;set;}
    public list<wrapQuesion> lstWrap{get;set;}
    public Map<String,String> QaMap{get;set;}
    public string textbox1{get;set;}
    public string tanswer;
    public double totalscore {get;set;}
    public double stotal{get;set;}
    public boolean isedit{get;set;}
    public list<Feedback__c> FeList;
    public Id currentRecordId{get;set;}
    public Map<String,String> Mapquestionans{get;set;}
    public boolean issetupequestion{get;set;}
    public String mode{get;set;}// determines if the page is new,edit/view mode
    public string ftotal{get;set;}
    public Integer tSize;
    public string total{get;set;}
    Save_the_date__c savethedaterec = new  Save_the_date__c();
    public FeedbackScoreCtrl(ApexPages.StandardController controller) {
      issetupequestion = false;
      sd = new Expert_Reviewer_Form__c();
      setupQue = new List<Setup_Questionnaire__c>();
      lstWrap = new list<wrapQuesion>();
      QaMap = new Map<String,String>();
      FeList = new list<Feedback__c>();
      Mapquestionans = new map<string,string>();
      Erfmid = apexpages.currentpage().getparameters().get('id');
      
      sd = [Select id,Save_the_date__c,Save_the_date__r.Save_the_Date__c,recordtype.name  from Expert_Reviewer_Form__c where id =:Erfmid LIMIT 1];
      if(sd.recordtype.name == 'Setup Questionnaire'){
      issetupequestion = true;
      }
      if(sd.Save_the_date__c != null){
          savethedaterec = [select id,status__c from Save_the_date__c where id= :sd.Save_the_date__c limit 1];
      }
      setupQue  = [select id,Question_1__c,Answer_1__c from Setup_Questionnaire__c where NOFO_Group__c =:sd.Save_the_date__r.Save_the_Date__c and recordType.name =:sd.recordtype.name];
      
      currentRecordId = ApexPages.currentPage().getParameters().get('id');
      mode = ApexPages.currentPage().getParameters().get('pageMode');   
      if(ApexPages.currentPage().getParameters().get('total') != null)
      {
      totalscore = double.valueof(ApexPages.currentPage().getParameters().get('total'));
      }
      
      if(ApexPages.currentPage().getParameters().get('ftotal') != null)
      {
      stotal = double.valueof(ApexPages.currentPage().getParameters().get('ftotal'));
      }
      
      for(Setup_Questionnaire__c  setq : setupQue){
      
      Mapquestionans.put(setq.Question_1__c,setq.Answer_1__c);
      }
      for(feedback__c feed : [select id,Question_1__c,Answer_1__c from Feedback__c where Expert_Reviewer_Form__r.id =: sd.id and recordType.name =: sd.recordtype.name ])
      {
         if(feed.Answer_1__c != null){
              system.debug('setq.Answer_1__c'+feed.Answer_1__c);
              isedit = true;
          }
          else {
              isedit = false;
          }
         wrapQuesion objWrap = new wrapQuesion();
          objWrap.fb = feed;
         lstWrap.add(objWrap);
      }
          //string s= pageMode();
       }
      
      public string pageMode(){

            String pageMode;

            System.debug('$$$$ :' + mode);
            // determine the page mode: new, edit, view.
            Id i = currentRecordId;

            Map<String,String> parameters = ApexPages.currentPage().getParameters();
            if(i == null){
                pageMode = 'new';
                System.debug('$$$$ :' + mode);
            } else if(parameters.containsKey('pageMode')){
                pageMode = 'edit';
                System.debug('$$$$ :' + pageMode);
            } else{
                pageMode = 'view';
                System.debug('$$$$ :' + mode);
            }
            if(sd.recordtype.name == 'Setup Questionnaire'){
              issetupequestion = true;
            }
            return pageMode;
            
        }

      
    public void calculate(){
    system.debug('####### >> '+textbox1);
    tanswer = textbox1;
    system.debug('the fid is'+QaMap.get(fId));
    system.debug('the answer is'+tanswer);
    for(wrapQuesion objWr:lstWrap){
    
        if(objWr.fb.Question_1__c == fId){
            if(objWr.fb.Answer_1__c == Mapquestionans.get(fId)){
               objwr.stotal='100';
               break;
            }
            else{
               objwr.stotal='0';    
            }    
        }
    }
    
    }
    
    public class wrapQuesion{
    
        public Feedback__c fb{get;set;}
        public string stotal{get;set;}
        
    }  
      
     public PageReference editRec(){
     PageReference pr = New PageReference('/apex/FeedbackScore?id='+ currentRecordId  );
     pr.getParameters().put('pageMode','edit');
     pr.setredirect(true);
     return pr;
     } 
        
        
   public pagereference save(){
      list<FeedBack__c> listtoupdate = new list<Feedback__c> ();
       
       integer tTotal=0;
       tSize = lstWrap.size();
       system.debug('ttotal'+lstWrap);
       system.debug('the size is'+tSize);
       for(wrapQuesion wq:lstWrap){
       if(wq.stotal != null) tTotal=tTotal+Integer.valueOf(wq.stotal); 
       listtoupdate.add(wq.fb);
       }
       system.debug('the total is####'+tTotal);
       if(tTotal != null && tsize != null) totalscore = tTotal/tSize;
              system.debug('the total is@@@@@'+totalscore );
       if(issetupequestion==true){
           sd.Total_Score__c  =  totalscore;
            system.debug('the total is####@'+sd.Total_Score__c );
       }
       
       boolean issuccess = false; 
       Try{
         update sd;
         update listtoupdate;
         issuccess = true;
       }
       Catch(exception e){
       
       }
       system.debug(issetupequestion );
       system.debug(issuccess);
       if(issetupequestion == false && issuccess == true ){
           savethedaterec.status__c = 'Pre-Confirmed';
           
           try {
           update savethedaterec;
            }
           Catch(exception e){
               system.debug('e***'+e.getmessage());
           }
       }
       string str = string.valueof(totalscore);
       string str1 = string.valueof(stotal);
         
    PageReference pr = New PageReference('/apex/FeedbackScore?id='+sd.id);
    
         pr.getParameters().put('pageMode','view');
         
         pr.getParameters().put('total',str);
         pr.getParameters().put('ftotal',str1);
         pr.setredirect(true);
         
         return pr;   
   
   }
     
}