src/objects/Expert_Reviewer_Form__c.object
<CustomObject>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_the_date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Save the date</label>
        <referenceTo>Save_the_Date__c</referenceTo>
        <relationshipName>Expert_Reviewer_Form</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Vetting Questions Not Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vetting Questions Submitted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>External Reviewer Form</label>
    <nameField>
        <displayFormat>Form - {0000}</displayFormat>
        <label>Form ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Reviewer Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer_Form__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Reviewer Form</label>
        <referenceTo>Expert_Reviewer_Form__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <formula>Setup_Questionnaire__r.Question_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Save the Date</label>
        <referenceTo>Save_the_Date__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup Questionnaire</label>
        <referenceTo>Setup_Questionnaire__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reviewer_Pool__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Reviewer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expert Reviewer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviewer Pools</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available with Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible – COI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reviewer Pool</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Reviewer Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewer Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Save_the_Date__c.object
<CustomObject>
    <description># 471</description>
    <fields>
        <fullName>Comments__c</fullName>
        <description>When ‘Available w/Comments’ is selected from the “Response” picklist, the “Comments” field shall be required.</description>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Competition_Fiscal_Year__c</fullName>
        <label>Competition Fiscal Year</label>
        <picklist>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2024</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Competition_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>#471</description>
        <label>Competition Name</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Corporate_Program_Name__c</fullName>
        <formula>Competition_Name__r.Corporate_Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corporate Program Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <formula>Reviewer_Pool__r.Expert_Reviewer_Name__r.FirstName&amp; &apos; &apos; &amp;Reviewer_Pool__r.Expert_Reviewer_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expert Reviewer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Save the date functionality</description>
        <label>Expert Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <formula>Text(Competition_Name__r.Fiscal_Yr__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fiscal Year</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <picklist>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available w/Comments</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reviewer_Pool__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Save the date functionality</description>
        <label>Reviewer Pool</label>
        <referenceTo>Reviewer_Pool__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <label>Role Type</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Expertise Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to NOFO Group for implementing save the date functionality</description>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ineligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible - COI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Save the Date</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Save the Date ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Save the Date</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Setup_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Setup Questionnaires</relationshipLabel>
        <relationshipName>Setup_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup Questionnaire</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>Setup Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/QuestionnaireFormSetup.cls
public with sharing class QuestionnaireFormSetup{

    private ApexPages.StandardController standardController;
    
    public QuestionnaireFormSetup(ApexPages.StandardController standardController){
        this.standardController = standardController;
    }
    
    public PageReference trainingQuestion(){
        
        Id recordId = standardController.getId();
        system.debug(recordId);
        Save_the_Date__c saveTheDate = [Select id,Comments__c,Competition_Fiscal_Year__c,Competition_Name__c,Corporate_Program_Name__c,Expert_Reviewer__c,
                                       Expert_Reviewer_Name__c,Fiscal_Year__c,Save_the_Date__c,Response__c,Reviewer_Pool__c,Role_Type__c,Status__c from
                                        Save_the_Date__c where id =:recordId];
                                        
        system.debug('Save_the_Date__c '+saveTheDate );                           
        List<Expert_Reviewer_Form__c> questionFeedbackList = new List<Expert_Reviewer_Form__c>();
        List<Feedback__c> feedbackQuestion = new List<Feedback__c>();
        List<Setup_Questionnaire__c> questions= new List<Setup_Questionnaire__c >();
        questions = [Select id,Name,Answer_1__c,NOFO_Group__c,Question_1__c,RecordType.name,RecordType.id from Setup_Questionnaire__c where NOFO_Group__c=:saveTheDate.Save_the_Date__c];
        System.debug('List of Questions -----' + questions.size());
        set<string> recordtypenames = new set<string>();
        for(Setup_Questionnaire__c qc: questions){
            recordtypenames.add(qc.recordtype.name);
        }
        System.debug('recordtypenames -----' + recordtypenames);
        list<string> recordtypenameslist = new list<string>();
        Map<string,string> exrectype = new Map<string,string>();
        Map <string,string> expfmap = new map<string,string>();
        
        try {
        for(Recordtype f1: [select id,name from RecordType where SObjectType = 'Expert_Reviewer_Form__c' and name in: recordtypenames ]){
                expfmap.put(f1.name,f1.id);
                recordtypenameslist.add(f1.name);
                exrectype.put(f1.id,f1.name);
        }
        }
        catch (exception e){
            system.debug('eeee'+e.getmessage());
        }
        System.debug('expfmap-----' + expfmap);
        if(saveTheDate.Response__c == 'Available' ||saveTheDate.Response__c == 'Available w/Comments' )
        {
         
        try {    
                saveTheDate.Status__c ='Submitted';   
                update saveTheDate;
                if(recordtypenames.size()>0){
                    FOR(integer i=0;i<recordtypenames.size();i++){
                        Expert_Reviewer_Form__c QuestionForm = new Expert_Reviewer_Form__c();
                        QuestionForm.RecordtypeId = expfmap.get(recordtypenameslist[i]);
                        QuestionForm.Save_the_date__c = saveTheDate.id;
                        questionFeedbackList.add(QuestionForm);
                    }
                }
                
                Map <string,string> qfmap = new map<string,string>();
                for(Recordtype f1: [select id,name from RecordType where SObjectType =: 'Feedback__c' and name in:recordtypenames])
                {
                qfmap.put(f1.name,f1.id);
                 
                }   
                Map<string,id> eprfmap = new Map<string,id>();
                if(questionFeedbackList.size() > 0){
                    boolean success;
                    try{
                    insert questionFeedbackList;
                    success = true;
                    }
                    catch(exception e){
                    
                    }
                    if(success){
                        for(Expert_Reviewer_Form__c expf: questionFeedbackList){
                            eprfmap.put(expf.recordtypeid,expf.id);
                        }
                    }
                    System.debug('eprfmap-----' + eprfmap);       
                }
                
                if(questionFeedbackList.size()>0 && questions.size()>0){ 
                       
                       //for(Expert_Reviewer_Form__c ques :questionFeedbackList){
                            
                            for( Setup_Questionnaire__c q: questions ) {
                             
                                   Feedback__c QF = new Feedback__c();
                                     
                                   QF.NOFO_Group__c = q.NOFO_Group__c;
                                     
                                   QF.Setup_Questionnaire__c = q.id;
                                   id recty= expfmap.get(q.recordtype.name);
                                   QF.Expert_Reviewer_Form__c = eprfmap.get(recty);
                                   system.debug('QF.Expert_Reviewer_Form__c'+QF.Expert_Reviewer_Form__c);
                                   QF.RecordTypeid= qfmap.get((q.recordtype.name));
                                    // Schema.SObjectType.Feedback__c.getRecordTypeInfosByName().get('Advertiser').getRecordTypeId();
                                  
                                  // QF.Question_1__c = q.Question_1__c;
                                  // QF.Answer_1__c = q.Answer_1__c;
                               
                                  QF.Save_the_date__c = saveTheDate.id;
                                   feedbackQuestion.add(QF);
                                }
                           //}
                      }
                      
                      if(feedbackQuestion.size()>0){
                        insert feedbackQuestion;
                      }
        
        }
        catch(exception e){
            System.debug('execption'+e.getmessage());
        }
        }
        else {
            saveTheDate.Status__c ='Submitted';
            try {
                update saveTheDate;
            
            }
            catch(exception e){
                System.debug('exception'+e.getmessage());
            }
        }
        /*if(saveTheDate.Status__c =='Submitted'){
        
                Expert_Reviewer_Form__c QuestionForm = new Expert_Reviewer_Form__c();
                QuestionForm.Save_the_date__c = saveTheDate.id;
                questionFeedbackList.add(QuestionForm);
                
                if(questionFeedbackList.size() > 0){
                
                    insert questionFeedbackList;
                }
                
                if(questionFeedbackList.size()>0 && questions.size()>0){ 
                       
                       for(Expert_Reviewer_Form__c ques :questionFeedbackList){
                           
                            for( Setup_Questionnaire__c q: questions ) {
                            
                                   Feedback__c QF = new Feedback__c();
                                   QF.NOFO_Group__c = q.NOFO_Group__c;
                                   QF.Setup_Questionnaire__c = q.id;
                                   QF.Expert_Reviewer_Form__c = questionFeedbackList[0].id;
                                  // QF.Question_1__c = q.Question_1__c;
                                  // QF.Answer_1__c = q.Answer_1__c;
                               
                                  QF.Save_the_date__c = saveTheDate.id;
                                   feedbackQuestion.add(QF);
                                }
                           }
                      }
                      if(feedbackQuestion.size()>0){
                        insert feedbackQuestion;
                      }
                }*/
                
                PageReference pageRef = new PageReference('/'+saveTheDate.Id);
                pageRef.setRedirect(true);
                return pageRef;
        }
       
}