src/objects/Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <formula>Setup_Questionnaire__r.Question_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Question</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Save the Date</label>
        <referenceTo>Save_the_Date__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Setup_Questionnaire__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Setup Questionnaire</label>
        <referenceTo>Setup_Questionnaire__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Save_the_Date__c.object
<CustomObject>
    <description># 471</description>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to NOFO Group for implementing save the date functionality</description>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ineligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible - COI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Save the Date</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Save the Date ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Save the Date</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Setup_Questionnaire__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFO_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Setup Questionnaires</relationshipLabel>
        <relationshipName>Setup_Questionnaires</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Setup Questionnaire</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>Setup Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FeedbackQuestionCreator.cls
global class FeedbackQuestionCreator
{
/*public  Save_the_Date__c savedraft;
public list<Feedback__c> feedbackstoinsert;
public list<Setup_Questionnaire__c> SetupQuestionnairelist;
  

public Feedbackquestioncreator()
{
savedraft = new Save_the_Date__c ();
SetupQuestionnairelist = new list<Setup_Questionnaire__c>();
feedbackstoinsert = new list<Feedback__c>();

}*/

webservice static void Submit(string SavedraftID)
{
Save_the_Date__c savedraft = new Save_the_Date__c ();
list<Setup_Questionnaire__c> SetupQuestionnairelist = new list<Setup_Questionnaire__c>();
list<Feedback__c> feedbackstoinsert = new list<Feedback__c>();

savedraft = [select id,name,Save_the_Date__c,Status__c from Save_the_Date__c  where id =: SavedraftID];

if(savedraft != null && savedraft.Status__c != 'Submitted')
{

if(savedraft.Save_the_Date__c != null)
{
savedraft.Status__c = 'Submitted';
update savedraft;

SetupQuestionnairelist  = [select id,name,Answer_1__c,Question_1__c from  Setup_Questionnaire__c where NOFO_Group__c =: savedraft.Save_the_Date__c];

if(SetupQuestionnairelist.size()>0)
{
for(Setup_Questionnaire__c sp :SetupQuestionnairelist)
{
Feedback__c fc = new Feedback__c(); 
fc.NOFO_Group__c = savedraft.Save_the_Date__c;
fc.Setup_Questionnaire__c = sp.id;
fc.Save_the_Date__c = savedraft.id;
feedbackstoinsert.add(fc);
}
}
}
if(feedbackstoinsert.size()>0)
{
insert feedbackstoinsert;
}
//pagereference p = new pagereference('/apex/FeedbackScore?Id='+savedraft.Save_the_Date__c);
//return p;
}

}
}