src/objects/Grant_Close_Out__c.object
<CustomObject>
    <fields>
        <fullName>Award_Reporting_Requirements_Met__c</fullName>
        <label>Award Reporting Requirements Met</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Closeout_Reporting_Requirements_Met__c</fullName>
        <label>Closeout Reporting Requirements Met</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost_Share_Balance_Outstanding__c</fullName>
        <label>Cost Share Balance Outstanding</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Members_Exited_From_System__c</fullName>
        <label>Members Exited From System</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Open_Monitoring_Activities__c</fullName>
        <formula>Master_Award__r.Number_of_Open_Monitoring_Activities__c</formula>
        <label>Open Monitoring Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PO_Certified_Date__c</fullName>
        <label>PO Certified Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PO_Name__c</fullName>
        <label>PO Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Closeout Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Momentum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PO Certified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Closeout</label>
    <nameField>
        <displayFormat>GCO-{00000}</displayFormat>
        <label>Closeout Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Closeouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateGrantCloseOut.cls
global Class UpdateGrantCloseOut {
    //Constructor
    public UpdateGrantCloseOut(){
    	
    }
    
    //method for updating grant Close
    static webservice string updateGrantValue(string recId){
    	string errorMessage = '';
    	Profile  prof = [Select id, Name from Profile where Name = 'PO' limit 1];
        if(UserInfo.getProfileId()==prof.id){
    	if(recId != null && recId != ''){
    		list<Grant_Close_Out__c> closeOutList = [Select Id,Status__c,Name,Members_Exited_From_System__c,Award_Reporting_Requirements_Met__c,Cost_Share_Balance_Outstanding__c,Open_Monitoring_Activities__c,Closeout_Reporting_Requirements_Met__c from Grant_Close_Out__c Where Id = :recId Limit 1];
    		if(closeOutList != null && !closeOutList.isEmpty()){
    			if(closeOutList[0].Members_Exited_From_System__c=='Yes' && closeOutList[0].Award_Reporting_Requirements_Met__c=='Yes' && closeOutList[0].Cost_Share_Balance_Outstanding__c=='No' && closeOutList[0].Open_Monitoring_Activities__c==0.0 && closeOutList[0].Closeout_Reporting_Requirements_Met__c=='Yes'){
    				closeOutList[0].Status__c='PO Certified';
    				closeOutList[0].PO_Certified_Date__c=system.date.today();
    				closeOutList[0].PO_Name__c=UserInfo.getName();
    			}else if(closeOutList[0].Members_Exited_From_System__c!='Yes'){
					errorMessage = 'Members are still serving on this grant. Please close all members before closing this grant.';				
				}else if(closeOutList[0].Award_Reporting_Requirements_Met__c!='Yes'){
					errorMessage = 'Reporting activities have not been met. Please make sure that all reporting activities have been met before closing this grant.';
				}else if(closeOutList[0].Cost_Share_Balance_Outstanding__c!='No'){
					errorMessage = 'Cost share balance is outstanding. Please make sure that there is no outstanding costshare balance before closing this grant.';
				}else if(closeOutList[0].Open_Monitoring_Activities__c>0){
					errorMessage = 'Open monitoring activities exist for this grant. Please close all monitoring activities before closing this grant.';
    			}else if(closeOutList[0].Closeout_Reporting_Requirements_Met__c!='Yes'){
					errorMessage = 'Closeout Reporting Requirements have not been met. Please make sure that all closeout reporting requirements have been met before closing this grant.';
    			}
    			update closeOutList[0];
    		}
    	}
     }else{
     	errorMessage = 'Please login as a PO and perform Certification';
     }
    	return errorMessage;
    }
    
}