src/objects/Master_Award__c.object
<CustomObject>
    <fields>
        <fullName>Number_of_Open_Monitoring_Activities__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Open Monitoring Activities</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the Master Award</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Master Award</label>
    <nameField>
        <label>Federal Award Identification Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Monitoring_Activity__c.object
<CustomObject>
    <description>Monitoring Activities associated to Monitoring Plans.</description>
    <fields>
        <fullName>Master_Award_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Award Name</label>
        <referenceTo>Master_Award__c</referenceTo>
        <relationshipLabel>Monitoring Activities</relationshipLabel>
        <relationshipName>Monitoring_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Monitoring_Activity__c</fullName>
        <label>Monitoring Activity</label>
        <picklist>
            <picklistValues>
                <fullName>Programmatic &amp; Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compliance Visit – Programmatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Desk Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drawdown Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up Compliance Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-site Compliance Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-site Training/Technical Assistance (T/TA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity Visit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Standards review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted/Issue-based Site Visit</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Monitoring Activity</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Monitoring Activity Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdateMonitoringActivityCount.cls
public with sharing class UpdateMonitoringActivityCount {
   
    //Constructor
    public UpdateMonitoringActivityCount(){
        
    }
    
    //Method to update Monitoring Activity Count on Master Award.
    public void updateActivityCount(list<Monitoring_Activity__c> MactivityList, map<Id,Monitoring_Activity__c> oldMap){
        //set for MasterAward Ids.
        set<Id> masterAwardIds = new set<Id>();
        
        //map for Master Award and related Award records.
        map<Id,Master_Award__c> masterAwardMap = new map<Id,Master_Award__c>();
        
        //Check for Monitoring Activity List Empty and Null.
        if(MactivityList != null && !MactivityList.isEmpty()){
            for(Monitoring_Activity__c mact: MactivityList){
            //system.debug('oldMap.get(mact.Id).Status__c = '+oldMap.get(mact.Id).Status__c);
                if((mact.Status__c != null && mact.Status__c.equalsIgnorecase('Open')) || (oldMap != null && oldMap.get(mact.Id) != null && oldMap.get(mact.Id).Status__c != null && oldMap.get(mact.Id).Status__c.equalsIgnorecase('Open'))){
                    if(mact.Master_Award_Name__c != null){
                        masterAwardIds.add(mact.Master_Award_Name__c);
                    }
                }//end of If for Status null check and value check.
            }//end of for Loop.
            
            //retrieve Master Award Records with related Monitoring Activity Records.
            if(masterAwardIds != null && !masterAwardIds.isEmpty()){
                masterAwardMap = new map<Id,Master_Award__c>([Select Id,Number_of_Open_Monitoring_Activities__c,(Select Id,Status__c from Monitoring_Activities__r where Status__c = 'Open') from Master_Award__c where ID IN:masterAwardIds]);
            }
            
            //update count on Master Award 
            if(masterAwardMap != null && !masterAwardMap.isEmpty()){
                for(Master_Award__c maw : masterAwardMap.values()){
                    if(maw.Monitoring_Activities__r != null && !maw.Monitoring_Activities__r.isEmpty()){
                        maw.Number_of_Open_Monitoring_Activities__c = maw.Monitoring_Activities__r.size();
                    }else{
                        maw.Number_of_Open_Monitoring_Activities__c = 0;
                    }
                }
                
                update masterAwardMap.values();
            }           
        }//end of IF for Monitoring Activity List Empty check
    }
    
}