src/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>ConfiguredBudgetForms__c</fullName>
        <label>ConfiguredBudgetForms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>NOFO/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFO/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFOs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prime_Application__c.object
<CustomObject>
    <fields>
        <fullName>NOFO_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO/RFP</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR 3</booleanFilter>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>contains</operation>
                <value>Continuation, New &amp; Continuation</value>
            </filterItems>
            <filterItems>
                <field>$Source.CNCS_Corporate_Program__c</field>
                <operation>equals</operation>
                <valueField>NOFA__c.CNCS_Corporate_Program__c</valueField>
            </filterItems>
            <filterItems>
                <field>NOFA__c.NOFA_Type__c</field>
                <operation>equals</operation>
                <value>New, New &amp; Continuation</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prime_Application_Configured_BudgetForms__c</fullName>
        <label>Prime Application Configured BudgetForms</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Prime_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Prime Application</label>
        <referenceTo>Prime_Application__c</referenceTo>
        <relationshipLabel>Prime Applications</relationshipLabel>
        <relationshipName>Prime_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Prime Application</label>
    <nameField>
        <label>Prime Application ID Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prime Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CldBdgPrmAppMultiSelectCntrl.cls
public with sharing class CldBdgPrmAppMultiSelectCntrl{

    public ApexPages.StandardController stdcontroller;
    public SelectOption[] selectedBdgFrms { get; set; }
    public SelectOption[] allBdgFrms { get; set; }
    public String message { get; set; }
    public List<cb3__Budget_Settings__c> lstBudgetForm{get;set;}
    public Prime_Application__c prmApplication{get;set;}
    public Boolean showBdgFrm{get;set;} 
    public string selBudgetForm{get;set;}
    public NOFA__c nofa{get;set;}
    public String nofaId;
    public Map<Id,String> mpBdgFrmIdToTitle{get;set;}
    public Set<String> setConfiguredPrmAppBdgFrmIds{get;set;}
    public Set<String> setAvailableBudgetForms{get;set;}
    public Set<String> setSelectedBudgetForms{get;set;}
         
    public CldBdgPrmAppMultiSelectCntrl(){
          selectedBdgFrms = new List<SelectOption>();
    }
    
    public CldBdgPrmAppMultiSelectCntrl(ApexPages.StandardController p_controller){
        selectedBdgFrms = new List<SelectOption>();
        this.stdcontroller= p_controller;
        this.prmApplication= (Prime_Application__c )stdController.getrecord();
        prmApplication=[select id,name,NOFO_RFP__c,Prime_Application_Configured_BudgetForms__c FROM Prime_Application__c where id= :prmApplication.id];
        if(prmApplication.NOFO_RFP__c!=null){
            nofaId=prmApplication.NOFO_RFP__c;
            retrieveSelectedBudgetFormData();
        }
    }
   
    public void retrieveSelectedBudgetFormData(){
        try{
            allBdgFrms= new List<SelectOption>();
            if(nofaId!=null && nofaId!=''){
                  list<nofa__c> nofas =  new list<nofa__c>([select id,ConfiguredBudgetForms__c FROM NOFA__c WHERE id = :nofaId]);
                  System.debug('***nofa***'+nofa);
                  if(nofas!=null && nofas.size()>0){
                      String strBdgFrmsid=nofas[0].ConfiguredBudgetForms__c ;
                      List<String> lstBdgFrmIds=new List<String>();
                      if(strBdgFrmsid!=null){
                          lstBdgFrmIds =strBdgFrmsid.split(',');
                          System.debug('***lstBdgFrmIds ***'+lstBdgFrmIds );
          
                          lstBudgetForm= [SELECT id,name,cb3__Title__c FROM cb3__Budget_Settings__c where id in :lstBdgFrmIds ORDER BY cb3__Title__c  ]; 
                          System.debug('***lstBudgetForm***'+lstBudgetForm);
                          mpBdgFrmIdToTitle =new Map<Id,String>();
        
                          for(cb3__Budget_Settings__c itrBdgFrm :lstBudgetForm){
                             mpBdgFrmIdToTitle.put(itrBdgFrm.id,itrBdgFrm.cb3__Title__c);
                          }
                       
                          System.debug('***mpBdgFrmIdToTitle***'+mpBdgFrmIdToTitle);
                          exludeConfiguredBdgFrms(lstBudgetForm);
                          String strBdgFrmTitle='';
                           
                          for (String itrStr : setAvailableBudgetForms) {
                                if(mpBdgFrmIdToTitle!=null && mpBdgFrmIdToTitle.containsKey(itrStr)){
                                        strBdgFrmTitle=mpBdgFrmIdToTitle.get(itrStr);
                                    if(strBdgFrmTitle!=null && strBdgFrmTitle!='')
                                        allBdgFrms.add(new SelectOption(itrStr ,strBdgFrmTitle));
                                    }
                                }
                            System.debug('***allBdgFrms***'+allBdgFrms);
                           
                            for (String itrStr : setSelectedBudgetForms) {
                               if(mpBdgFrmIdToTitle!=null && mpBdgFrmIdToTitle.containsKey(itrStr)){
                                    strBdgFrmTitle=mpBdgFrmIdToTitle.get(itrStr);
                                    if(strBdgFrmTitle!=null && strBdgFrmTitle!='')
                                        selectedBdgFrms.add(new SelectOption(itrStr ,strBdgFrmTitle));
                                    }
                            }
                            System.debug('***selectedBdgFrms***'+selectedBdgFrms);
                          }
                  }
            }
           }
           catch(Exception exc){
             System.debug('***exception in method retrieveSelectedBudgetFormData() ***');
           }
    }
    
    public void exludeConfiguredBdgFrms(List<cb3__Budget_Settings__c> p_lstBudgetForm){
        try{        
            String tmpSelectedBdgFrmsId=prmApplication.Prime_Application_Configured_BudgetForms__c;
            setConfiguredPrmAppBdgFrmIds=new Set<String>();
            setAvailableBudgetForms=new Set<String>();
            setSelectedBudgetForms=new Set<String>();
            
            if(prmApplication.Prime_Application_Configured_BudgetForms__c!=null  
                          && prmApplication.Prime_Application_Configured_BudgetForms__c!=''){
                for(String strKey : prmApplication.Prime_Application_Configured_BudgetForms__c.split(',')){
                    setConfiguredPrmAppBdgFrmIds.add(strKey);
                }
                for (cb3__Budget_Settings__c itrBudgetForm : p_lstBudgetForm) {
                    if(!setConfiguredPrmAppBdgFrmIds.contains(itrBudgetForm.id) ){
                        setAvailableBudgetForms.add(itrBudgetForm.id);
                    }else{
                        setSelectedBudgetForms.add(itrBudgetForm.id);
                    }            
                }
            }  else{
                    for (cb3__Budget_Settings__c itrBudgetForm : p_lstBudgetForm) {
                            setAvailableBudgetForms.add(itrBudgetForm.id);
                    }
            }
        }catch(Exception exc){
            System.debug('***exception in method exludeConfiguredBdgFrms() ***');
        }            
    }
    
    public PageReference save() {
        message = 'Selected Budget Forms';
        String bdgFrmIds='';
        Boolean first = true;
        
        for ( SelectOption so : selectedBdgFrms ) {
            if (!first) {
                message += ', ';
                bdgFrmIds+=',';
            }
            message += so.getLabel() + ' (' + so.getValue() + ')';
            bdgFrmIds+=  so.getValue();
            first = false;
        }
        
        prmApplication.Prime_Application_Configured_BudgetForms__c =  bdgFrmIds;
        
        try{
            update prmApplication;
        }
        catch(Exception exc){
           System.debug('CldBdgPrmAppMultiSelectCntrl -save() method -Exception *** '+ exc);
        }
        return null;
    }
   
}