src/objects/NOFA_Group__c.object
<CustomObject>
    <label>NOFO Group</label>
    <nameField>
        <displayFormat>NOFA Group ID-{0000}</displayFormat>
        <label>NOFO Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reviewer_Pool__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Reviewer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expert Reviewer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviewer Pools</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Reviewer Pool</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Reviewer Pool</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Reviewer Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewer Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddPanelMembersContTest.cls
@isTest
private class AddPanelMembersContTest {
	public static AddPanelMembersCont ext;
    static testMethod void myUnitTest() {
       Nofa_Group__c ng = Utilityclass.createNofaGroup();
       insert ng;
       
       Contact c = UtilityClass.createContact();
       insert c;
       
       Reviewer_Pool__c	rp = UtilityClass.createReviewerPool();
       rp.NOFA_Group__c = ng.Id;
       rp.Expert_Reviewer_Name__c = c.Id;
       insert rp;
       
       Stages__c stage = UtilityClass.createStage();
       stage.NOFA_Group__c = ng.Id;
       insert stage;
       
       Paneling__c panel = UtilityClass.createPanel();
       panel.Stage_Number__c = stage.Id;
       insert panel;       
       
       
       PageReference pref = Page.AddPanelMembers; 
       test.setCurrentPage(pref);      
       pref.getParameters().put('Id',panel.Id);
       ext = new AddPanelMembersCont();
       Apexpages.currentPage().getParameters().put('area','CNCS');
       Apexpages.currentPage().getParameters().put('residence','VA');
       Apexpages.currentPage().getParameters().put('education','Less Than High School');
       Apexpages.currentPage().getParameters().put('status',' ');
       Apexpages.currentPage().getParameters().put('rating','0');
       Apexpages.currentPage().getParameters().put('Experience','2');
       //ext.wrappedContacts.add(new contactWrapper(c));
       ext.getContacts();
       ext.runSearch();              
       ext.savePanelMembers();
       ext.cancel();
        
    }
}