src/objects/NOFA_Group__c.object
<CustomObject>
    <fields>
        <fullName>Legacy_NOFO_Group_ID__c</fullName>
        <label>Legacy NOFO Group ID</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External or Blended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Review_of__c</fullName>
        <label>Review of</label>
        <picklist>
            <picklistValues>
                <fullName>Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concept papers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFO Group</label>
    <nameField>
        <displayFormat>NOFA Group ID-{0000}</displayFormat>
        <label>NOFO Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFO Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reviewer_Pool__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Reviewer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expert Reviewer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviewer Pools</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Reviewer Pool</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Experience Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Control Reiviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Rater Reliability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Review Quality Control</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available with Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible – COI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reviewer Pool</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Reviewer Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewer Pool</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Save_the_Date__c.object
<CustomObject>
    <description># 471</description>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <formula>Reviewer_Pool__r.Expert_Reviewer_Name__r.FirstName&amp; &apos; &apos; &amp;Reviewer_Pool__r.Expert_Reviewer_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expert Reviewer Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expert_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Save the date functionality</description>
        <label>Expert Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer_Pool__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Save the date functionality</description>
        <label>Reviewer Pool</label>
        <referenceTo>Reviewer_Pool__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Type__c</fullName>
        <label>Role Type</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Expertise Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Save_the_Date__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to NOFO Group for implementing save the date functionality</description>
        <label>NOFO Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Save the Date</relationshipLabel>
        <relationshipName>Save_the_Date</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ineligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible - COI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Confirmed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Save the Date</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Save the Date ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Save the Date</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SavetheDateAnnouncements.cls
/********************************************************************************************
Class Name: SavetheDateAnnouncements
Description: An apex controller for SavetheDate Page.
             Creates Save the Date Pool for each reviewer from the Reviewer Pool.
**********************************************************************************************
Modified By:Pratyusha Mungamuri
Modified On:10/19/2016
Purpose:Comments
**********************************************************************************************/
public class SavetheDateAnnouncements
{
    private ApexPages.StandardController standardController;
    
 
    public SavetheDateAnnouncements(ApexPages.StandardController standardController)
    {
        this.standardController = standardController;
    }
    public PageReference DateAnnouncements()
    {
     
        // Apex code for handling record from a Detail page goes here
        Id recordId = standardController.getId();
        NOFA_Group__c Ngroup = [Select Id, Legacy_NOFO_Group_ID__c,Name__c, Review_of__c, Review_Type__c, Status__c from NOFA_Group__c where Id = :recordId];
        Set<Id> ReviewerPoolIDs = new Set<Id>();
        set<Id> contactIds = new set<Id>();
        set<Id> userIds = new set<Id>();
               
        map<Id,Reviewer_Pool__c> reviewerIdtoPMId = new map<Id,Reviewer_Pool__c>();
        map<Id,Id> PQ= new map<Id,Id>();
        List<Save_the_Date__c> Savethedatepool = new List<Save_the_Date__c>();
        System.debug('RecordId*****' +recordId);
       
       /* Get a list of all of the Contacts associated to the Reviewer Pool*/
        List<Reviewer_Pool__c> reviewerPoolList = new List<Reviewer_Pool__c>();
        reviewerPoolList = [SELECT Id,Expert_Reviewer_Name__c,Roles__c FROM Reviewer_Pool__c where NOFA_Group__c= :recordId];
        for(Reviewer_Pool__c rp: reviewerPoolList){
          ReviewerPoolIDs.add(rp.Expert_Reviewer_Name__c);
          reviewerIdtoPMId.put(rp.Expert_Reviewer_Name__c,rp); 
        }
        
        /* Create an Save the Date Pool for each Reviewer */
        for (ID rpID: ReviewerPoolIDs){
            Save_the_Date__c std = new Save_the_Date__c();
            if(rpID != null)
            {
            std.Expert_Reviewer__c = rpID;
            std.Save_the_Date__c = recordId;
            std.Reviewer_Pool__c = reviewerIdtoPMId.get(rpID).Id;
            contactIds.add(std.Expert_Reviewer__c);
            std.Role_Type__c = reviewerIdtoPMId.get(rpID).Roles__c;
          
            //Set the Status 
            Savethedatepool.add(std);
            }
        }
        
        system.debug('savethedatalist'+ Savethedatepool.size());
        insert Savethedatepool;   
        PageReference pageRef = new PageReference('/'+Ngroup.Id);
        pageRef.setRedirect(true);
       return pageRef;
    }
}