src/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Disaster_Type__c</fullName>
        <label>Disaster Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Focus_Area__c</fullName>
        <label>Focus Area</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <label>Organization Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <label>Organization</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Project_State__c</fullName>
        <label>Project State</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Round__c</fullName>
        <label>Round</label>
        <type>TextArea</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Round__c.object
<CustomObject>
    <label>Round</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Round Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicationSearchCont.cls
public class ApplicationSearchCont {
	
	public Paneling__c panel{get;set;}
	public String panelId {get;set;}
    public ApplicationSearchCont(ApexPages.StandardController controller) {
    	panelId = Apexpages.currentPage().getParameters().get('id'); 
		panel = new Paneling__c();
		if(panelId!=null && panelId != ''){
			panel = [Select Id,Name, Disaster_Type__c,Focus_Area__c,Organization__c,Organization_Type__c,Project_State__c,	Round__c from Paneling__c
				where Id = :panelId];
		}
				
    }
    
    public ApplicationSearchCont getThis(){
        return this;
    }
    
    public pageReference SaveParameters(){
    	if(panel!=null){
    		update panel;
    		PageReference pg = new PageReference('/'+panelId);
        	return pg;
    	}
    	return null;
    }

}