src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <label>Zip</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/projectaddrresdocotrext.cls
public with sharing class projectaddrresdocotrext {

    public string USERNAME='160781 ';
    public string PASSWORD='Strike1';
    public Project__c pro {get; set;}
    public List<AddressdoctorComWebservice5.Address> responseAddresses{get;set;}
    public projectaddrresdocotrext(ApexPages.StandardController controller) {

       pro=(Project__c)controller.getRecord();
       responseAddresses=new List<AddressdoctorComWebservice5.Address>();
       doCallout();

    }
    
    public PageReference doCallout()
    {
           
            AddressdoctorComWebservice5.ArrayOfString Street=new AddressdoctorComWebservice5.ArrayOfString();
            Street.string_x=new string[]{pro.Street_Address_1__c};
            AddressdoctorComWebservice5.ArrayOfString PostalCode=new AddressdoctorComWebservice5.ArrayOfString();
            PostalCode.string_x=new string[]{string.valueof(pro.Zip__c)};
             AddressdoctorComWebservice5.ArrayOfString Province=new AddressdoctorComWebservice5.ArrayOfString();
            Province.string_x=new string[]{pro.State__c};
            AddressdoctorComWebservice5.ArrayOfString Country=new AddressdoctorComWebservice5.ArrayOfString();
            Country.string_x=new string[]{pro.country__c};
            
            AddressdoctorComWebservice5.AddressValidationSoap    doctorCall=new AddressdoctorComWebservice5.AddressValidationSoap();
            
            
            AddressdoctorComWebservice5.Parameters parameters=new AddressdoctorComWebservice5.Parameters();
            parameters.ProcessMode='BATCH';
            AddressdoctorComWebservice5.Address[] Add_resses=new AddressdoctorComWebservice5.Address[1];
            AddressdoctorComWebservice5.Address Addres=new AddressdoctorComWebservice5.Address();
            Addres.Street=Street;
            Addres.PostalCode=PostalCode;
            Addres.Province=Province;
            Addres.Country=Country;
              
                
            Add_resses[0]=Addres;
            
            AddressdoctorComWebservice5.ArrayOfAddress  arrayofAddress=new AddressdoctorComWebservice5.ArrayOfAddress ();
            arrayofAddress.Address=Add_resses;
            
            AddressdoctorComWebservice5.ArrayOfAddress addresses=arrayofAddress;
             
            AddressdoctorComWebservice5.ArrayOfEnrichment enrichments;
            
            AddressdoctorComWebservice5.Response response=new AddressdoctorComWebservice5.Response();
            response=doctorCall.Process(USERNAME,PASSWORD,parameters,addresses,enrichments);
            
            system.debug('response=================>'+response.statusCode);
            
            AddressdoctorComWebservice5.Result[]  results=response.Results.Result;
            for(AddressdoctorComWebservice5.Result result:response.Results.Result)
            {
                for(AddressdoctorComWebservice5.ResultData  resultAd:result.ResultDataSet.ResultData)
                {
                
                    system.debug('result is===='+result);
                    AddressdoctorComWebservice5.Address Address=resultAd.Address;
                    responseAddresses.add(resultAd.Address);
                    system.debug('=@@@='+address.street.string_x);
                    system.debug('=@@@='+address.province.string_x);
                    //system.debug('=@@@='+address.Locality.string_x);
                    system.debug('=@@@='+address.PostalCode.string_x);
                   system.debug('=@@@='+address.Country.string_x);
                    //+'===='+address.Street.string_x+'===='+address.Country.string_x+'====='+address.Province.string_x+'====='+address.DeliveryAddressLines.string_x);
                }
            }
            
            return null;
    
    
    
    }

}